using AutoMapper;
using Molinos.Scato.Dominio.Dto;
using Molinos.Scato.Dominio.Entidades;

namespace Molinos.Scato.Servicios.Conversiones.Impl.Perfiles
{
    public class CartaPorteMappingProfile : Profile
    {
        public override string ProfileName
        {
            get { return "CartaPorteMappingProfile"; }
        }
        protected override void Configure()
        {
            Mapper.CreateMap<CartaPorte, CartaPorteDto>()
                  .ForMember(t => t.Transportista, f => f.MapFrom(r => r.Transportista.RazonSocial))
                  .ForMember(t => t.TransportistaId, f => f.MapFrom(r => r.Transportista.Id))
                  .ForMember(t => t.TransportistaCUIT, f => f.MapFrom(r => r.Transportista.Cuit))
                  .ForMember(t => t.TipoComercial, f => f.MapFrom(r => r.TipoComercial.Descripcion))
                  .ForMember(t => t.TipoComercialSentido, f => f.MapFrom(r => r.TipoComercial.Sentido))
                  .ForMember(t => t.TipoComercialId, f => f.MapFrom(r => r.TipoComercial.Id))
                  .ForMember(t => t.TipoComercialCodigoSap, f => f.MapFrom(r => r.TipoComercial.CodigoSap))
                  .ForMember(t => t.Material, f => f.MapFrom(r => r.Material.Descripcion))
                  .ForMember(t => t.MaterialId, f => f.MapFrom(r => r.Material.Id))
                  .ForMember(t => t.MaterialPideLote, f => f.MapFrom(r => r.Material.Lote))
                  .ForMember(t => t.MaterialPideContrato, f => f.MapFrom(r => r.Material.Contrato))
                  .ForMember(t => t.MaterialCodigoSap, f => f.MapFrom(r => r.Material.CodigoSAP))
                  .ForMember(t => t.Procedencia, f => f.MapFrom(r => r.Procedencia.Descripcion))
                  .ForMember(t => t.ProcedenciaId, f => f.MapFrom(r => r.Procedencia.Id))
                  .ForMember(t => t.ProcedenciaCodigoSap, f => f.MapFrom(r => r.Procedencia.CodigoAfip))
                  .ForMember(t => t.ProvinciaDescripcion, f => f.MapFrom(r => r.Procedencia.Provincia.Descripcion))
                  .ForMember(t => t.ProvinciaCodigoSap, f => f.MapFrom(r => r.Procedencia.Provincia.CodigoAfip))
                  .ForMember(t => t.ProvinciaId, f => f.MapFrom(r => r.Procedencia.Provincia.Id))
                  .ForMember(t => t.TitularCartaPorte, f => f.MapFrom(r => r.TitularCartaPorte.Descripcion))
                  .ForMember(t => t.TitularCartaPorteId, f => f.MapFrom(r => r.TitularCartaPorte.Id))
                  .ForMember(t => t.TitularCartaPorteCodigoSap, f => f.MapFrom(r => r.TitularCartaPorte.CodigoSap))
                  .ForMember(t => t.TitularCartaPorteCuil, f => f.MapFrom(r => r.TitularCartaPorte.Cuil))
                  .ForMember(t => t.TitularCartaPorteMail, f => f.MapFrom(r => r.TitularCartaPorte.EnvioAutomaticoMail && r.TitularCartaPorte.EsTitularCP && !string.IsNullOrEmpty(r.TitularCartaPorte.Mail) ? r.TitularCartaPorte.Mail : string.Empty))
                  .ForMember(t => t.TitularCartaPorteEnvioMailEnAnalisis, f => f.MapFrom(r => r.TitularCartaPorte.Analisis))
                  .ForMember(t => t.TitularCartaPorteEnvioMailEnPesada, f => f.MapFrom(r => r.TitularCartaPorte.Pesada))
                  .ForMember(t => t.Intermediario, f => f.MapFrom(r => r.Intermediario.Descripcion))
                  .ForMember(t => t.IntermediarioId, f => f.MapFrom(r => r.Intermediario.Id))
                  .ForMember(t => t.IntermediarioCodigoSap, f => f.MapFrom(r => r.Intermediario.CodigoSap))
                  .ForMember(t => t.IntermediarioCuit, f => f.MapFrom(r => r.Intermediario.Cuil))
                  .ForMember(t => t.IntermediarioMail, f => f.MapFrom(r => r.Intermediario.EnvioAutomaticoMail && r.Intermediario.EsIntermediario && !string.IsNullOrEmpty(r.Intermediario.Mail) ? r.Intermediario.Mail : string.Empty))
                  .ForMember(t => t.IntermediarioEnvioMailEnAnalisis, f => f.MapFrom(r => r.Intermediario.Analisis))
                  .ForMember(t => t.IntermediarioEnvioMailEnPesada, f => f.MapFrom(r => r.Intermediario.Pesada))
                  .ForMember(t => t.RtteComercial, f => f.MapFrom(r => r.RtteComercial.Descripcion))
                  .ForMember(t => t.RtteComercialId, f => f.MapFrom(r => r.RtteComercial.Id))
                  .ForMember(t => t.RtteComercialCodigoSap, f => f.MapFrom(r => r.RtteComercial.CodigoSap))
                  .ForMember(t => t.RtteComercialCuit, f => f.MapFrom(r => r.RtteComercial.Cuil))
                  .ForMember(t => t.RtteComercialMail, f => f.MapFrom(r => r.RtteComercial.EnvioAutomaticoMail && r.RtteComercial.EsRemitenteComercial && !string.IsNullOrEmpty(r.RtteComercial.Mail) ? r.RtteComercial.Mail : string.Empty))
                  .ForMember(t => t.RtteProvinciaLegal, f => f.MapFrom(r => r.RtteComercial.Provincia.Descripcion))
                  .ForMember(t => t.RtteLocalidadLegal, f => f.MapFrom(r => r.RtteComercial.Localidad.Descripcion))
                  .ForMember(t => t.RtteDomicilioLegal, f => f.MapFrom(r => r.RtteComercial.Domicilio))
                  .ForMember(t => t.RtteComercialEnvioMailEnAnalisis, f => f.MapFrom(r => r.RtteComercial.Analisis))
                  .ForMember(t => t.RtteComercialEnvioMailEnPesada, f => f.MapFrom(r => r.RtteComercial.Pesada))
                  .ForMember(t => t.Corredor, f => f.MapFrom(r => r.Corredor.Descripcion))
                  .ForMember(t => t.CorredorId, f => f.MapFrom(r => r.Corredor.Id))
                  .ForMember(t => t.CorredorVendedor, f => f.MapFrom(r => r.CorredorVendedor.Descripcion))
                  .ForMember(t => t.CorredorVendedorId, f => f.MapFrom(r => r.CorredorVendedor.Id))
                  .ForMember(t => t.CorredorVendedorCuil, f => f.MapFrom(r => r.CorredorVendedor.Cuil))
                  .ForMember(t => t.TipoCategoriaId, f => f.MapFrom(r => r.Categoria.Id))
                  .ForMember(t => t.TipoCategoria, f => f.MapFrom(r => r.Categoria.Clasificacion))
                  .ForMember(t => t.IntermediarioFlete, f => f.MapFrom(r => r.IntermediarioFlete.Descripcion))
                  .ForMember(t => t.IntermediarioFleteId, f => f.MapFrom(r => r.IntermediarioFlete.Id))
                  .ForMember(t => t.IntermediarioFleteCuil, f => f.MapFrom(r => r.IntermediarioFlete.Cuil))
                  .ForMember(t => t.Entregador, f => f.MapFrom(r => r.Entregador.RazonSocial))
                  .ForMember(t => t.EntregadorId, f => f.MapFrom(r => r.Entregador.Id))
                  .ForMember(t => t.EntregadorCuit, f => f.MapFrom(r => r.Entregador.Cuil))
                  .ForMember(t => t.EntregadorMail, f => f.MapFrom(r => r.Entregador.EnvioAutomaticoMail && !string.IsNullOrEmpty(r.Entregador.Mail) ? r.Entregador.Mail : string.Empty))
                  .ForMember(t => t.EntregadorEnvioMailEnAnalisis, f => f.MapFrom(r => r.Entregador.Analisis))
                  .ForMember(t => t.EntregadorEnvioMailEnPesada, f => f.MapFrom(r => r.Entregador.Pesada))
                  .ForMember(t => t.AgenteCompras, f => f.MapFrom(r => r.AgenteCompras.Descripcion))
                  .ForMember(t => t.AgenteComprasId, f => f.MapFrom(r => r.AgenteCompras.Id))
                  .ForMember(t => t.AgenteComprasCuil, f => f.MapFrom(r => r.AgenteCompras.Cuil))
                  .ForMember(t => t.Destinatario, f => f.MapFrom(r => r.Destinatario != null ? r.Destinatario.Descripcion : r.DestinatarioCliente.Descripcion))
                  .ForMember(t => t.DestinatarioId, f => f.MapFrom(r => r.Destinatario != null ? r.Destinatario.Id : r.DestinatarioCliente.Id))
                  .ForMember(t => t.DestinatarioCodigoSap, f => f.MapFrom(r => r.Destinatario != null ? r.Destinatario.CodigoSap : r.DestinatarioCliente.CodigoSap))
                  .ForMember(t => t.DestinatarioCuil, f => f.MapFrom(r => r.Destinatario != null ? r.Destinatario.Cuil : r.DestinatarioCliente.Cuit))
                  .ForMember(t => t.DestinatarioMail, f => f.MapFrom(r => r.Destinatario != null && r.Destinatario.EnvioAutomaticoMail && r.Destinatario.EsDestinatario && !string.IsNullOrEmpty(r.Destinatario.Mail) ? r.Destinatario.Mail : string.Empty))
                  .ForMember(t => t.DestinatarioEnvioMailEnAnalisis, f => f.MapFrom(r => r.Destinatario != null && r.Destinatario.Analisis))
                  .ForMember(t => t.DestinatarioEnvioMailEnPesada, f => f.MapFrom(r => r.Destinatario != null && r.Destinatario.Pesada))
                  .ForMember(t => t.DestinatarioProvincia, f => f.MapFrom(r => r.Destinatario != null ? r.Destinatario.Provincia.Descripcion : r.DestinatarioCliente.Provincia))
                  .ForMember(t => t.DestinatarioLocalidad, f => f.MapFrom(r => r.Destinatario != null ? r.Destinatario.Localidad.Descripcion : r.DestinatarioCliente.Localidad))
                  .ForMember(t => t.DestinatarioDomicilio, f => f.MapFrom(r => r.Destinatario != null ? r.Destinatario.Domicilio : r.DestinatarioCliente.Direccion))
                  .ForMember(t => t.Prestador, f => f.MapFrom(r => r.Prestador.Descripcion))
                  .ForMember(t => t.PrestadorId, f => f.MapFrom(r => r.Prestador.Id))
                  .ForMember(t => t.PrestadorCodigoSap, f => f.MapFrom(r => r.Prestador.CodigoSap))
                  .ForMember(t => t.AgenteComprasCodigoSap, f => f.MapFrom(r => r.AgenteCompras.CodigoSap))
                  .ForMember(t => t.CorredorCodigoSap, f => f.MapFrom(r => r.Corredor.CodigoSap))
                  .ForMember(t => t.CorredorCuil, f => f.MapFrom(r => r.Corredor.Cuil))
                  .ForMember(t => t.DestinoCodigoSap, f => f.MapFrom(r => r.CentroDestino != null ? r.CentroDestino.CodigoSAP : r.ClienteDestino.CodigoSap))
                  .ForMember(t => t.Destino, f => f.MapFrom(r => r.CentroDestino != null ? r.CentroDestino.Descripcion : r.ClienteDestino.Descripcion))
                  .ForMember(t => t.DestinoId, f => f.MapFrom(r => r.CentroDestino != null ? r.CentroDestino.Id : r.ClienteDestino.Id))
                  .ForMember(t => t.DestinoDireccion, f => f.MapFrom(r => r.CentroDestino != null ? r.CentroDestino.Direccion : r.ClienteDestino.Direccion))
                  .ForMember(t => t.DestinoProvincia, f => f.MapFrom(r => r.CentroDestino != null ? r.CentroDestino.Provincia.Descripcion : r.ClienteDestino.Provincia))
                  .ForMember(t => t.DestinoLocalidad, f => f.MapFrom(r => r.CentroDestino != null ? r.CentroDestino.Localidad.Descripcion : r.ClienteDestino.Localidad))
                  .ForMember(t => t.DestinoCodigoPostal, f => f.MapFrom(r => r.CentroDestino != null ? r.CentroDestino.CodigoPostal : null))
                  .ForMember(t => t.BocaDestinoOncca, f => f.MapFrom(r => r.BocaDestino.CodigoONCCA))
                  .ForMember(t => t.BocaDestino, f => f.MapFrom(r => r.BocaDestino.NombreBocaDeDestino))
                  .ForMember(t => t.BocaDestinoDomicilio, f => f.MapFrom(r => r.BocaDestino.Domicilio))
                  .ForMember(t => t.BocaDestinoLocalidad, f => f.MapFrom(r => r.BocaDestino.Localidad.Descripcion))
                  .ForMember(t => t.BocaDestinoProvincia, f => f.MapFrom(r => r.BocaDestino.Provincia.Descripcion))
                  .ForMember(t => t.CuitProveedorBocaDestino, f => f.MapFrom(r => r.BocaDestino.Proveedor.Cuil))
                  .ForMember(t => t.NombreProveedorBocaDestino, f => f.MapFrom(r => r.BocaDestino.Proveedor.RazonSocial))
                  .ForMember(t => t.BocaDestinoCodigoPostal, f => f.MapFrom(r => r.BocaDestino.CodigoPostal))
                  .ForMember(t => t.DestinoCuit, f => f.MapFrom(r => r.CentroDestino != null ? r.CentroDestino.Cuit : r.ClienteDestino.Cuit))
                  .ForMember(t => t.DestinoLocalidadCodigoSap, f => f.MapFrom(r => r.CentroDestino != null ? r.CentroDestino.Localidad.CodigoAfip : r.ClienteDestino.Localidad))
                  .ForMember(t => t.MaterialCodigoEspecie, f => f.MapFrom(r => r.Material.CodigoEspecie))
                  .ForMember(t => t.MaterialTipoGrano, f => f.MapFrom(r => r.Material.TipoDeGrano))
                  .ForMember(t => t.EsClienteDestinatario, f => f.MapFrom(r => r.DestinatarioCliente != null))
                  .ForMember(t => t.Tecnologia, f => f.MapFrom(r => r.Tecnologia.Nombre))
                  .ForMember(t => t.TecnologiaId, f => f.MapFrom(r => r.Tecnologia.Id))
                  .ForMember(t => t.CodigoAnexo, f => f.MapFrom(r => r.CodigoAnexo))
                  .ForMember(t => t.KmARecorrer, f => f.MapFrom(r => r.KmRecorrer.HasValue ? r.KmRecorrer.ToString() : ""))
                  .ForMember(t => t.Cpe, f => f.MapFrom(r => r.Cpe.HasValue && r.Cpe.Value))
                  .ForMember(t => t.RtteComercialProductorId, f => f.MapFrom(r => r.RtteComercialProductor.Id))
                  .ForMember(t => t.Sucursal, f => f.MapFrom(r => r.Sucursal))
                  .ForMember(t => t.Cosecha, f => f.MapFrom(r => r.Cosecha))
                  .ForMember(t => t.DestinoProvinciaCodigoAfip, f => f.MapFrom(r => r.CentroDestino.Provincia.CodigoAfip))
                  .ForMember(t => t.DestinoLocalidadCodigoAfip, f => f.MapFrom(r => r.CentroDestino.Localidad.CodigoAfip))
                  .ForMember(t => t.DestinoPlantaAfip, f => f.MapFrom(r => r.CentroDestino.Planta))
                  .ForMember(t => t.CorredorVendedorSecundarioCuil, f => f.MapFrom(r => r.CorredorVendedorSecundario.Cuil))
                  .ForMember(t => t.RtteComercialProductorCuil, f => f.MapFrom(r => r.RtteComercialProductor.Cuil))
                  .ForMember(t => t.CorredorVendedorSecundarioId, f => f.MapFrom(r => r.CorredorVendedorSecundario.Id))
                  .ForMember(t => t.CorredorVendedorSecundario, f => f.MapFrom(r => r.CorredorVendedorSecundario.Descripcion))
                  .ForMember(t => t.RtteComercialProductor, f => f.MapFrom(r => r.RtteComercialProductor.Descripcion))
                  .ForMember(t => t.RtteComercialVentaSecundarioId, f => f.MapFrom(r => r.RtteComercialVentaSecundaria.Id))
                  .ForMember(t => t.RtteComercialVentaSecundarioCodigoSap, f => f.MapFrom(r => r.RtteComercialVentaSecundaria.CodigoSap))
                  .ForMember(t => t.RtteComercialVentaSecundario, f => f.MapFrom(r => r.RtteComercialVentaSecundaria.Descripcion))
                  .ForMember(t => t.RtteComercialVentaSecundarioCuil, f => f.MapFrom(r => r.RtteComercialVentaSecundaria.Cuil))
                  .ForMember(t => t.RtteComercialVentaSecundario2Id, f => f.MapFrom(r => r.RtteComercialVentaSecundaria2.Id))
                  .ForMember(t => t.RtteComercialVentaSecundario2CodigoSap, f => f.MapFrom(r => r.RtteComercialVentaSecundaria2.CodigoSap))
                  .ForMember(t => t.RtteComercialVentaSecundario2, f => f.MapFrom(r => r.RtteComercialVentaSecundaria2.Descripcion))
                  .ForMember(t => t.RtteComercialVentaSecundario2Cuil, f => f.MapFrom(r => r.RtteComercialVentaSecundaria2.Cuil))
                  .ForMember(t => t.CorredorVendedorSecundarioCodigoSap, f => f.MapFrom(r => r.CorredorVendedorSecundario.CodigoSap))
                  .ForMember(t => t.CodigoRamalId, f => f.MapFrom(r => r.RamalFerroviario.Id))
                  .ForMember(t => t.CodigoRamalAfip, f => f.MapFrom(r => r.RamalFerroviario.CodigoAfip))
                  .ForMember(t => t.CodigoRamal, f => f.MapFrom(r => r.RamalFerroviario.Descripcion))
                  .ForMember(t => t.TransportistaTramo2, f => f.MapFrom(r => r.TransportistaTramo2.RazonSocial))
                  .ForMember(t => t.TransportistaTramo2Id, f => f.MapFrom(r => r.TransportistaTramo2.Id))
                  .ForMember(t => t.TransportistaTramo2CUIT, f => f.MapFrom(r => r.TransportistaTramo2.Cuit))
                  .ForMember(t => t.PagadorFlete, f => f.MapFrom(r => r.PagadorFlete.RazonSocial))
                  .ForMember(t => t.PagadorFleteId, f => f.MapFrom(r => r.PagadorFlete.Id))
                  .ForMember(t => t.PagadorFleteCuil, f => f.MapFrom(r => r.PagadorFlete.Cuil))
                  .ForMember(t => t.TransportistaTramo2CUIT, f => f.MapFrom(r => r.TransportistaTramo2.Cuit))
                  .ForMember(t => t.RepresentanteRecibidor, f => f.MapFrom(r => r.RepresentanteRecibidor.RazonSocial))
                  .ForMember(t => t.RepresentanteRecibidorId, f => f.MapFrom(r => r.RepresentanteRecibidor.Id))
                  .ForMember(t => t.RepresentanteRecibidorCuil, f => f.MapFrom(r => r.RepresentanteRecibidor.Cuil));
            Mapper.CreateMap<CartaPorteDto, CartaPorte>();

            Mapper.CreateMap<CartaPorte, InfoCaladoDto>()
                  .ForMember(t => t.TitularCartaPorte, f => f.MapFrom(r => r.TitularCartaPorte.Descripcion))
                  .ForMember(t => t.Entregador, f => f.MapFrom(r => r.Entregador.RazonSocial))
                  .ForMember(t => t.AgenteCompras, f => f.MapFrom(r => r.AgenteCompras.Descripcion))
                  .ForMember(t => t.RtteComercial, f => f.MapFrom(r => r.RtteComercial.Descripcion))
                  .ForMember(t => t.CTG, f => f.MapFrom(r => r.CTG))
                  .ForMember(t => t.EnvioDirectoCamara, f => f.MapFrom(r => (r.RtteComercial != null && r.RtteComercial.EnvioCamaraDirecto) || (r.RtteComercial == null && r.TitularCartaPorte.EnvioCamaraDirecto)))
                  .ForMember(t => t.Procedencia, f => f.MapFrom(r => r.Procedencia != null ? r.Procedencia.Descripcion : string.Empty));
        }
    }
}
