//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque", ConfigurationName="AFIPServicioConsultaComunicacionEmbarque.wconscomunicacionembarqueSoap")]
    public interface wconscomunicacionembarqueSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/ObtenerConsultaEstadosCOEM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntidadGenerica))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSAutenticacion))]
        Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoEstadoProceso ObtenerConsultaEstadosCOEM(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/ObtenerConsultaEstadosCOEM", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoEstadoProceso> ObtenerConsultaEstadosCOEMAsync(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/ObtenerConsultaNoAbordo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntidadGenerica))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSAutenticacion))]
        Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoNoAbordoProceso ObtenerConsultaNoAbordo(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/ObtenerConsultaNoAbordo", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoNoAbordoProceso> ObtenerConsultaNoAbordoAsync(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/ObtenerConsultaSolicitudes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntidadGenerica))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSAutenticacion))]
        Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoSolicitudProceso ObtenerConsultaSolicitudes(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/ObtenerConsultaSolicitudes", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoSolicitudProceso> ObtenerConsultaSolicitudesAsync(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/DummyTestConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntidadGenerica))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSAutenticacion))]
        Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyTestConnectionOutput DummyTestConnection(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa wsAutenticacion, Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.DummyTestConnectionInput dummyTestConnectionInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/DummyTestConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyTestConnectionOutput> DummyTestConnectionAsync(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa wsAutenticacion, Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.DummyTestConnectionInput dummyTestConnectionInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/DummyTestConnectionOrg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntidadGenerica))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSAutenticacion))]
        Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyTestConnectionOutput DummyTestConnectionOrg(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionOrganismo wsAutenticacion, Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.DummyTestConnectionInput dummyTestConnectionInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/DummyTestConnectionOrg", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyTestConnectionOutput> DummyTestConnectionOrgAsync(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionOrganismo wsAutenticacion, Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.DummyTestConnectionInput dummyTestConnectionInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/Dummy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractEntidadGenerica))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSAutenticacion))]
        Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyOutput Dummy();
        
        [System.ServiceModel.OperationContractAttribute(Action="Ar.Gob.Afip.Dga.wconscomunicacionembarque/Dummy", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyOutput> DummyAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class WSAutenticacionEmpresa : WSAutenticacion {
        
        private long cuitEmpresaConectadaField;
        
        private string tipoAgenteField;
        
        private string rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long CuitEmpresaConectada {
            get {
                return this.cuitEmpresaConectadaField;
            }
            set {
                this.cuitEmpresaConectadaField = value;
                this.RaisePropertyChanged("CuitEmpresaConectada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TipoAgente {
            get {
                return this.tipoAgenteField;
            }
            set {
                this.tipoAgenteField = value;
                this.RaisePropertyChanged("TipoAgente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("Rol");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSAutenticacionOrganismo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSAutenticacionEmpresa))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class WSAutenticacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string signField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("Sign");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class DummyOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appServerField;
        
        private string dbServerField;
        
        private string authServerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AppServer {
            get {
                return this.appServerField;
            }
            set {
                this.appServerField = value;
                this.RaisePropertyChanged("AppServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DbServer {
            get {
                return this.dbServerField;
            }
            set {
                this.dbServerField = value;
                this.RaisePropertyChanged("DbServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AuthServer {
            get {
                return this.authServerField;
            }
            set {
                this.authServerField = value;
                this.RaisePropertyChanged("AuthServer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ResultadoEjecucionOfDummyOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverField;
        
        private System.DateTime timeStampField;
        
        private DummyOutput resultadoField;
        
        private ErrorEjecucion[] erroresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
                this.RaisePropertyChanged("Server");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DummyOutput Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ErrorEjecucion[] Errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
                this.RaisePropertyChanged("Errores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ErrorEjecucion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ResultadoEjecucionOfDummyTestConnectionOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverField;
        
        private System.DateTime timeStampField;
        
        private DummyTestConnectionOutput resultadoField;
        
        private ErrorEjecucion[] erroresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
                this.RaisePropertyChanged("Server");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DummyTestConnectionOutput Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ErrorEjecucion[] Errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
                this.RaisePropertyChanged("Errores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class DummyTestConnectionOutput : AbstractEntidadOfInt32 {
        
        private int numericoEnteroField;
        
        private decimal numericoDecimalField;
        
        private string caracteresField;
        
        private System.DateTime fechaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NumericoEntero {
            get {
                return this.numericoEnteroField;
            }
            set {
                this.numericoEnteroField = value;
                this.RaisePropertyChanged("NumericoEntero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal NumericoDecimal {
            get {
                return this.numericoDecimalField;
            }
            set {
                this.numericoDecimalField = value;
                this.RaisePropertyChanged("NumericoDecimal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Caracteres {
            get {
                return this.caracteresField;
            }
            set {
                this.caracteresField = value;
                this.RaisePropertyChanged("Caracteres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DummyTestConnectionOutput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public abstract partial class AbstractEntidadOfInt32 : AbstractEntidadGenerica {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractEntidadOfInt32))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DummyTestConnectionOutput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractEntidadOfString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultaSolicitudes))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoSolicitudProceso))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultaNoAbordo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoNoAbordoProceso))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultaEstadoCOEM))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoEstadoProceso))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public abstract partial class AbstractEntidadGenerica : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultaSolicitudes))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoSolicitudProceso))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultaNoAbordo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoNoAbordoProceso))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultaEstadoCOEM))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoEstadoProceso))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public abstract partial class AbstractEntidadOfString : AbstractEntidadGenerica {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ConsultaSolicitudes : AbstractEntidadOfString {
        
        private string identificadorCACEField;
        
        private string numeroSolicitudField;
        
        private string identificadorCOEMField;
        
        private string estadoField;
        
        private System.Nullable<System.DateTime> fechaEstadoField;
        
        private string tipoSolicitudField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentificadorCACE {
            get {
                return this.identificadorCACEField;
            }
            set {
                this.identificadorCACEField = value;
                this.RaisePropertyChanged("IdentificadorCACE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NumeroSolicitud {
            get {
                return this.numeroSolicitudField;
            }
            set {
                this.numeroSolicitudField = value;
                this.RaisePropertyChanged("NumeroSolicitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdentificadorCOEM {
            get {
                return this.identificadorCOEMField;
            }
            set {
                this.identificadorCOEMField = value;
                this.RaisePropertyChanged("IdentificadorCOEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> FechaEstado {
            get {
                return this.fechaEstadoField;
            }
            set {
                this.fechaEstadoField = value;
                this.RaisePropertyChanged("FechaEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TipoSolicitud {
            get {
                return this.tipoSolicitudField;
            }
            set {
                this.tipoSolicitudField = value;
                this.RaisePropertyChanged("TipoSolicitud");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ResultadoSolicitudProceso : AbstractEntidadOfString {
        
        private ConsultaSolicitudes[] listadoField;
        
        private string informacionAdicionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ConsultaSolicitudes[] Listado {
            get {
                return this.listadoField;
            }
            set {
                this.listadoField = value;
                this.RaisePropertyChanged("Listado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InformacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
                this.RaisePropertyChanged("InformacionAdicional");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ConsultaNoAbordo : AbstractEntidadOfString {
        
        private string identificadorCACEField;
        
        private string identificadorCOEMField;
        
        private string tipoField;
        
        private string contenedorField;
        
        private string destinacionField;
        
        private string cuitField;
        
        private System.Nullable<System.DateTime> fechaNoAbordoField;
        
        private string tipoNoAbordoField;
        
        private string motivoNoAbordoField;
        
        private string descripcionMotivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentificadorCACE {
            get {
                return this.identificadorCACEField;
            }
            set {
                this.identificadorCACEField = value;
                this.RaisePropertyChanged("IdentificadorCACE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdentificadorCOEM {
            get {
                return this.identificadorCOEMField;
            }
            set {
                this.identificadorCOEMField = value;
                this.RaisePropertyChanged("IdentificadorCOEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Contenedor {
            get {
                return this.contenedorField;
            }
            set {
                this.contenedorField = value;
                this.RaisePropertyChanged("Contenedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Destinacion {
            get {
                return this.destinacionField;
            }
            set {
                this.destinacionField = value;
                this.RaisePropertyChanged("Destinacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
                this.RaisePropertyChanged("Cuit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> FechaNoAbordo {
            get {
                return this.fechaNoAbordoField;
            }
            set {
                this.fechaNoAbordoField = value;
                this.RaisePropertyChanged("FechaNoAbordo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TipoNoAbordo {
            get {
                return this.tipoNoAbordoField;
            }
            set {
                this.tipoNoAbordoField = value;
                this.RaisePropertyChanged("TipoNoAbordo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MotivoNoAbordo {
            get {
                return this.motivoNoAbordoField;
            }
            set {
                this.motivoNoAbordoField = value;
                this.RaisePropertyChanged("MotivoNoAbordo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DescripcionMotivo {
            get {
                return this.descripcionMotivoField;
            }
            set {
                this.descripcionMotivoField = value;
                this.RaisePropertyChanged("DescripcionMotivo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ResultadoNoAbordoProceso : AbstractEntidadOfString {
        
        private ConsultaNoAbordo[] listadoField;
        
        private string informacionAdicionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ConsultaNoAbordo[] Listado {
            get {
                return this.listadoField;
            }
            set {
                this.listadoField = value;
                this.RaisePropertyChanged("Listado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InformacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
                this.RaisePropertyChanged("InformacionAdicional");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ConsultaEstadoCOEM : AbstractEntidadOfString {
        
        private string identificadorCOEMField;
        
        private string cuitAltaField;
        
        private string motivoField;
        
        private System.Nullable<System.DateTime> fechaEstadoField;
        
        private string estadoField;
        
        private string cODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentificadorCOEM {
            get {
                return this.identificadorCOEMField;
            }
            set {
                this.identificadorCOEMField = value;
                this.RaisePropertyChanged("IdentificadorCOEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CuitAlta {
            get {
                return this.cuitAltaField;
            }
            set {
                this.cuitAltaField = value;
                this.RaisePropertyChanged("CuitAlta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("Motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> FechaEstado {
            get {
                return this.fechaEstadoField;
            }
            set {
                this.fechaEstadoField = value;
                this.RaisePropertyChanged("FechaEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ResultadoEstadoProceso : AbstractEntidadOfString {
        
        private ConsultaEstadoCOEM[] listadoField;
        
        private string informacionAdicionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ConsultaEstadoCOEM[] Listado {
            get {
                return this.listadoField;
            }
            set {
                this.listadoField = value;
                this.RaisePropertyChanged("Listado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InformacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
                this.RaisePropertyChanged("InformacionAdicional");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class DummyTestConnectionInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool simularRespuestaConErroresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool SimularRespuestaConErrores {
            get {
                return this.simularRespuestaConErroresField;
            }
            set {
                this.simularRespuestaConErroresField = value;
                this.RaisePropertyChanged("SimularRespuestaConErrores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ResultadoEjecucionOfResultadoSolicitudProceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverField;
        
        private System.DateTime timeStampField;
        
        private ResultadoSolicitudProceso resultadoField;
        
        private ErrorEjecucion[] erroresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
                this.RaisePropertyChanged("Server");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ResultadoSolicitudProceso Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ErrorEjecucion[] Errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
                this.RaisePropertyChanged("Errores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ResultadoEjecucionOfResultadoNoAbordoProceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverField;
        
        private System.DateTime timeStampField;
        
        private ResultadoNoAbordoProceso resultadoField;
        
        private ErrorEjecucion[] erroresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
                this.RaisePropertyChanged("Server");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ResultadoNoAbordoProceso Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ErrorEjecucion[] Errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
                this.RaisePropertyChanged("Errores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class ResultadoEjecucionOfResultadoEstadoProceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverField;
        
        private System.DateTime timeStampField;
        
        private ResultadoEstadoProceso resultadoField;
        
        private ErrorEjecucion[] erroresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
                this.RaisePropertyChanged("Server");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ResultadoEstadoProceso Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ErrorEjecucion[] Errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
                this.RaisePropertyChanged("Errores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ar.Gob.Afip.Dga.wconscomunicacionembarque")]
    public partial class WSAutenticacionOrganismo : WSAutenticacion {
        
        private long cuitOrganismoField;
        
        private long cuitUsuarioConectadoField;
        
        private long cuitEmpresaConectadaField;
        
        private string tipoAgenteField;
        
        private string rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long CuitOrganismo {
            get {
                return this.cuitOrganismoField;
            }
            set {
                this.cuitOrganismoField = value;
                this.RaisePropertyChanged("CuitOrganismo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long CuitUsuarioConectado {
            get {
                return this.cuitUsuarioConectadoField;
            }
            set {
                this.cuitUsuarioConectadoField = value;
                this.RaisePropertyChanged("CuitUsuarioConectado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long CuitEmpresaConectada {
            get {
                return this.cuitEmpresaConectadaField;
            }
            set {
                this.cuitEmpresaConectadaField = value;
                this.RaisePropertyChanged("CuitEmpresaConectada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TipoAgente {
            get {
                return this.tipoAgenteField;
            }
            set {
                this.tipoAgenteField = value;
                this.RaisePropertyChanged("TipoAgente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("Rol");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wconscomunicacionembarqueSoapChannel : Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.wconscomunicacionembarqueSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wconscomunicacionembarqueSoapClient : System.ServiceModel.ClientBase<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.wconscomunicacionembarqueSoap>, Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.wconscomunicacionembarqueSoap {
        
        public wconscomunicacionembarqueSoapClient() {
        }
        
        public wconscomunicacionembarqueSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wconscomunicacionembarqueSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wconscomunicacionembarqueSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wconscomunicacionembarqueSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoEstadoProceso ObtenerConsultaEstadosCOEM(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera) {
            return base.Channel.ObtenerConsultaEstadosCOEM(argWSAutenticacionEmpresa, identificadorCabecera);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoEstadoProceso> ObtenerConsultaEstadosCOEMAsync(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera) {
            return base.Channel.ObtenerConsultaEstadosCOEMAsync(argWSAutenticacionEmpresa, identificadorCabecera);
        }
        
        public Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoNoAbordoProceso ObtenerConsultaNoAbordo(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera) {
            return base.Channel.ObtenerConsultaNoAbordo(argWSAutenticacionEmpresa, identificadorCabecera);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoNoAbordoProceso> ObtenerConsultaNoAbordoAsync(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera) {
            return base.Channel.ObtenerConsultaNoAbordoAsync(argWSAutenticacionEmpresa, identificadorCabecera);
        }
        
        public Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoSolicitudProceso ObtenerConsultaSolicitudes(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera) {
            return base.Channel.ObtenerConsultaSolicitudes(argWSAutenticacionEmpresa, identificadorCabecera);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfResultadoSolicitudProceso> ObtenerConsultaSolicitudesAsync(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa argWSAutenticacionEmpresa, string identificadorCabecera) {
            return base.Channel.ObtenerConsultaSolicitudesAsync(argWSAutenticacionEmpresa, identificadorCabecera);
        }
        
        public Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyTestConnectionOutput DummyTestConnection(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa wsAutenticacion, Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.DummyTestConnectionInput dummyTestConnectionInput) {
            return base.Channel.DummyTestConnection(wsAutenticacion, dummyTestConnectionInput);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyTestConnectionOutput> DummyTestConnectionAsync(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionEmpresa wsAutenticacion, Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.DummyTestConnectionInput dummyTestConnectionInput) {
            return base.Channel.DummyTestConnectionAsync(wsAutenticacion, dummyTestConnectionInput);
        }
        
        public Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyTestConnectionOutput DummyTestConnectionOrg(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionOrganismo wsAutenticacion, Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.DummyTestConnectionInput dummyTestConnectionInput) {
            return base.Channel.DummyTestConnectionOrg(wsAutenticacion, dummyTestConnectionInput);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyTestConnectionOutput> DummyTestConnectionOrgAsync(Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.WSAutenticacionOrganismo wsAutenticacion, Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.DummyTestConnectionInput dummyTestConnectionInput) {
            return base.Channel.DummyTestConnectionOrgAsync(wsAutenticacion, dummyTestConnectionInput);
        }
        
        public Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyOutput Dummy() {
            return base.Channel.Dummy();
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Servicios.AFIPServicioConsultaComunicacionEmbarque.ResultadoEjecucionOfDummyOutput> DummyAsync() {
            return base.Channel.DummyAsync();
        }
    }
}
