//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.Scato.Servicios.ComplianceWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webcompliance.com.ar/webservice/soap-graneles", ConfigurationName="ComplianceWebService.DatosPort")]
    public interface DatosPort {
        
        // CODEGEN: Generating message contract since the operation controlarDatosGraneles is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webcompliance.com.ar/webservice/soap-graneles#controlarDatosGraneles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesResponse controlarDatosGraneles(Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webcompliance.com.ar/webservice/soap-graneles#controlarDatosGraneles", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesResponse> controlarDatosGranelesAsync(Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.webcompliance.com.ar/webservice/soap-graneles")]
    public partial class Datos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cuitField;
        
        private string dniField;
        
        private string patente1Field;
        
        private string patente2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
                this.RaisePropertyChanged("cuit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string patente1 {
            get {
                return this.patente1Field;
            }
            set {
                this.patente1Field = value;
                this.RaisePropertyChanged("patente1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string patente2 {
            get {
                return this.patente2Field;
            }
            set {
                this.patente2Field = value;
                this.RaisePropertyChanged("patente2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.webcompliance.com.ar/webservice/soap-graneles")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string colorEmpresaField;
        
        private string codigoErrorField;
        
        private string nombreEmpresaField;
        
        private string colorChoferField;
        
        private string nombreChoferField;
        
        private string colorVehiculo1Field;
        
        private string codigoVehiculo1Field;
        
        private string colorVehiculo2Field;
        
        private string codigoVehiculo2Field;
        
        private string codigoCombinacionField;
        
        private string palletsField;
        
        private string avlChoferField;
        
        private string avlVehiculo1Field;
        
        private string avlVehiculo2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string colorEmpresa {
            get {
                return this.colorEmpresaField;
            }
            set {
                this.colorEmpresaField = value;
                this.RaisePropertyChanged("colorEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("codigoError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombreEmpresa {
            get {
                return this.nombreEmpresaField;
            }
            set {
                this.nombreEmpresaField = value;
                this.RaisePropertyChanged("nombreEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string colorChofer {
            get {
                return this.colorChoferField;
            }
            set {
                this.colorChoferField = value;
                this.RaisePropertyChanged("colorChofer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nombreChofer {
            get {
                return this.nombreChoferField;
            }
            set {
                this.nombreChoferField = value;
                this.RaisePropertyChanged("nombreChofer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string colorVehiculo1 {
            get {
                return this.colorVehiculo1Field;
            }
            set {
                this.colorVehiculo1Field = value;
                this.RaisePropertyChanged("colorVehiculo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string codigoVehiculo1 {
            get {
                return this.codigoVehiculo1Field;
            }
            set {
                this.codigoVehiculo1Field = value;
                this.RaisePropertyChanged("codigoVehiculo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string colorVehiculo2 {
            get {
                return this.colorVehiculo2Field;
            }
            set {
                this.colorVehiculo2Field = value;
                this.RaisePropertyChanged("colorVehiculo2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string codigoVehiculo2 {
            get {
                return this.codigoVehiculo2Field;
            }
            set {
                this.codigoVehiculo2Field = value;
                this.RaisePropertyChanged("codigoVehiculo2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string codigoCombinacion {
            get {
                return this.codigoCombinacionField;
            }
            set {
                this.codigoCombinacionField = value;
                this.RaisePropertyChanged("codigoCombinacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string pallets {
            get {
                return this.palletsField;
            }
            set {
                this.palletsField = value;
                this.RaisePropertyChanged("pallets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string avlChofer {
            get {
                return this.avlChoferField;
            }
            set {
                this.avlChoferField = value;
                this.RaisePropertyChanged("avlChofer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string avlVehiculo1 {
            get {
                return this.avlVehiculo1Field;
            }
            set {
                this.avlVehiculo1Field = value;
                this.RaisePropertyChanged("avlVehiculo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string avlVehiculo2 {
            get {
                return this.avlVehiculo2Field;
            }
            set {
                this.avlVehiculo2Field = value;
                this.RaisePropertyChanged("avlVehiculo2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class controlarDatosGranelesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webcompliance.com.ar/webservice/soap-graneles", Order=0)]
        public Molinos.Scato.Servicios.ComplianceWebService.Datos Datos;
        
        public controlarDatosGranelesRequest() {
        }
        
        public controlarDatosGranelesRequest(Molinos.Scato.Servicios.ComplianceWebService.Datos Datos) {
            this.Datos = Datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class controlarDatosGranelesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webcompliance.com.ar/webservice/soap-graneles", Order=0)]
        public Molinos.Scato.Servicios.ComplianceWebService.Response Response;
        
        public controlarDatosGranelesResponse() {
        }
        
        public controlarDatosGranelesResponse(Molinos.Scato.Servicios.ComplianceWebService.Response Response) {
            this.Response = Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatosPortChannel : Molinos.Scato.Servicios.ComplianceWebService.DatosPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatosPortClient : System.ServiceModel.ClientBase<Molinos.Scato.Servicios.ComplianceWebService.DatosPort>, Molinos.Scato.Servicios.ComplianceWebService.DatosPort {
        
        public DatosPortClient() {
        }
        
        public DatosPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatosPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatosPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatosPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesResponse Molinos.Scato.Servicios.ComplianceWebService.DatosPort.controlarDatosGraneles(Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesRequest request) {
            return base.Channel.controlarDatosGraneles(request);
        }
        
        public Molinos.Scato.Servicios.ComplianceWebService.Response controlarDatosGraneles(Molinos.Scato.Servicios.ComplianceWebService.Datos Datos) {
            Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesRequest inValue = new Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesRequest();
            inValue.Datos = Datos;
            Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesResponse retVal = ((Molinos.Scato.Servicios.ComplianceWebService.DatosPort)(this)).controlarDatosGraneles(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesResponse> Molinos.Scato.Servicios.ComplianceWebService.DatosPort.controlarDatosGranelesAsync(Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesRequest request) {
            return base.Channel.controlarDatosGranelesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesResponse> controlarDatosGranelesAsync(Molinos.Scato.Servicios.ComplianceWebService.Datos Datos) {
            Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesRequest inValue = new Molinos.Scato.Servicios.ComplianceWebService.controlarDatosGranelesRequest();
            inValue.Datos = Datos;
            return ((Molinos.Scato.Servicios.ComplianceWebService.DatosPort)(this)).controlarDatosGranelesAsync(inValue);
        }
    }
}
