//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.Scato.WfEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Molinos.Scato.WfEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir última versión.
        /// </summary>
        public static string AbrirUltimaVersion {
            get {
                return ResourceManager.GetString("AbrirUltimaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Versión.
        /// </summary>
        public static string AbrirVersion {
            get {
                return ResourceManager.GetString("AbrirVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar.
        /// </summary>
        public static string Activar {
            get {
                return ResourceManager.GetString("Activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al activar la versión comenzará a utilizarse para las nuevas ejecuciones del workflow. Una vez activada ya no podrá ser modificada.
        ///¿Desea continuar y activar la versión?.
        /// </summary>
        public static string ActivarMensaje {
            get {
                return ResourceManager.GetString("ActivarMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea activar el workflow &apos;{0}&apos;?.
        /// </summary>
        public static string ActivarWorkflowMensaje {
            get {
                return ResourceManager.GetString("ActivarWorkflowMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar Workflow.
        /// </summary>
        public static string ActivarWorkflowTitulo {
            get {
                return ResourceManager.GetString("ActivarWorkflowTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades.
        /// </summary>
        public static string CategoriaActividades {
            get {
                return ResourceManager.GetString("CategoriaActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de Flujo.
        /// </summary>
        public static string CategoriaControlDeFlujo {
            get {
                return ResourceManager.GetString("CategoriaControlDeFlujo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        public static string DefinicionActiva {
            get {
                return ResourceManager.GetString("DefinicionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string DefinicionComentario {
            get {
                return ResourceManager.GetString("DefinicionComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Creación.
        /// </summary>
        public static string DefinicionFechaCreacion {
            get {
                return ResourceManager.GetString("DefinicionFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creada Por.
        /// </summary>
        public static string DefinicionNombreUsuario {
            get {
                return ResourceManager.GetString("DefinicionNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar.
        /// </summary>
        public static string Desactivar {
            get {
                return ResourceManager.GetString("Desactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea desactivar el workflow &apos;{0}&apos;?.
        /// </summary>
        public static string DesactivarWorkflowMensaje {
            get {
                return ResourceManager.GetString("DesactivarWorkflowMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesactivarWorkflow.
        /// </summary>
        public static string DesactivarWorkflowTitulo {
            get {
                return ResourceManager.GetString("DesactivarWorkflowTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es requerido.
        /// </summary>
        public static string Error_Requerido {
            get {
                return ResourceManager.GetString("Error_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un workflow con el código {0}.
        /// </summary>
        public static string Error_WorkflowCodigoExistente {
            get {
                return ResourceManager.GetString("Error_WorkflowCodigoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error en la aplicación ({0}). Por favor contáctese con el soporte..
        /// </summary>
        public static string ErrorGenerico {
            get {
                return ResourceManager.GetString("ErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ErrorId {
            get {
                return ResourceManager.GetString("ErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string ErrorMensaje {
            get {
                return ResourceManager.GetString("ErrorMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permiso para acceder al Editor de Workflow.
        /// </summary>
        public static string ErrorPermiso {
            get {
                return ResourceManager.GetString("ErrorPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string ErrorTipo {
            get {
                return ResourceManager.GetString("ErrorTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparado.
        /// </summary>
        public static string EstadoPreparado {
            get {
                return ResourceManager.GetString("EstadoPreparado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea guardar los cambios en el workflow abierto?.
        /// </summary>
        public static string GuardarCambiosMensaje {
            get {
                return ResourceManager.GetString("GuardarCambiosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Cambios.
        /// </summary>
        public static string GuardarCambiosTitulo {
            get {
                return ResourceManager.GetString("GuardarCambiosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Como.
        /// </summary>
        public static string GuardarComo {
            get {
                return ResourceManager.GetString("GuardarComo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de la nueva versión.
        /// </summary>
        public static string GuardarComoDatosVersion {
            get {
                return ResourceManager.GetString("GuardarComoDatosVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar versión.
        /// </summary>
        public static string GuardarComoDefinicionActiva {
            get {
                return ResourceManager.GetString("GuardarComoDefinicionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string GuardarComoDefinicionComentarios {
            get {
                return ResourceManager.GetString("GuardarComoDefinicionComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string GuardarComoWorkflow {
            get {
                return ResourceManager.GetString("GuardarComoWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Inicial.
        /// </summary>
        public static string GuardarComoWorkflowActividadInicial {
            get {
                return ResourceManager.GetString("GuardarComoWorkflowActividadInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string GuardarComoWorkflowActivo {
            get {
                return ResourceManager.GetString("GuardarComoWorkflowActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro.
        /// </summary>
        public static string GuardarComoWorkflowCentro {
            get {
                return ResourceManager.GetString("GuardarComoWorkflowCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string GuardarComoWorkflowCodigo {
            get {
                return ResourceManager.GetString("GuardarComoWorkflowCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del nuevo workflow.
        /// </summary>
        public static string GuardarComoWorkflowDatos {
            get {
                return ResourceManager.GetString("GuardarComoWorkflowDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string GuardarComoWorkflowDescripcion {
            get {
                return ResourceManager.GetString("GuardarComoWorkflowDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Existente.
        /// </summary>
        public static string GuardarComoWorkflowExistente {
            get {
                return ResourceManager.GetString("GuardarComoWorkflowExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Workflow.
        /// </summary>
        public static string GuardarComoWorkflowNuevo {
            get {
                return ResourceManager.GetString("GuardarComoWorkflowNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string GuardarComoWorkflowTipo {
            get {
                return ResourceManager.GetString("GuardarComoWorkflowTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ItemvalidacionError {
            get {
                return ResourceManager.GetString("ItemvalidacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ItemValidacionWarning {
            get {
                return ResourceManager.GetString("ItemValidacionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar verificar las credenciales. Verifique la conexión a la red..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique los datos ingresados.
        /// </summary>
        public static string LoginVerifiqueDatos {
            get {
                return ResourceManager.GetString("LoginVerifiqueDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string MenuArchivo {
            get {
                return ResourceManager.GetString("MenuArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir....
        /// </summary>
        public static string MenuArchivoAbrir {
            get {
                return ResourceManager.GetString("MenuArchivoAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activación de Workflows....
        /// </summary>
        public static string MenuArchivoActivarDesactivar {
            get {
                return ResourceManager.GetString("MenuArchivoActivarDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string MenuArchivoCerrar {
            get {
                return ResourceManager.GetString("MenuArchivoCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string MenuArchivoGuardar {
            get {
                return ResourceManager.GetString("MenuArchivoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y Activar.
        /// </summary>
        public static string MenuArchivoGuardarActivar {
            get {
                return ResourceManager.GetString("MenuArchivoGuardarActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Como....
        /// </summary>
        public static string MenuArchivoGuardarComo {
            get {
                return ResourceManager.GetString("MenuArchivoGuardarComo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo....
        /// </summary>
        public static string MenuArchivoNuevo {
            get {
                return ResourceManager.GetString("MenuArchivoNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string MenuArchivoSalir {
            get {
                return ResourceManager.GetString("MenuArchivoSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar verificar sus permisos. Verifique la conexión a la red..
        /// </summary>
        public static string PermisosError {
            get {
                return ResourceManager.GetString("PermisosError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Workflow.
        /// </summary>
        public static string TituloAbrirWorkflow {
            get {
                return ResourceManager.GetString("TituloAbrirWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activación de Workflows.
        /// </summary>
        public static string TituloActivarDesactivar {
            get {
                return ResourceManager.GetString("TituloActivarDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCATO - Editor de Workflows.
        /// </summary>
        public static string TituloEditorWorkflows {
            get {
                return ResourceManager.GetString("TituloEditorWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Workflow.
        /// </summary>
        public static string TituloGuardarWorkflow {
            get {
                return ResourceManager.GetString("TituloGuardarWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versiones del workflow seleccionado:.
        /// </summary>
        public static string VersionesWorkflow {
            get {
                return ResourceManager.GetString("VersionesWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver versiones anteriores.
        /// </summary>
        public static string VerVersionesAnteriores {
            get {
                return ResourceManager.GetString("VerVersionesAnteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Inicial.
        /// </summary>
        public static string WorkflowActividadInicial {
            get {
                return ResourceManager.GetString("WorkflowActividadInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string WorkflowActivo {
            get {
                return ResourceManager.GetString("WorkflowActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string WorkflowCodigo {
            get {
                return ResourceManager.GetString("WorkflowCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string WorkflowDescripcion {
            get {
                return ResourceManager.GetString("WorkflowDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Activación.
        /// </summary>
        public static string WorkflowFechaActivacion {
            get {
                return ResourceManager.GetString("WorkflowFechaActivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El workflow se guardó exitosamente.
        /// </summary>
        public static string WorkflowGuardado {
            get {
                return ResourceManager.GetString("WorkflowGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Workflow.
        /// </summary>
        public static string WorkflowNuevo {
            get {
                return ResourceManager.GetString("WorkflowNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows disponibles:.
        /// </summary>
        public static string WorkflowsDisponibles {
            get {
                return ResourceManager.GetString("WorkflowsDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string WorkflowTipo {
            get {
                return ResourceManager.GetString("WorkflowTipo", resourceCulture);
            }
        }
    }
}
