//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.Scato.Test.AnalisisDeCalidad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scato.molinos.com/", ConfigurationName="AnalisisDeCalidad.IAutorizarTransportistaInhabilitadoService")]
    public interface IAutorizarTransportistaInhabilitadoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IAutorizarTransportistaInhabilitadoService/AutorizarTran" +
            "sportistaInhabilitado", ReplyAction="http://scato.molinos.com/IAutorizarTransportistaInhabilitadoService/AutorizarTran" +
            "sportistaInhabilitadoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        bool AutorizarTransportistaInhabilitado(System.Guid instanceId, bool autorizado, bool terminaInhabilitacion, Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorridoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IAutorizarTransportistaInhabilitadoService/AutorizarTran" +
            "sportistaInhabilitado", ReplyAction="http://scato.molinos.com/IAutorizarTransportistaInhabilitadoService/AutorizarTran" +
            "sportistaInhabilitadoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<bool> AutorizarTransportistaInhabilitadoAsync(System.Guid instanceId, bool autorizado, bool terminaInhabilitacion, Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorridoDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutorizarTransportistaInhabilitadoServiceChannel : Molinos.Scato.Test.AnalisisDeCalidad.IAutorizarTransportistaInhabilitadoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutorizarTransportistaInhabilitadoServiceClient : System.ServiceModel.ClientBase<Molinos.Scato.Test.AnalisisDeCalidad.IAutorizarTransportistaInhabilitadoService>, Molinos.Scato.Test.AnalisisDeCalidad.IAutorizarTransportistaInhabilitadoService {
        
        public AutorizarTransportistaInhabilitadoServiceClient() {
        }
        
        public AutorizarTransportistaInhabilitadoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutorizarTransportistaInhabilitadoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutorizarTransportistaInhabilitadoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutorizarTransportistaInhabilitadoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AutorizarTransportistaInhabilitado(System.Guid instanceId, bool autorizado, bool terminaInhabilitacion, Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorridoDto) {
            return base.Channel.AutorizarTransportistaInhabilitado(instanceId, autorizado, terminaInhabilitacion, controlRecorridoDto);
        }
        
        public System.Threading.Tasks.Task<bool> AutorizarTransportistaInhabilitadoAsync(System.Guid instanceId, bool autorizado, bool terminaInhabilitacion, Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorridoDto) {
            return base.Channel.AutorizarTransportistaInhabilitadoAsync(instanceId, autorizado, terminaInhabilitacion, controlRecorridoDto);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scato.molinos.com/", ConfigurationName="AnalisisDeCalidad.ISalidaDeCentroService")]
    public interface ISalidaDeCentroService {
        
        // CODEGEN: Generating message contract since the operation SalidaDeCentro is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/ISalidaDeCentroService/SalidaDeCentro", ReplyAction="http://scato.molinos.com/ISalidaDeCentroService/SalidaDeCentroResponse")]
        Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroResponse SalidaDeCentro(Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/ISalidaDeCentroService/SalidaDeCentro", ReplyAction="http://scato.molinos.com/ISalidaDeCentroService/SalidaDeCentroResponse")]
        System.Threading.Tasks.Task<Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroResponse> SalidaDeCentroAsync(Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalidaDeCentro", WrapperNamespace="http://scato.molinos.com/", IsWrapped=true)]
    public partial class SalidaDeCentroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=0)]
        public System.Guid instanceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=1)]
        public Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorridoDto;
        
        public SalidaDeCentroRequest() {
        }
        
        public SalidaDeCentroRequest(System.Guid instanceId, Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorridoDto) {
            this.instanceId = instanceId;
            this.controlRecorridoDto = controlRecorridoDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalidaDeCentroResponse {
        
        public SalidaDeCentroResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalidaDeCentroServiceChannel : Molinos.Scato.Test.AnalisisDeCalidad.ISalidaDeCentroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalidaDeCentroServiceClient : System.ServiceModel.ClientBase<Molinos.Scato.Test.AnalisisDeCalidad.ISalidaDeCentroService>, Molinos.Scato.Test.AnalisisDeCalidad.ISalidaDeCentroService {
        
        public SalidaDeCentroServiceClient() {
        }
        
        public SalidaDeCentroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalidaDeCentroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalidaDeCentroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalidaDeCentroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroResponse Molinos.Scato.Test.AnalisisDeCalidad.ISalidaDeCentroService.SalidaDeCentro(Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroRequest request) {
            return base.Channel.SalidaDeCentro(request);
        }
        
        public void SalidaDeCentro(System.Guid instanceId, Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorridoDto) {
            Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroRequest inValue = new Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroRequest();
            inValue.instanceId = instanceId;
            inValue.controlRecorridoDto = controlRecorridoDto;
            Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroResponse retVal = ((Molinos.Scato.Test.AnalisisDeCalidad.ISalidaDeCentroService)(this)).SalidaDeCentro(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroResponse> Molinos.Scato.Test.AnalisisDeCalidad.ISalidaDeCentroService.SalidaDeCentroAsync(Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroRequest request) {
            return base.Channel.SalidaDeCentroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroResponse> SalidaDeCentroAsync(System.Guid instanceId, Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorridoDto) {
            Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroRequest inValue = new Molinos.Scato.Test.AnalisisDeCalidad.SalidaDeCentroRequest();
            inValue.instanceId = instanceId;
            inValue.controlRecorridoDto = controlRecorridoDto;
            return ((Molinos.Scato.Test.AnalisisDeCalidad.ISalidaDeCentroService)(this)).SalidaDeCentroAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scato.molinos.com/", ConfigurationName="AnalisisDeCalidad.IIngresarOrdenCargaInternaService")]
    public interface IIngresarOrdenCargaInternaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IIngresarOrdenCargaInternaService/IngresarOrdenCargaInte" +
            "rna", ReplyAction="http://scato.molinos.com/IIngresarOrdenCargaInternaService/IngresarOrdenCargaInte" +
            "rnaResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Molinos.Scato.Dominio.Comandos.ResultadoCrear))]
        Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaResponse IngresarOrdenCargaInterna(Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IIngresarOrdenCargaInternaService/IngresarOrdenCargaInte" +
            "rna", ReplyAction="http://scato.molinos.com/IIngresarOrdenCargaInternaService/IngresarOrdenCargaInte" +
            "rnaResponse")]
        System.Threading.Tasks.Task<Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaResponse> IngresarOrdenCargaInternaAsync(Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresarOrdenCargaInterna", WrapperNamespace="http://scato.molinos.com/", IsWrapped=true)]
    public partial class IngresarOrdenCargaInternaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=0)]
        public Molinos.Scato.Dominio.Dto.OrdenCargaInternaDto orden;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=1)]
        public int centroId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=2)]
        public string nombreWorkflow;
        
        public IngresarOrdenCargaInternaRequest() {
        }
        
        public IngresarOrdenCargaInternaRequest(Molinos.Scato.Dominio.Dto.OrdenCargaInternaDto orden, int centroId, string nombreWorkflow) {
            this.orden = orden;
            this.centroId = centroId;
            this.nombreWorkflow = nombreWorkflow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresarOrdenCargaInternaResponse", WrapperNamespace="http://scato.molinos.com/", IsWrapped=true)]
    public partial class IngresarOrdenCargaInternaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=0)]
        public Molinos.Scato.Dominio.Comandos.Resultado resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=1)]
        public System.Guid instanceId;
        
        public IngresarOrdenCargaInternaResponse() {
        }
        
        public IngresarOrdenCargaInternaResponse(Molinos.Scato.Dominio.Comandos.Resultado resultado, System.Guid instanceId) {
            this.resultado = resultado;
            this.instanceId = instanceId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIngresarOrdenCargaInternaServiceChannel : Molinos.Scato.Test.AnalisisDeCalidad.IIngresarOrdenCargaInternaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IngresarOrdenCargaInternaServiceClient : System.ServiceModel.ClientBase<Molinos.Scato.Test.AnalisisDeCalidad.IIngresarOrdenCargaInternaService>, Molinos.Scato.Test.AnalisisDeCalidad.IIngresarOrdenCargaInternaService {
        
        public IngresarOrdenCargaInternaServiceClient() {
        }
        
        public IngresarOrdenCargaInternaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IngresarOrdenCargaInternaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngresarOrdenCargaInternaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngresarOrdenCargaInternaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaResponse Molinos.Scato.Test.AnalisisDeCalidad.IIngresarOrdenCargaInternaService.IngresarOrdenCargaInterna(Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaRequest request) {
            return base.Channel.IngresarOrdenCargaInterna(request);
        }
        
        public Molinos.Scato.Dominio.Comandos.Resultado IngresarOrdenCargaInterna(Molinos.Scato.Dominio.Dto.OrdenCargaInternaDto orden, int centroId, string nombreWorkflow, out System.Guid instanceId) {
            Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaRequest inValue = new Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaRequest();
            inValue.orden = orden;
            inValue.centroId = centroId;
            inValue.nombreWorkflow = nombreWorkflow;
            Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaResponse retVal = ((Molinos.Scato.Test.AnalisisDeCalidad.IIngresarOrdenCargaInternaService)(this)).IngresarOrdenCargaInterna(inValue);
            instanceId = retVal.instanceId;
            return retVal.resultado;
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaResponse> IngresarOrdenCargaInternaAsync(Molinos.Scato.Test.AnalisisDeCalidad.IngresarOrdenCargaInternaRequest request) {
            return base.Channel.IngresarOrdenCargaInternaAsync(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scato.molinos.com/", ConfigurationName="AnalisisDeCalidad.IPesadaService")]
    public interface IPesadaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IPesadaService/Pesada", ReplyAction="http://scato.molinos.com/IPesadaService/PesadaResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Molinos.Scato.Dominio.Comandos.ResultadoCrear))]
        Molinos.Scato.Test.AnalisisDeCalidad.PesadaResponse Pesada(Molinos.Scato.Test.AnalisisDeCalidad.PesadaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IPesadaService/Pesada", ReplyAction="http://scato.molinos.com/IPesadaService/PesadaResponse")]
        System.Threading.Tasks.Task<Molinos.Scato.Test.AnalisisDeCalidad.PesadaResponse> PesadaAsync(Molinos.Scato.Test.AnalisisDeCalidad.PesadaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pesada", WrapperNamespace="http://scato.molinos.com/", IsWrapped=true)]
    public partial class PesadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=0)]
        public System.Guid instanceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=1)]
        public int peso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=2)]
        public int almacenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=3)]
        public System.Nullable<int> hidraulicaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=4)]
        public System.Nullable<int> calleId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=5)]
        public int balanzaId;
        
        public PesadaRequest() {
        }
        
        public PesadaRequest(System.Guid instanceId, int peso, int almacenId, System.Nullable<int> hidraulicaId, System.Nullable<int> calleId, int balanzaId) {
            this.instanceId = instanceId;
            this.peso = peso;
            this.almacenId = almacenId;
            this.hidraulicaId = hidraulicaId;
            this.calleId = calleId;
            this.balanzaId = balanzaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PesadaResponse", WrapperNamespace="http://scato.molinos.com/", IsWrapped=true)]
    public partial class PesadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=0)]
        public Molinos.Scato.Dominio.Comandos.Resultado resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scato.molinos.com/", Order=1)]
        public int peso;
        
        public PesadaResponse() {
        }
        
        public PesadaResponse(Molinos.Scato.Dominio.Comandos.Resultado resultado, int peso) {
            this.resultado = resultado;
            this.peso = peso;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPesadaServiceChannel : Molinos.Scato.Test.AnalisisDeCalidad.IPesadaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PesadaServiceClient : System.ServiceModel.ClientBase<Molinos.Scato.Test.AnalisisDeCalidad.IPesadaService>, Molinos.Scato.Test.AnalisisDeCalidad.IPesadaService {
        
        public PesadaServiceClient() {
        }
        
        public PesadaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PesadaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PesadaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PesadaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.Scato.Test.AnalisisDeCalidad.PesadaResponse Molinos.Scato.Test.AnalisisDeCalidad.IPesadaService.Pesada(Molinos.Scato.Test.AnalisisDeCalidad.PesadaRequest request) {
            return base.Channel.Pesada(request);
        }
        
        public Molinos.Scato.Dominio.Comandos.Resultado Pesada(System.Guid instanceId, ref int peso, int almacenId, System.Nullable<int> hidraulicaId, System.Nullable<int> calleId, int balanzaId) {
            Molinos.Scato.Test.AnalisisDeCalidad.PesadaRequest inValue = new Molinos.Scato.Test.AnalisisDeCalidad.PesadaRequest();
            inValue.instanceId = instanceId;
            inValue.peso = peso;
            inValue.almacenId = almacenId;
            inValue.hidraulicaId = hidraulicaId;
            inValue.calleId = calleId;
            inValue.balanzaId = balanzaId;
            Molinos.Scato.Test.AnalisisDeCalidad.PesadaResponse retVal = ((Molinos.Scato.Test.AnalisisDeCalidad.IPesadaService)(this)).Pesada(inValue);
            peso = retVal.peso;
            return retVal.resultado;
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Test.AnalisisDeCalidad.PesadaResponse> PesadaAsync(Molinos.Scato.Test.AnalisisDeCalidad.PesadaRequest request) {
            return base.Channel.PesadaAsync(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scato.molinos.com/", ConfigurationName="AnalisisDeCalidad.ICargarPrecintosService")]
    public interface ICargarPrecintosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/ICargarPrecintosService/CargarPrecintos", ReplyAction="http://scato.molinos.com/ICargarPrecintosService/CargarPrecintosResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Molinos.Scato.Dominio.Comandos.ResultadoCrear))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        Molinos.Scato.Dominio.Comandos.Resultado CargarPrecintos(Molinos.Scato.Dominio.Dto.PrecintoDto[] listaPrecintos, System.Guid instanceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/ICargarPrecintosService/CargarPrecintos", ReplyAction="http://scato.molinos.com/ICargarPrecintosService/CargarPrecintosResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> CargarPrecintosAsync(Molinos.Scato.Dominio.Dto.PrecintoDto[] listaPrecintos, System.Guid instanceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICargarPrecintosServiceChannel : Molinos.Scato.Test.AnalisisDeCalidad.ICargarPrecintosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CargarPrecintosServiceClient : System.ServiceModel.ClientBase<Molinos.Scato.Test.AnalisisDeCalidad.ICargarPrecintosService>, Molinos.Scato.Test.AnalisisDeCalidad.ICargarPrecintosService {
        
        public CargarPrecintosServiceClient() {
        }
        
        public CargarPrecintosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CargarPrecintosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargarPrecintosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargarPrecintosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Molinos.Scato.Dominio.Comandos.Resultado CargarPrecintos(Molinos.Scato.Dominio.Dto.PrecintoDto[] listaPrecintos, System.Guid instanceId) {
            return base.Channel.CargarPrecintos(listaPrecintos, instanceId);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> CargarPrecintosAsync(Molinos.Scato.Dominio.Dto.PrecintoDto[] listaPrecintos, System.Guid instanceId) {
            return base.Channel.CargarPrecintosAsync(listaPrecintos, instanceId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scato.molinos.com/", ConfigurationName="AnalisisDeCalidad.IIngresoDeObservacionesService")]
    public interface IIngresoDeObservacionesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IIngresoDeObservacionesService/IngresoDeObservaciones", ReplyAction="http://scato.molinos.com/IIngresoDeObservacionesService/IngresoDeObservacionesRes" +
            "ponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Molinos.Scato.Dominio.Comandos.ResultadoCrear))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        Molinos.Scato.Dominio.Comandos.Resultado IngresoDeObservaciones(Molinos.Scato.Dominio.Dto.ObservacionDto observacion, System.Guid instanceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IIngresoDeObservacionesService/IngresoDeObservaciones", ReplyAction="http://scato.molinos.com/IIngresoDeObservacionesService/IngresoDeObservacionesRes" +
            "ponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> IngresoDeObservacionesAsync(Molinos.Scato.Dominio.Dto.ObservacionDto observacion, System.Guid instanceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIngresoDeObservacionesServiceChannel : Molinos.Scato.Test.AnalisisDeCalidad.IIngresoDeObservacionesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IngresoDeObservacionesServiceClient : System.ServiceModel.ClientBase<Molinos.Scato.Test.AnalisisDeCalidad.IIngresoDeObservacionesService>, Molinos.Scato.Test.AnalisisDeCalidad.IIngresoDeObservacionesService {
        
        public IngresoDeObservacionesServiceClient() {
        }
        
        public IngresoDeObservacionesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IngresoDeObservacionesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngresoDeObservacionesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngresoDeObservacionesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Molinos.Scato.Dominio.Comandos.Resultado IngresoDeObservaciones(Molinos.Scato.Dominio.Dto.ObservacionDto observacion, System.Guid instanceId) {
            return base.Channel.IngresoDeObservaciones(observacion, instanceId);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> IngresoDeObservacionesAsync(Molinos.Scato.Dominio.Dto.ObservacionDto observacion, System.Guid instanceId) {
            return base.Channel.IngresoDeObservacionesAsync(observacion, instanceId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scato.molinos.com/", ConfigurationName="AnalisisDeCalidad.IControlDePesoEsperadoService")]
    public interface IControlDePesoEsperadoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IControlDePesoEsperadoService/ControlDePesoEsperado", ReplyAction="http://scato.molinos.com/IControlDePesoEsperadoService/ControlDePesoEsperadoRespo" +
            "nse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Molinos.Scato.Dominio.Comandos.ResultadoCrear))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        Molinos.Scato.Dominio.Comandos.Resultado ControlDePesoEsperado(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IControlDePesoEsperadoService/ControlDePesoEsperado", ReplyAction="http://scato.molinos.com/IControlDePesoEsperadoService/ControlDePesoEsperadoRespo" +
            "nse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> ControlDePesoEsperadoAsync(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlDePesoEsperadoServiceChannel : Molinos.Scato.Test.AnalisisDeCalidad.IControlDePesoEsperadoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlDePesoEsperadoServiceClient : System.ServiceModel.ClientBase<Molinos.Scato.Test.AnalisisDeCalidad.IControlDePesoEsperadoService>, Molinos.Scato.Test.AnalisisDeCalidad.IControlDePesoEsperadoService {
        
        public ControlDePesoEsperadoServiceClient() {
        }
        
        public ControlDePesoEsperadoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlDePesoEsperadoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlDePesoEsperadoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlDePesoEsperadoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Molinos.Scato.Dominio.Comandos.Resultado ControlDePesoEsperado(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId) {
            return base.Channel.ControlDePesoEsperado(controlRecorrido, instanceId);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> ControlDePesoEsperadoAsync(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId) {
            return base.Channel.ControlDePesoEsperadoAsync(controlRecorrido, instanceId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scato.molinos.com/", ConfigurationName="AnalisisDeCalidad.IVerificacionCamionRechazadoService")]
    public interface IVerificacionCamionRechazadoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IVerificacionCamionRechazadoService/VerificacionCamionRe" +
            "chazado", ReplyAction="http://scato.molinos.com/IVerificacionCamionRechazadoService/VerificacionCamionRe" +
            "chazadoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Molinos.Scato.Dominio.Comandos.ResultadoCrear))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        Molinos.Scato.Dominio.Comandos.Resultado VerificacionCamionRechazado(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IVerificacionCamionRechazadoService/VerificacionCamionRe" +
            "chazado", ReplyAction="http://scato.molinos.com/IVerificacionCamionRechazadoService/VerificacionCamionRe" +
            "chazadoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> VerificacionCamionRechazadoAsync(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVerificacionCamionRechazadoServiceChannel : Molinos.Scato.Test.AnalisisDeCalidad.IVerificacionCamionRechazadoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerificacionCamionRechazadoServiceClient : System.ServiceModel.ClientBase<Molinos.Scato.Test.AnalisisDeCalidad.IVerificacionCamionRechazadoService>, Molinos.Scato.Test.AnalisisDeCalidad.IVerificacionCamionRechazadoService {
        
        public VerificacionCamionRechazadoServiceClient() {
        }
        
        public VerificacionCamionRechazadoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerificacionCamionRechazadoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificacionCamionRechazadoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificacionCamionRechazadoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Molinos.Scato.Dominio.Comandos.Resultado VerificacionCamionRechazado(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId) {
            return base.Channel.VerificacionCamionRechazado(controlRecorrido, instanceId);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> VerificacionCamionRechazadoAsync(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId) {
            return base.Channel.VerificacionCamionRechazadoAsync(controlRecorrido, instanceId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scato.molinos.com/", ConfigurationName="AnalisisDeCalidad.IControlPesoMaximoService")]
    public interface IControlPesoMaximoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IControlPesoMaximoService/ControlPesoMaximo", ReplyAction="http://scato.molinos.com/IControlPesoMaximoService/ControlPesoMaximoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Molinos.Scato.Dominio.Comandos.ResultadoCrear))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        Molinos.Scato.Dominio.Comandos.Resultado ControlPesoMaximo(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scato.molinos.com/IControlPesoMaximoService/ControlPesoMaximo", ReplyAction="http://scato.molinos.com/IControlPesoMaximoService/ControlPesoMaximoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> ControlPesoMaximoAsync(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlPesoMaximoServiceChannel : Molinos.Scato.Test.AnalisisDeCalidad.IControlPesoMaximoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlPesoMaximoServiceClient : System.ServiceModel.ClientBase<Molinos.Scato.Test.AnalisisDeCalidad.IControlPesoMaximoService>, Molinos.Scato.Test.AnalisisDeCalidad.IControlPesoMaximoService {
        
        public ControlPesoMaximoServiceClient() {
        }
        
        public ControlPesoMaximoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlPesoMaximoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlPesoMaximoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlPesoMaximoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Molinos.Scato.Dominio.Comandos.Resultado ControlPesoMaximo(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId) {
            return base.Channel.ControlPesoMaximo(controlRecorrido, instanceId);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> ControlPesoMaximoAsync(Molinos.Scato.Dominio.Dto.ControlRecorridoDto controlRecorrido, System.Guid instanceId) {
            return base.Channel.ControlPesoMaximoAsync(controlRecorrido, instanceId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnalisisDeCalidad.IAnalisisDeCalidadService")]
    public interface IAnalisisDeCalidadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalisisDeCalidadService/AnalisisDeCalidad", ReplyAction="http://tempuri.org/IAnalisisDeCalidadService/AnalisisDeCalidadResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Molinos.Scato.Dominio.Comandos.ResultadoCrear))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        Molinos.Scato.Dominio.Comandos.Resultado AnalisisDeCalidad(System.Guid instanceId, string numeroDeOrden, Molinos.Scato.Dominio.Dto.AnalisisPorCaracteristicaDto[] caracteristicasAnalizadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalisisDeCalidadService/AnalisisDeCalidad", ReplyAction="http://tempuri.org/IAnalisisDeCalidadService/AnalisisDeCalidadResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> AnalisisDeCalidadAsync(System.Guid instanceId, string numeroDeOrden, Molinos.Scato.Dominio.Dto.AnalisisPorCaracteristicaDto[] caracteristicasAnalizadas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnalisisDeCalidadServiceChannel : Molinos.Scato.Test.AnalisisDeCalidad.IAnalisisDeCalidadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnalisisDeCalidadServiceClient : System.ServiceModel.ClientBase<Molinos.Scato.Test.AnalisisDeCalidad.IAnalisisDeCalidadService>, Molinos.Scato.Test.AnalisisDeCalidad.IAnalisisDeCalidadService {
        
        public AnalisisDeCalidadServiceClient() {
        }
        
        public AnalisisDeCalidadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnalisisDeCalidadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalisisDeCalidadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalisisDeCalidadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Molinos.Scato.Dominio.Comandos.Resultado AnalisisDeCalidad(System.Guid instanceId, string numeroDeOrden, Molinos.Scato.Dominio.Dto.AnalisisPorCaracteristicaDto[] caracteristicasAnalizadas) {
            return base.Channel.AnalisisDeCalidad(instanceId, numeroDeOrden, caracteristicasAnalizadas);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Dominio.Comandos.Resultado> AnalisisDeCalidadAsync(System.Guid instanceId, string numeroDeOrden, Molinos.Scato.Dominio.Dto.AnalisisPorCaracteristicaDto[] caracteristicasAnalizadas) {
            return base.Channel.AnalisisDeCalidadAsync(instanceId, numeroDeOrden, caracteristicasAnalizadas);
        }
    }
}
