<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <!--General-->
    <ProjectSolution>..\Molinos.Scato.sln</ProjectSolution>
    <NUnitToolPath>C:\Program Files (x86)\NUnit 2.6.3\bin</NUnitToolPath>
    <NUnitProject>..\Molinos.Scato.Test\bin\Jenkins\Molinos.Scato.Test.dll</NUnitProject>
    <OutputDir>..\Deploy\</OutputDir>
    <PackageWeb>..\Molinos.Scato.Web\obj\Jenkins\Package\**\*</PackageWeb>
    <PackageServicios>..\Molinos.Scato.ServiciosWeb\obj\Jenkins\Package\**\*</PackageServicios>
    <PackageWorkflow>..\Molinos.Scato.Workflow\obj\Jenkins\Package\**\*</PackageWorkflow>
    <PackageWebMobile>..\Molinos.Scato.WebMobile\obj\Jenkins\Package\**\*</PackageWebMobile>
    <PackageWebOperaciones>..\Molinos.Scato.WebOperaciones\obj\Jenkins\Package\**\*</PackageWebOperaciones>
    <PackageModuloImpresor>..\Molinos.Scato.ModuloImpresor\obj\Jenkins\Package\**\*</PackageModuloImpresor>
    <PackageWebPuerto>..\Molinos.Scato.WebPuerto\obj\Jenkins\Package\**\*</PackageWebPuerto>
    <PackageWebPuertoApi>..\Molinos.Scato.WebPuertoApi\obj\Jenkins\Package\**\*</PackageWebPuertoApi>

    <XamlxWorkflow>..\Molinos.Scato.Workflow\**\*.xamlx</XamlxWorkflow>

    <OpenCoverTool>C:\Program Files (x86)\OpenCover\OpenCover.Console.exe</OpenCoverTool>
    <!--<OpenCoverFilter>+[Molinos.Scato.Web]Molinos.Scato.Web.Controllers.* +[Molinos.Scato.Actividades]* +[Molinos.Scato.Servicios]Molinos.Scato.Servicios.Procesamiento.* +[Molinos.Scato.Servicios]Molinos.Scato.Servicios.ServicioComandos +[Molinos.Scato.Servicios]Molinos.Scato.Servicios.ServicioRepositorio</OpenCoverFilter>-->
    <OpenCoverFilter>+[Molinos.Scato.Actividades]* +[Molinos.Scato.Dominio]* -[Molinos.Scato.Dominio]Molinos.Scato.Dominio.Recursos.* +[Molinos.Scato.Repositorio]* +[Molinos.Scato.Servicios]* -[Molinos.Scato.Servicios]Molinos.Scato.Servicios.AfipWebService.* -[Molinos.Scato.Servicios]Molinos.Scato.Servicios.AfipCTGWebService.* -[Molinos.Scato.Servicios]Molinos.Scato.Servicios.ComplianceWebService.* -[Molinos.Scato.Servicios]Molinos.Scato.Servicios.GestionarCartasDePortePE.* -[Molinos.Scato.Servicios]Molinos.Scato.Servicios.Orquestador.* -[Molinos.Scato.Servicios]Molinos.Scato.Servicios.ServiciosSap.* +[Molinos.Scato.ServiciosWeb]* +[Molinos.Scato.Web]* +[Molinos.Scato.WfEditor]* +[Molinos.Scato.Workflow]*</OpenCoverFilter>

    <ReportGeneratorTool>C:\Program Files (x86)\ReportGenerator\bin\ReportGenerator.exe</ReportGeneratorTool>

    <GendarmeTool>C:\Program Files (x86)\Gendarme\gendarme.exe</GendarmeTool>
    <GendarmeAssemblies>..\Molinos.Scato.Actividades\bin\Jenkins\Molinos.Scato.Actividades.dll ..\Molinos.Scato.Dominio\bin\Jenkins\Molinos.Scato.Dominio.dll ..\Molinos.Scato.Repositorio\bin\Jenkins\Molinos.Scato.Repositorio.dll ..\Molinos.Scato.Web\bin\Molinos.Scato.Web.dll ..\Molinos.Scato.Workflow\bin\Molinos.Scato.Workflow.dll</GendarmeAssemblies>

    <!--<StyleCopCmdToolPath>C:\Program Files (x86)\StyleCopCmd</StyleCopCmdToolPath>-->

    <OutputPackDir>..\Deploy\DeployPack</OutputPackDir>
    <OutputPackEditorDir>..\Deploy\DeployPack\EditorWf</OutputPackEditorDir>
    <OutputPackWebDir>..\Deploy\DeployPack\Web</OutputPackWebDir>
    <OutputPackServiciosWebDir>..\Deploy\DeployPack\ServiciosWeb</OutputPackServiciosWebDir>
    <OutputPackWorkflowDir>..\Deploy\DeployPack\Workflow</OutputPackWorkflowDir>
    <OutputPackReportsDir>..\Deploy\DeployPack\Reportes</OutputPackReportsDir>
    <OutputPackWebMobileDir>..\Deploy\DeployPack\WebMobile</OutputPackWebMobileDir>
    <OutputPackWebOperacionesDir>..\Deploy\DeployPack\WebOperaciones</OutputPackWebOperacionesDir>
    <OutputPackModuloImpresorDir>..\Deploy\DeployPack\ModuloImpresor</OutputPackModuloImpresorDir>
    <OutputPackWebPuertoDir>..\Deploy\DeployPack\WebPuerto</OutputPackWebPuertoDir>
    <OutputPackWebPuertoApiDir>..\Deploy\DeployPack\WebPuertoApi</OutputPackWebPuertoApiDir>

    <ZipDir>..\Deploy\**\*.zip</ZipDir>
    <CmdDir>..\Deploy\**\*.cmd</CmdDir>
    
    <DeployParametersWeb>..\Molinos.Scato.Web\*.DeployParameters.xml</DeployParametersWeb>
    <DeployParametersServicios>..\Molinos.Scato.ServiciosWeb\*.DeployParameters.xml</DeployParametersServicios>
    <DeployParametersWorkflow>..\Molinos.Scato.Workflow\*.DeployParameters.xml</DeployParametersWorkflow>
    <DeployParametersWebMobile>..\Molinos.Scato.WebMobile\*.DeployParameters.xml</DeployParametersWebMobile>
    <DeployParametersWebOperaciones>..\Molinos.Scato.WebOperaciones\*.DeployParameters.xml</DeployParametersWebOperaciones>
    <DeployParametersModuloImpresor>..\Molinos.Scato.ModuloImpresor\*.DeployParameters.xml</DeployParametersModuloImpresor>
    <DeployParametersWebPuerto>..\Molinos.Scato.WebPuerto\*.DeployParameters.xml</DeployParametersWebPuerto>
    <DeployParametersWebPuertoApi>..\Molinos.Scato.WebPuertoApi\*.DeployParameters.xml</DeployParametersWebPuertoApi>

    <MsiDir>..\Deploy\EditorWF\</MsiDir>
    <QaMsiDir>..\Deploy\EditorWF\**\*.qa.msi</QaMsiDir>
    <ProdMsiDir>..\Deploy\EditorWF\**\*.prod.msi</ProdMsiDir>
    
    <ReportsDir>..\Molinos.Scato.Reportes\*.rdl</ReportsDir>

    <BatDir>..\Molinos.Scato.Build\DeployBat\*.bat</BatDir>
    
  
</PropertyGroup>

</Project>