$DB = "Scato"
$Server = ".\SQLEXPRESS"
$Evironment = "DEV"
$Files = "."
# $CreateDB = $Files + "\CustomCreateDB.sql"
$AlterDB = $Files + "\01 AlterDatabase"
$RunAfterCreate = $Files + "\02 RunAfterCreateDatabase"
$RunBeforeUp = $Files + "\03 RunBeforeUp"
$Up = $Files + "\04 Up"
$RunAfterUp = $Files + "\05 RunFirstAfterUp"
$Functions = $Files + "\06 Functions"
$Views = $Files + "\07 Views"
$Sprocs = $Files + "\08 StoredProcedures"
$Trigger = $Files + "\09 Triggers"
$Indexes = $Files + "\10 Indexes"
$RunAfterAny = $Files + "\11 RunAfterOtherAnyTimeScripts"
$Perms = $Files + "\12 Permissions"
$Version = $Files + "\Version\RoundhouseDBVersion.txt"
$Out = $Files + "\Output"
 
&rh.exe -database $DB -servername $Server -env $Evironment -files $Files -alterdatabasefolder $AlterDB -runaftercreatedatabasefolder $RunAfterCreate -runbeforeupfolder $RunBeforeUp -upfolder $Up -runfirstfolder $RunAfterUp -functionsfolder $Functions -viewsfolder $Views -sprocsfolder $Sprocs -triggersfolder $Trigger -indexesfolder $Indexes -runAfterOtherAnyTimeScriptsfolder $RunAfterAny -permissionsfolder $Perms -versionfile $Version -output $Out -dryrun