//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.Scato.Servicios.Urenport {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Urenport.calpesSoap")]
    public interface calpesSoap {
        
        // CODEGEN: Generating message contract since element name pic from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imagen", ReplyAction="*")]
        Molinos.Scato.Servicios.Urenport.ImagenResponse Imagen(Molinos.Scato.Servicios.Urenport.ImagenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imagen", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.Urenport.ImagenResponse> ImagenAsync(Molinos.Scato.Servicios.Urenport.ImagenRequest request);
        
        // CODEGEN: Generating message contract since element name Au from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        Molinos.Scato.Servicios.Urenport.TestResponse Test(Molinos.Scato.Servicios.Urenport.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.Urenport.TestResponse> TestAsync(Molinos.Scato.Servicios.Urenport.TestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImagenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Imagen", Namespace="http://tempuri.org/", Order=0)]
        public Molinos.Scato.Servicios.Urenport.ImagenRequestBody Body;
        
        public ImagenRequest() {
        }
        
        public ImagenRequest(Molinos.Scato.Servicios.Urenport.ImagenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImagenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] pic;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numCP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipo_doc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Au;
        
        public ImagenRequestBody() {
        }
        
        public ImagenRequestBody(byte[] pic, string numCP, string tipo_doc, string Au) {
            this.pic = pic;
            this.numCP = numCP;
            this.tipo_doc = tipo_doc;
            this.Au = Au;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImagenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImagenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Molinos.Scato.Servicios.Urenport.ImagenResponseBody Body;
        
        public ImagenResponse() {
        }
        
        public ImagenResponse(Molinos.Scato.Servicios.Urenport.ImagenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImagenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImagenResult;
        
        public ImagenResponseBody() {
        }
        
        public ImagenResponseBody(string ImagenResult) {
            this.ImagenResult = ImagenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public Molinos.Scato.Servicios.Urenport.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(Molinos.Scato.Servicios.Urenport.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Au;
        
        public TestRequestBody() {
        }
        
        public TestRequestBody(string Au) {
            this.Au = Au;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Molinos.Scato.Servicios.Urenport.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(Molinos.Scato.Servicios.Urenport.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calpesSoapChannel : Molinos.Scato.Servicios.Urenport.calpesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calpesSoapClient : System.ServiceModel.ClientBase<Molinos.Scato.Servicios.Urenport.calpesSoap>, Molinos.Scato.Servicios.Urenport.calpesSoap {
        
        public calpesSoapClient() {
        }
        
        public calpesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calpesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calpesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calpesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.Scato.Servicios.Urenport.ImagenResponse Molinos.Scato.Servicios.Urenport.calpesSoap.Imagen(Molinos.Scato.Servicios.Urenport.ImagenRequest request) {
            return base.Channel.Imagen(request);
        }
        
        public string Imagen(byte[] pic, string numCP, string tipo_doc, string Au) {
            Molinos.Scato.Servicios.Urenport.ImagenRequest inValue = new Molinos.Scato.Servicios.Urenport.ImagenRequest();
            inValue.Body = new Molinos.Scato.Servicios.Urenport.ImagenRequestBody();
            inValue.Body.pic = pic;
            inValue.Body.numCP = numCP;
            inValue.Body.tipo_doc = tipo_doc;
            inValue.Body.Au = Au;
            Molinos.Scato.Servicios.Urenport.ImagenResponse retVal = ((Molinos.Scato.Servicios.Urenport.calpesSoap)(this)).Imagen(inValue);
            return retVal.Body.ImagenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.Urenport.ImagenResponse> Molinos.Scato.Servicios.Urenport.calpesSoap.ImagenAsync(Molinos.Scato.Servicios.Urenport.ImagenRequest request) {
            return base.Channel.ImagenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Servicios.Urenport.ImagenResponse> ImagenAsync(byte[] pic, string numCP, string tipo_doc, string Au) {
            Molinos.Scato.Servicios.Urenport.ImagenRequest inValue = new Molinos.Scato.Servicios.Urenport.ImagenRequest();
            inValue.Body = new Molinos.Scato.Servicios.Urenport.ImagenRequestBody();
            inValue.Body.pic = pic;
            inValue.Body.numCP = numCP;
            inValue.Body.tipo_doc = tipo_doc;
            inValue.Body.Au = Au;
            return ((Molinos.Scato.Servicios.Urenport.calpesSoap)(this)).ImagenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.Scato.Servicios.Urenport.TestResponse Molinos.Scato.Servicios.Urenport.calpesSoap.Test(Molinos.Scato.Servicios.Urenport.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test(string Au) {
            Molinos.Scato.Servicios.Urenport.TestRequest inValue = new Molinos.Scato.Servicios.Urenport.TestRequest();
            inValue.Body = new Molinos.Scato.Servicios.Urenport.TestRequestBody();
            inValue.Body.Au = Au;
            Molinos.Scato.Servicios.Urenport.TestResponse retVal = ((Molinos.Scato.Servicios.Urenport.calpesSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.Urenport.TestResponse> Molinos.Scato.Servicios.Urenport.calpesSoap.TestAsync(Molinos.Scato.Servicios.Urenport.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Servicios.Urenport.TestResponse> TestAsync(string Au) {
            Molinos.Scato.Servicios.Urenport.TestRequest inValue = new Molinos.Scato.Servicios.Urenport.TestRequest();
            inValue.Body = new Molinos.Scato.Servicios.Urenport.TestRequestBody();
            inValue.Body.Au = Au;
            return ((Molinos.Scato.Servicios.Urenport.calpesSoap)(this)).TestAsync(inValue);
        }
    }
}
