//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.Scato.Servicios.ComplianceWebServiceV2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://beta.webcompliance.com.ar/webcompliance/webservice/agroacopios", ConfigurationName="ComplianceWebServiceV2.DatosPort")]
    public interface DatosPort {
        
        // CODEGEN: Generating message contract since the operation controlarDatosAgroacopios is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://beta.webcompliance.com.ar/webcompliance/webservice/agroacopios#controlarDa" +
            "tosAgroacopios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosResponse controlarDatosAgroacopios(Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://beta.webcompliance.com.ar/webcompliance/webservice/agroacopios#controlarDa" +
            "tosAgroacopios", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosResponse> controlarDatosAgroacopiosAsync(Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beta.webcompliance.com.ar/webcompliance/webservice/agroacopios")]
    public partial class Datos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cuitField;
        
        private string dniField;
        
        private string patente1Field;
        
        private string patente2Field;
        
        private string plantaField;
        
        /// <remarks/>
        public string cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
                this.RaisePropertyChanged("cuit");
            }
        }
        
        /// <remarks/>
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        public string patente1 {
            get {
                return this.patente1Field;
            }
            set {
                this.patente1Field = value;
                this.RaisePropertyChanged("patente1");
            }
        }
        
        /// <remarks/>
        public string patente2 {
            get {
                return this.patente2Field;
            }
            set {
                this.patente2Field = value;
                this.RaisePropertyChanged("patente2");
            }
        }
        
        /// <remarks/>
        public string planta {
            get {
                return this.plantaField;
            }
            set {
                this.plantaField = value;
                this.RaisePropertyChanged("planta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beta.webcompliance.com.ar/webcompliance/webservice/agroacopios")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int colorEmpresaField;
        
        private int codigoErrorField;
        
        private string nombreEmpresaField;
        
        private int colorChoferField;
        
        private string nombreChoferField;
        
        private int colorVehiculo1Field;
        
        private string codigoVehiculo1Field;
        
        private int colorVehiculo2Field;
        
        private string codigoVehiculo2Field;
        
        private string codigoCombinacionField;
        
        private int palletsField;
        
        private string avlChoferField;
        
        private string avlVehiculo1Field;
        
        private string avlVehiculo2Field;
        
        private string subcontrataChoferField;
        
        private string subcontrataVehiculo1Field;
        
        private string subcontrataVehiculo2Field;
        
        /// <remarks/>
        public int colorEmpresa {
            get {
                return this.colorEmpresaField;
            }
            set {
                this.colorEmpresaField = value;
                this.RaisePropertyChanged("colorEmpresa");
            }
        }
        
        /// <remarks/>
        public int codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("codigoError");
            }
        }
        
        /// <remarks/>
        public string nombreEmpresa {
            get {
                return this.nombreEmpresaField;
            }
            set {
                this.nombreEmpresaField = value;
                this.RaisePropertyChanged("nombreEmpresa");
            }
        }
        
        /// <remarks/>
        public int colorChofer {
            get {
                return this.colorChoferField;
            }
            set {
                this.colorChoferField = value;
                this.RaisePropertyChanged("colorChofer");
            }
        }
        
        /// <remarks/>
        public string nombreChofer {
            get {
                return this.nombreChoferField;
            }
            set {
                this.nombreChoferField = value;
                this.RaisePropertyChanged("nombreChofer");
            }
        }
        
        /// <remarks/>
        public int colorVehiculo1 {
            get {
                return this.colorVehiculo1Field;
            }
            set {
                this.colorVehiculo1Field = value;
                this.RaisePropertyChanged("colorVehiculo1");
            }
        }
        
        /// <remarks/>
        public string codigoVehiculo1 {
            get {
                return this.codigoVehiculo1Field;
            }
            set {
                this.codigoVehiculo1Field = value;
                this.RaisePropertyChanged("codigoVehiculo1");
            }
        }
        
        /// <remarks/>
        public int colorVehiculo2 {
            get {
                return this.colorVehiculo2Field;
            }
            set {
                this.colorVehiculo2Field = value;
                this.RaisePropertyChanged("colorVehiculo2");
            }
        }
        
        /// <remarks/>
        public string codigoVehiculo2 {
            get {
                return this.codigoVehiculo2Field;
            }
            set {
                this.codigoVehiculo2Field = value;
                this.RaisePropertyChanged("codigoVehiculo2");
            }
        }
        
        /// <remarks/>
        public string codigoCombinacion {
            get {
                return this.codigoCombinacionField;
            }
            set {
                this.codigoCombinacionField = value;
                this.RaisePropertyChanged("codigoCombinacion");
            }
        }
        
        /// <remarks/>
        public int pallets {
            get {
                return this.palletsField;
            }
            set {
                this.palletsField = value;
                this.RaisePropertyChanged("pallets");
            }
        }
        
        /// <remarks/>
        public string avlChofer {
            get {
                return this.avlChoferField;
            }
            set {
                this.avlChoferField = value;
                this.RaisePropertyChanged("avlChofer");
            }
        }
        
        /// <remarks/>
        public string avlVehiculo1 {
            get {
                return this.avlVehiculo1Field;
            }
            set {
                this.avlVehiculo1Field = value;
                this.RaisePropertyChanged("avlVehiculo1");
            }
        }
        
        /// <remarks/>
        public string avlVehiculo2 {
            get {
                return this.avlVehiculo2Field;
            }
            set {
                this.avlVehiculo2Field = value;
                this.RaisePropertyChanged("avlVehiculo2");
            }
        }
        
        /// <remarks/>
        public string subcontrataChofer {
            get {
                return this.subcontrataChoferField;
            }
            set {
                this.subcontrataChoferField = value;
                this.RaisePropertyChanged("subcontrataChofer");
            }
        }
        
        /// <remarks/>
        public string subcontrataVehiculo1 {
            get {
                return this.subcontrataVehiculo1Field;
            }
            set {
                this.subcontrataVehiculo1Field = value;
                this.RaisePropertyChanged("subcontrataVehiculo1");
            }
        }
        
        /// <remarks/>
        public string subcontrataVehiculo2 {
            get {
                return this.subcontrataVehiculo2Field;
            }
            set {
                this.subcontrataVehiculo2Field = value;
                this.RaisePropertyChanged("subcontrataVehiculo2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class controlarDatosAgroacopiosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Molinos.Scato.Servicios.ComplianceWebServiceV2.Datos datos;
        
        public controlarDatosAgroacopiosRequest() {
        }
        
        public controlarDatosAgroacopiosRequest(Molinos.Scato.Servicios.ComplianceWebServiceV2.Datos datos) {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class controlarDatosAgroacopiosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Molinos.Scato.Servicios.ComplianceWebServiceV2.Response controlarDatosReturn;
        
        public controlarDatosAgroacopiosResponse() {
        }
        
        public controlarDatosAgroacopiosResponse(Molinos.Scato.Servicios.ComplianceWebServiceV2.Response controlarDatosReturn) {
            this.controlarDatosReturn = controlarDatosReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatosPortChannel : Molinos.Scato.Servicios.ComplianceWebServiceV2.DatosPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatosPortClient : System.ServiceModel.ClientBase<Molinos.Scato.Servicios.ComplianceWebServiceV2.DatosPort>, Molinos.Scato.Servicios.ComplianceWebServiceV2.DatosPort {
        
        public DatosPortClient() {
        }
        
        public DatosPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatosPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatosPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatosPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosResponse Molinos.Scato.Servicios.ComplianceWebServiceV2.DatosPort.controlarDatosAgroacopios(Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosRequest request) {
            return base.Channel.controlarDatosAgroacopios(request);
        }
        
        public Molinos.Scato.Servicios.ComplianceWebServiceV2.Response controlarDatosAgroacopios(Molinos.Scato.Servicios.ComplianceWebServiceV2.Datos datos) {
            Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosRequest inValue = new Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosRequest();
            inValue.datos = datos;
            Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosResponse retVal = ((Molinos.Scato.Servicios.ComplianceWebServiceV2.DatosPort)(this)).controlarDatosAgroacopios(inValue);
            return retVal.controlarDatosReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosResponse> Molinos.Scato.Servicios.ComplianceWebServiceV2.DatosPort.controlarDatosAgroacopiosAsync(Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosRequest request) {
            return base.Channel.controlarDatosAgroacopiosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosResponse> controlarDatosAgroacopiosAsync(Molinos.Scato.Servicios.ComplianceWebServiceV2.Datos datos) {
            Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosRequest inValue = new Molinos.Scato.Servicios.ComplianceWebServiceV2.controlarDatosAgroacopiosRequest();
            inValue.datos = datos;
            return ((Molinos.Scato.Servicios.ComplianceWebServiceV2.DatosPort)(this)).controlarDatosAgroacopiosAsync(inValue);
        }
    }
}
