UPDATE Campo SET TituloOncca = 'Fecha' WHERE Direccion = 'FechaEmision'
UPDATE Campo SET TituloOncca = 'Remitente o Destinatario' WHERE Direccion = 'TitularCP'
UPDATE Campo SET TituloOncca = 'Cuit' WHERE Direccion = 'CuitTitularCP'
UPDATE Campo SET TituloOncca = 'Remitente o Destinatario' WHERE Direccion = 'Destinatario'
UPDATE Campo SET TituloOncca = 'Cuit' WHERE Direccion = 'CuitDestinatario'
UPDATE Campo SET TituloOncca = 'Kilos Netos' WHERE Direccion = 'PesoNeto'
UPDATE Campo SET TituloOncca = 'Tipo' WHERE Direccion = 'TipoDeComprobanteONCCA'
UPDATE Campo SET TituloOncca = 'Número' WHERE Direccion = 'NumeroDeDocumentoDeIngreso'
UPDATE Campo SET TituloOncca = 'Kilos Netos' WHERE Direccion = 'SaldosSTOCK'
UPDATE Campo SET TituloOncca = 'Observaciones' WHERE Direccion = 'ObservacionesONCCA'
UPDATE Campo SET TituloOncca = 'Kilos Netos' WHERE Direccion = 'PesoNetoSinHumedad'
