BEGIN TRAN;

Update Destino set Activo = 0 where id = 1;

Update Destino set IdSap = 'ES', nacionalidad = 'española', IdBandera = 73 where id = 2;
Update Destino set IdSap = 'IT', nacionalidad = 'italiana', IdBandera = 113 where id = 3;
Update Destino set IdSap = 'PE', nacionalidad = 'Peruana', IdBandera = 174 where id = 4;
Update Destino set IdSap = 'GB', nacionalidad = 'británica', IdBandera = 241 where id = 5;
Update Destino set IdSap = 'PH', nacionalidad = 'filipina', IdBandera = 80 where id = 6;
Update Destino set IdSap = 'ZA', nacionalidad = 'sudafricana', IdBandera = 205 where id = 7;
Update Destino set IdSap = 'NL', nacionalidad = 'holandesa', IdBandera = 167 where id = 8;
Update Destino set IdSap = 'PL', nacionalidad = 'polaca', IdBandera = 177 where id = 9;
Update Destino set IdSap = 'AU', nacionalidad = 'australiana', IdBandera = 16 where id = 10;
Update Destino set IdSap = 'NL', nacionalidad = 'holandesa', IdBandera = 167 where id = 11;
Update Destino set IdSap = 'IN', nacionalidad = 'hindú', IdBandera = 106 where id = 14;
Update Destino set IdSap = 'TH', nacionalidad = 'tailandesa', IdBandera = 211 where id = 15;
Update Destino set IdSap = 'CO', nacionalidad = 'colombiana', IdBandera = 52 where id = 16;
Update Destino set IdSap = 'PK', nacionalidad = 'pakistaní', IdBandera = 168 where id = 17;
Update Destino set IdSap = 'LY', nacionalidad = 'libia', IdBandera = 127 where id = 18;
Update Destino set IdSap = 'TN', nacionalidad = 'tunecina', IdBandera = 222 where id = 19;
Update Destino set IdSap = 'DZ', nacionalidad = 'argelina', IdBandera = 12 where id = 20;
Update Destino set IdSap = 'JP', nacionalidad = 'japonesa', IdBandera = 115 where id = 21;
Update Destino set IdSap = 'CN', nacionalidad = 'Chino', IdBandera = 47 where id = 22;
Update Destino set IdSap = 'MA', nacionalidad = 'marroquí', IdBandera = 141 where id = 24;
Update Destino set IdSap = 'ID', nacionalidad = 'indonesia', IdBandera = 107 where id = 25;
Update Destino set IdSap = 'EG', nacionalidad = 'egipcia', IdBandera = 67 where id = 26;
Update Destino set IdSap = 'IE', nacionalidad = 'irlandesa', IdBandera = 110 where id = 27;
Update Destino set IdSap = 'TR', nacionalidad = 'turca', IdBandera = 225 where id = 28;
Update Destino set IdSap = 'EC', nacionalidad = 'ecuatoriana', IdBandera = 66 where id = 30;
Update Destino set IdSap = 'BD', nacionalidad = 'bangladesí', IdBandera = 21 where id = 31;
Update Destino set IdSap = 'US', nacionalidad = 'estadounidense', IdBandera = 75 where id = 32;
Update Destino set IdSap = 'PT', nacionalidad = 'portuguesa', IdBandera = 178 where id = 33;
Update Destino set IdSap = 'BE', nacionalidad = 'belga', IdBandera = 24 where id = 34;
Update Destino set IdSap = 'VN', nacionalidad = 'vietnamita', IdBandera = 233 where id = 35;
Update Destino set IdSap = 'DZ', nacionalidad = 'argelina', IdBandera = 12 where id = 36;
Update Destino set IdSap = 'CY', nacionalidad = 'chipriota', IdBandera = 48 where id = 37;
Update Destino set IdSap = 'SY', nacionalidad = 'siria', IdBandera = 201 where id = 38;
Update Destino set IdSap = 'MG', nacionalidad = 'madecasiana', IdBandera = 133 where id = 39;
Update Destino set IdSap = 'IR', nacionalidad = 'iraní', IdBandera = 108 where id = 41;
Update Destino set IdSap = 'NZ', nacionalidad = 'neozelandesa', IdBandera = 165 where id = 42;
Update Destino set IdSap = 'NL', nacionalidad = 'holandesa', IdBandera = 167 where id = 43;
Update Destino set IdSap = 'KP', nacionalidad = 'coreana', IdBandera = 57 where id = 44;
Update Destino set IdSap = 'CL', nacionalidad = 'chilena', IdBandera = 46 where id = 46;
Update Destino set IdSap = 'DE', nacionalidad = 'alemana', IdBandera = 4 where id = 47;
Update Destino set IdSap = 'MY', nacionalidad = 'malaya', IdBandera = 134 where id = 48;
Update Destino set IdSap = 'LB', nacionalidad = 'libanesa', IdBandera = 125 where id = 49;
Update Destino set IdSap = 'FR', nacionalidad = 'francesa', IdBandera = 83 where id = 50;
Update Destino set IdSap = 'DK', nacionalidad = 'Danesa', IdBandera = 63 where id = 51;

Update Destino set Activo = 0 where id = 54;

Update Destino set IdSap = 'PL', nacionalidad = 'polaca', IdBandera = 177 where id = 55;
Update Destino set IdSap = 'PA', nacionalidad = 'panameña', IdBandera = 171 where id = 57;
Update Destino set IdSap = 'GT', nacionalidad = 'guatemalteca', IdBandera = 95 where id = 60;
Update Destino set IdSap = 'DO', nacionalidad = 'dominicana', IdBandera = 65 where id = 61;
Update Destino set IdSap = 'KR', nacionalidad = 'coreana', IdBandera = 58 where id = 64;
Update Destino set IdSap = 'RU', nacionalidad = 'rusa', IdBandera = 184 where id = 66;
Update Destino set IdSap = 'MZ', nacionalidad = 'mozambiqueña', IdBandera = 153 where id = 67;
Update Destino set IdSap = 'BR', nacionalidad = 'brasileña', IdBandera = 33 where id = 68;
Update Destino set IdSap = 'YE', nacionalidad = 'yemenita', IdBandera = 237 where id = 69;
Update Destino set IdSap = 'GR', nacionalidad = 'griega', IdBandera = 91 where id = 70;
Update Destino set IdSap = 'MA', nacionalidad = 'marroquí', IdBandera = 141 where id = 71;
Update Destino set IdSap = 'OM', nacionalidad = 'omaní', IdBandera = 166 where id = 73;
Update Destino set IdSap = 'AE', nacionalidad = 'árabe', IdBandera = 69 where id = 75;
Update Destino set IdSap = 'SA', nacionalidad = 'saudí', IdBandera = 11 where id = 76;
Update Destino set IdSap = 'IT', nacionalidad = 'italiana', IdBandera = 113 where id = 77;
Update Destino set IdSap = 'TZ', nacionalidad = 'tanzana', IdBandera = 213 where id = 78;
Update Destino set IdSap = 'KE', nacionalidad = 'keniana', IdBandera = 118 where id = 79;
Update Destino set IdSap = 'US', nacionalidad = 'estadounidense', IdBandera = 75 where id = 80;
Update Destino set IdSap = 'IT', nacionalidad = 'italiana', IdBandera = 113 where id = 81;
Update Destino set IdSap = 'SI', nacionalidad = 'eslovenia', IdBandera = 72 where id = 82;
Update Destino set IdSap = 'RO', nacionalidad = 'rumana', IdBandera = 183 where id = 83;
Update Destino set IdSap = 'CU', nacionalidad = 'cubana', IdBandera = 62 where id = 84;

Update Destino set Activo = 0 where id = 86;

--Update Destino set IdSap = 'LD', nacionalidad = 'Latviana', IdBandera = ALTA BANDERA where id = 89;
Update Destino set IdSap = 'SY', nacionalidad = 'siria', IdBandera = 201 where id = 91;
Update Destino set IdSap = 'GB', nacionalidad = 'británica', IdBandera = 241 where id = 92;
Update Destino set IdSap = 'LT', nacionalidad = 'lituana', IdBandera = 129 where id = 94;
Update Destino set IdSap = 'CR', nacionalidad = 'costarricense', IdBandera = 60 where id = 95;
Update Destino set IdSap = 'VN', nacionalidad = 'vietnamita', IdBandera = 233 where id = 97;
Update Destino set IdSap = 'VE', nacionalidad = 'venezolana', IdBandera = 232 where id = 98;
Update Destino set IdSap = 'SA', nacionalidad = 'saudí', IdBandera = 11 where id = 99;
Update Destino set IdSap = 'AR', nacionalidad = 'argentina', IdBandera = 13 where id = 100;
Update Destino set IdSap = 'SN', nacionalidad = 'senegalesa', IdBandera = 196 where id = 102;
Update Destino set IdSap = 'AR', nacionalidad = 'argentina', IdBandera = 13 where id = 103;
Update Destino set IdSap = 'CI', nacionalidad = 'Marfilense', IdBandera = 59 where id = 104;
Update Destino set IdSap = 'BN', nacionalidad = 'de Brunei', IdBandera = 34 where id = 106;
Update Destino set IdSap = 'CG', nacionalidad = 'Congoleña', IdBandera = 55 where id = 109;
Update Destino set IdSap = 'NA', nacionalidad = 'namibia', IdBandera = 155 where id = 110;
Update Destino set IdSap = 'MU', nacionalidad = 'mauriciense', IdBandera = 144 where id = 113;
Update Destino set IdSap = 'MU', nacionalidad = 'mauriciense', IdBandera = 144 where id = 114;
Update Destino set IdSap = 'IL', nacionalidad = 'israelí', IdBandera = 112 where id = 116;
Update Destino set IdSap = 'HK', nacionalidad = 'china', IdBandera = 104 where id = 117;
Update Destino set IdSap = 'AE', nacionalidad = 'árabe', IdBandera = 69 where id = 119;
Update Destino set IdSap = 'BY', nacionalidad = 'bielorrusa', IdBandera = 23 where id = 121;
Update Destino set IdSap = 'MR', nacionalidad = 'mauritana', IdBandera = 145 where id = 122;
Update Destino set IdSap = 'GH', nacionalidad = 'ghanesa', IdBandera = 88 where id = 123;
Update Destino set IdSap = 'CV', nacionalidad = 'caboverdiana', IdBandera = 38 where id = 124;
Update Destino set IdSap = 'CM', nacionalidad = 'camerunesa', IdBandera = 41 where id = 126;

Update Destino set Activo = 0 where id = 128;
Update Destino set Activo = 0 where id = 129;
Update Destino set Activo = 0 where id = 130;
Update Destino set Activo = 0 where id = 131;
Update Destino set Activo = 0 where id = 132;
Update Destino set Activo = 0 where id = 133;
Update Destino set Activo = 0 where id = 134;
Update Destino set Activo = 0 where id = 136;

Update Destino set IdSap = 'LV', nacionalidad = 'letona', IdBandera = 124 where id = 139;

Update Destino set Activo = 0 where id = 140;
Update Destino set Activo = 0 where id = 141;

Update Destino set IdSap = 'TW', nacionalidad = 'taiwanesa', IdBandera = 212 where id = 142;
Update Destino set IdSap = 'JO', nacionalidad = 'jordana', IdBandera = 116 where id = 143;

Update Destino set Activo = 0 where id = 144;
Update Destino set Activo = 0 where id = 146;
Update Destino set Activo = 0 where id = 147;
Update Destino set Activo = 0 where id = 150;
Update Destino set Activo = 0 where id = 151;
Update Destino set Activo = 0 where id = 152;
Update Destino set Activo = 0 where id = 153;
Update Destino set Activo = 0 where id = 154;
Update Destino set Activo = 0 where id = 155;
Update Destino set Activo = 0 where id = 156;
Update Destino set Activo = 0 where id = 157;

Update Destino set IdSap = 'NG', nacionalidad = 'nigeriana', IdBandera = 160 where id = 158;
Update Destino set IdSap = 'UG', nacionalidad = 'ugandesa', IdBandera = 228 where id = 159;

Update Destino set Activo = 0 where id = 160;
Update Destino set Activo = 0 where id = 163;

Update Destino set IdSap = 'GT', nacionalidad = 'guatemalteca', IdBandera = 95 where id = 164;

Update Destino set Activo = 0 where id = 165;

Update Destino set IdSap = 'IN', nacionalidad = 'hindú', IdBandera = 106 where id = 166;
Update Destino set IdSap = 'IQ', nacionalidad = 'iraquí', IdBandera = 109 where id = 168;
Update Destino set IdSap = 'EG', nacionalidad = 'egipcia', IdBandera = 67 where id = 169;
Update Destino set IdSap = 'NL', nacionalidad = 'holandesa', IdBandera = 167 where id = 170;
Update Destino set IdSap = 'MU', nacionalidad = 'mauriciense', IdBandera = 144 where id = 171;
Update Destino set IdSap = 'GN', nacionalidad = 'guineana', IdBandera = 97 where id = 172;
Update Destino set IdSap = 'AO', nacionalidad = 'angolana', IdBandera = 6 where id = 173;
Update Destino set IdSap = 'IQ', nacionalidad = 'iraquí', IdBandera = 109 where id = 174;
Update Destino set IdSap = 'AE', nacionalidad = 'árabe', IdBandera = 69 where id = 175;
Update Destino set IdSap = 'DO', nacionalidad = 'dominicana', IdBandera = 65 where id = 176;
Update Destino set IdSap = 'KR', nacionalidad = 'coreana', IdBandera = 58 where id = 177;
Update Destino set IdSap = 'DZ', nacionalidad = 'argelina', IdBandera = 12 where id = 178;
Update Destino set IdSap = 'KE', nacionalidad = 'keniana', IdBandera = 118 where id = 179;
Update Destino set IdSap = 'MX', nacionalidad = 'mexicana', IdBandera = 147 where id = 180;
Update Destino set IdSap = 'KW', nacionalidad = 'kuwaití', IdBandera = 121 where id = 181;
Update Destino set IdSap = 'ZA', nacionalidad = 'sudafricana', IdBandera = 205 where id = 182;
Update Destino set IdSap = 'MM', nacionalidad = 'Myanmar', IdBandera = 154 where id = 183;

Update Destino set Activo = 0 where id = 184;

Update Destino set IdSap = 'VN', nacionalidad = 'vietnamita', IdBandera = 233 where id = 185;
Update Destino set IdSap = 'GE', nacionalidad = 'georgiana', IdBandera = 86 where id = 186;
Update Destino set IdSap = 'LR', nacionalidad = 'liberiana', IdBandera = 126 where id = 187;
Update Destino set IdSap = 'CA', nacionalidad = 'canadiense', IdBandera = 42 where id = 188;

Update Destino set IdSap = 'ZPE', nacionalidad = '', IdBandera = NULL where id = 189;
Update Destino set IdSap = 'ZPE', nacionalidad = '', IdBandera = NULL where id = 190;
Update Destino set IdSap = 'ZPE', nacionalidad = '', IdBandera = NULL where id = 191;

Update Destino set IdSap = 'SV', nacionalidad = 'salvadoreña', IdBandera = 68 where id = 192;
Update Destino set IdSap = 'NI', nacionalidad = 'nicaragüense', IdBandera = 158 where id = 193;
Update Destino set IdSap = 'DZ', nacionalidad = 'argelina', IdBandera = 12 where id = 194;
Update Destino set IdSap = 'QA', nacionalidad = 'qatarí', IdBandera = 180 where id = 195;
Update Destino set IdSap = 'US', nacionalidad = 'estadounidense', IdBandera = 75 where id = 196;
Update Destino set IdSap = 'ES', nacionalidad = 'española', IdBandera = 73 where id = 197;
Update Destino set IdSap = 'BB', nacionalidad = 'de Barbados', IdBandera = 22 where id = 198;

-- INSERTS

insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Afganistán',1,'AF','Afganistán',1);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Gland',1,'AX','Islas Gland',2);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Albania',1,'AL','Albania',3);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Andorra',1,'AD','Andorra',5);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Anguilla',1,'AI','Anguilla',7);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Antártida',1,'AQ','Antártida',8);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Antigua y Barbuda',1,'AG','Antigua y Barbuda',9);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Antillas Holandesas',1,'AN','Antillas Holandesas',10);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Armenia',1,'AM','Armenia',14);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Aruba',1,'AW','Aruba',15);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Austria',1,'AT','Austria',17);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Azerbaiyán',1,'AZ','Azerbaiyán',18);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Bahamas',1,'BS','Bahamas',19);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Bahréin',1,'BH','Bahréin',20);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Belice',1,'BZ','Belice',25);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Benin',1,'BJ','Benin',26);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Bermudas',1,'BM','Bermudas',27);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Bhután',1,'BT','Bhután',28);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Bolivia',1,'BO','Bolivia',29);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Bosnia y Herzegovina',1,'BA','Bosnia y Herzegovina',30);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Botsuana',1,'BW','Botsuana',31);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Isla Bouvet',1,'BV','Isla Bouvet',32);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Bulgaria',1,'BG','Bulgaria',35);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Burkina Faso',1,'BF','Burkina Faso',36);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Burundi',1,'BI','Burundi',37);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Caimán',1,'KY','Islas Caimán',39);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Camboya',1,'KH','Camboya',40);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('República Centroafricana',1,'CF','República Centroafricana',43);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Chad',1,'TD','Chad',44);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('República Checa',1,'CZ','República Checa',45);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Isla de Navidad',1,'CX','Isla de Navidad',49);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Ciudad del Vaticano',1,'VA','Ciudad del Vaticano',50);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Cocos',1,'CC','Islas Cocos',51);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Comoras',1,'KM','Comoras',53);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('República Democrática del Congo',1,'CD','República Democrática del Congo',54);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Cook',1,'CK','Islas Cook',56);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Croacia',1,'HR','Croacia',61);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Dominica',1,'DM','Dominica',64);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Eritrea',1,'ER','Eritrea',70);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Eslovaquia',1,'SK','Eslovaquia',71);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas ultramarinas de Estados Unidos',1,'UM','Islas ultramarinas de Estados Unidos',74);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Estonia',1,'EE','Estonia',76);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Etiopía',1,'ET','Etiopía',77);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Inglaterra',1,'GB','Inglaterra',78);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Feroe',1,'FO','Islas Feroe',79);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Finlandia',1,'FI','Finlandia',81);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Fiyi',1,'FJ','Fiyi',82);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Gabón',1,'GA','Gabón',84);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Gambia',1,'GM','Gambia',85);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Georgias del Sur y Sandwich del Sur',1,'GS','Islas Georgias del Sur y Sandwich del Sur',87);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Gibraltar',1,'GI','Gibraltar',89);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Granada',1,'GD','Granada',90);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Groenlandia',1,'GL','Groenlandia',92);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Guadalupe',1,'GP','Guadalupe',93);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Guam',1,'GU','Guam',94);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Guayana Francesa',1,'GF','Guayana Francesa',96);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Guinea Ecuatorial',1,'GQ','Guinea Ecuatorial',98);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Guinea-Bissau',1,'GW','Guinea-Bissau',99);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Guyana',1,'GY','Guyana',100);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Haití',1,'HT','Haití',101);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Heard y McDonald',1,'HM','Islas Heard y McDonald',102);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Honduras',1,'HN','Honduras',103);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Hungría',1,'HU','Hungría',105);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islandia',1,'IS','Islandia',111);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Jamaica',1,'JM','Jamaica',114);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Kazajstán',1,'KZ','Kazajstán',117);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Kirguistán',1,'KG','Kirguistán',119);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Kiribati',1,'KI','Kiribati',120);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Laos',1,'LA','Laos',122);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Lesotho',1,'LS','Lesotho',123);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Liechtenstein',1,'LI','Liechtenstein',128);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Luxemburgo',1,'LU','Luxemburgo',130);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Macao',1,'MO','Macao',131);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('ARY Macedonia',1,'MK','ARY Macedonia',132);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Malawi',1,'MW','Malawi',135);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Maldivas',1,'MV','Maldivas',136);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Malí',1,'ML','Malí',137);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Malta',1,'MT','Malta',138);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Malvinas',1,'FK','Islas Malvinas',139);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Marianas del Norte',1,'MP','Islas Marianas del Norte',140);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Marshall',1,'MH','Islas Marshall',142);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Martinica',1,'MQ','Martinica',143);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Mayotte',1,'YT','Mayotte',146);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Micronesia',1,'FM','Micronesia',148);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Moldavia',1,'MD','Moldavia',149);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Mónaco',1,'MC','Mónaco',150);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Mongolia',1,'MN','Mongolia',151);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Montserrat',1,'MS','Montserrat',152);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Nauru',1,'NR','Nauru',156);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Nepal',1,'NP','Nepal',157);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Níger',1,'NE','Níger',159);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Niue',1,'NU','Niue',161);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Isla Norfolk',1,'NF','Isla Norfolk',162);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Noruega',1,'NO','Noruega',163);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Nueva Caledonia',1,'NC','Nueva Caledonia',164);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Palau',1,'PW','Palau',169);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Palestina',1,'PS','Palestina',170);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Papúa Nueva Guinea',1,'PG','Papúa Nueva Guinea',172);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Paraguay',1,'PY','Paraguay',173);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Pitcairn',1,'PN','Islas Pitcairn',175);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Polinesia Francesa',1,'PF','Polinesia Francesa',176);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Puerto Rico',1,'PR','Puerto Rico',179);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Reunión',1,'RE','Reunión',181);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Ruanda',1,'RW','Ruanda',182);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Sahara Occidental',1,'EH','Sahara Occidental',185);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Salomón',1,'SB','Islas Salomón',186);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Samoa',1,'WS','Samoa',187);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Samoa Americana',1,'AS','Samoa Americana',188);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('San Cristóbal y Nevis',1,'KN','San Cristóbal y Nevis',189);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('San Marino',1,'SM','San Marino',190);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('San Pedro y Miquelón',1,'PM','San Pedro y Miquelón',191);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('San Vicente y las Granadinas',1,'VC','San Vicente y las Granadinas',192);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Santa Helena',1,'SH','Santa Helena',193);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Santa Lucía',1,'LC','Santa Lucía',194);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Santo Tomé y Príncipe',1,'ST','Santo Tomé y Príncipe',195);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Serbia y Montenegro',1,'CS','Serbia y Montenegro',197);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Seychelles',1,'SC','Seychelles',198);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Sierra Leona',1,'SL','Sierra Leona',199);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Singapur',1,'SG','Singapur',200);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Somalia',1,'SO','Somalia',202);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Sri Lanka',1,'LK','Sri Lanka',203);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Suazilandia',1,'SZ','Suazilandia',204);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Sudán',1,'SD','Sudán',206);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Suecia',1,'SE','Suecia',207);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Suiza',1,'CH','Suiza',208);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Surinam',1,'SR','Surinam',209);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Svalbard y Jan Mayen',1,'SJ','Svalbard y Jan Mayen',210);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Tayikistán',1,'TJ','Tayikistán',214);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Territorio Británico del Océano Índico',1,'IO','Territorio Británico del Océano Índico',215);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Territorios Australes Franceses',1,'TF','Territorios Australes Franceses',216);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Timor Oriental',1,'TL','Timor Oriental',217);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Togo',1,'TG','Togo',218);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Tokelau',1,'TK','Tokelau',219);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Tonga',1,'TO','Tonga',220);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Trinidad y Tobago',1,'TT','Trinidad y Tobago',221);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Turcas y Caicos',1,'TC','Islas Turcas y Caicos',223);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Turkmenistán',1,'TM','Turkmenistán',224);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Tuvalu',1,'TV','Tuvalu',226);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Ucrania',1,'UA','Ucrania',227);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Uruguay',1,'UY','Uruguay',229);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Uzbekistán',1,'UZ','Uzbekistán',230);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Vanuatu',1,'VU','Vanuatu',231);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Vírgenes Británicas',1,'VG','Islas Vírgenes Británicas',234);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Islas Vírgenes de los Estados Unidos',1,'VI','Islas Vírgenes de los Estados Unidos',235);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Wallis y Futuna',1,'WF','Wallis y Futuna',236);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Yibuti',1,'DJ','Yibuti',238);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Zambia',1,'ZM','Zambia',239);
insert into destino (nombre, activo, IdSap, nacionalidad, IdBandera) values ('Zimbabue',1,'ZW','Zimbabue',240);

COMMIT;