BEGIN TRAN;

Update Destino set Activo = 0 where Id = 1;

Update Destino set CodigoSap = 'ES', nacionalIdad = 'española', Bandera_Id = 73 where Id = 2;
Update Destino set CodigoSap = 'IT', nacionalIdad = 'italiana', Bandera_Id = 113 where Id = 3;
Update Destino set CodigoSap = 'PE', nacionalIdad = 'Peruana', Bandera_Id = 174 where Id = 4;
Update Destino set CodigoSap = 'GB', nacionalIdad = 'británica', Bandera_Id = 241 where Id = 5;
Update Destino set CodigoSap = 'PH', nacionalIdad = 'filipina', Bandera_Id = 80 where Id = 6;
Update Destino set CodigoSap = 'ZA', nacionalIdad = 'sudafricana', Bandera_Id = 205 where Id = 7;
Update Destino set CodigoSap = 'NL', nacionalIdad = 'holandesa', Bandera_Id = 167 where Id = 8;
Update Destino set CodigoSap = 'PL', nacionalIdad = 'polaca', Bandera_Id = 177 where Id = 9;
Update Destino set CodigoSap = 'AU', nacionalIdad = 'australiana', Bandera_Id = 16 where Id = 10;
Update Destino set CodigoSap = 'NL', nacionalIdad = 'holandesa', Bandera_Id = 167 where Id = 11;
Update Destino set CodigoSap = 'IN', nacionalIdad = 'hindú', Bandera_Id = 106 where Id = 14;
Update Destino set CodigoSap = 'TH', nacionalIdad = 'tailandesa', Bandera_Id = 211 where Id = 15;
Update Destino set CodigoSap = 'CO', nacionalIdad = 'colombiana', Bandera_Id = 52 where Id = 16;
Update Destino set CodigoSap = 'PK', nacionalIdad = 'pakistaní', Bandera_Id = 168 where Id = 17;
Update Destino set CodigoSap = 'LY', nacionalIdad = 'libia', Bandera_Id = 127 where Id = 18;
Update Destino set CodigoSap = 'TN', nacionalIdad = 'tunecina', Bandera_Id = 222 where Id = 19;
Update Destino set CodigoSap = 'DZ', nacionalIdad = 'argelina', Bandera_Id = 12 where Id = 20;
Update Destino set CodigoSap = 'JP', nacionalIdad = 'japonesa', Bandera_Id = 115 where Id = 21;
Update Destino set CodigoSap = 'CN', nacionalIdad = 'Chino', Bandera_Id = 47 where Id = 22;
Update Destino set CodigoSap = 'MA', nacionalIdad = 'marroquí', Bandera_Id = 141 where Id = 24;
Update Destino set CodigoSap = 'Id', nacionalIdad = 'indonesia', Bandera_Id = 107 where Id = 25;
Update Destino set CodigoSap = 'EG', nacionalIdad = 'egipcia', Bandera_Id = 67 where Id = 26;
Update Destino set CodigoSap = 'IE', nacionalIdad = 'irlandesa', Bandera_Id = 110 where Id = 27;
Update Destino set CodigoSap = 'TR', nacionalIdad = 'turca', Bandera_Id = 225 where Id = 28;
Update Destino set CodigoSap = 'EC', nacionalIdad = 'ecuatoriana', Bandera_Id = 66 where Id = 30;
Update Destino set CodigoSap = 'BD', nacionalIdad = 'bangladesí', Bandera_Id = 21 where Id = 31;
Update Destino set CodigoSap = 'US', nacionalIdad = 'estadounIdense', Bandera_Id = 75 where Id = 32;
Update Destino set CodigoSap = 'PT', nacionalIdad = 'portuguesa', Bandera_Id = 178 where Id = 33;
Update Destino set CodigoSap = 'BE', nacionalIdad = 'belga', Bandera_Id = 24 where Id = 34;
Update Destino set CodigoSap = 'VN', nacionalIdad = 'vietnamita', Bandera_Id = 233 where Id = 35;
Update Destino set CodigoSap = 'DZ', nacionalIdad = 'argelina', Bandera_Id = 12 where Id = 36;
Update Destino set CodigoSap = 'CY', nacionalIdad = 'chipriota', Bandera_Id = 48 where Id = 37;
Update Destino set CodigoSap = 'SY', nacionalIdad = 'siria', Bandera_Id = 201 where Id = 38;
Update Destino set CodigoSap = 'MG', nacionalIdad = 'madecasiana', Bandera_Id = 133 where Id = 39;
Update Destino set CodigoSap = 'IR', nacionalIdad = 'iraní', Bandera_Id = 108 where Id = 41;
Update Destino set CodigoSap = 'NZ', nacionalIdad = 'neozelandesa', Bandera_Id = 165 where Id = 42;
Update Destino set CodigoSap = 'NL', nacionalIdad = 'holandesa', Bandera_Id = 167 where Id = 43;
Update Destino set CodigoSap = 'KP', nacionalIdad = 'coreana', Bandera_Id = 57 where Id = 44;
Update Destino set CodigoSap = 'CL', nacionalIdad = 'chilena', Bandera_Id = 46 where Id = 46;
Update Destino set CodigoSap = 'DE', nacionalIdad = 'alemana', Bandera_Id = 4 where Id = 47;
Update Destino set CodigoSap = 'MY', nacionalIdad = 'malaya', Bandera_Id = 134 where Id = 48;
Update Destino set CodigoSap = 'LB', nacionalIdad = 'libanesa', Bandera_Id = 125 where Id = 49;
Update Destino set CodigoSap = 'FR', nacionalIdad = 'francesa', Bandera_Id = 83 where Id = 50;
Update Destino set CodigoSap = 'DK', nacionalIdad = 'Danesa', Bandera_Id = 63 where Id = 51;

Update Destino set Activo = 0 where Id = 54;

Update Destino set CodigoSap = 'PL', nacionalIdad = 'polaca', Bandera_Id = 177 where Id = 55;
Update Destino set CodigoSap = 'PA', nacionalIdad = 'panameña', Bandera_Id = 171 where Id = 57;
Update Destino set CodigoSap = 'GT', nacionalIdad = 'guatemalteca', Bandera_Id = 95 where Id = 60;
Update Destino set CodigoSap = 'DO', nacionalIdad = 'dominicana', Bandera_Id = 65 where Id = 61;
Update Destino set CodigoSap = 'KR', nacionalIdad = 'coreana', Bandera_Id = 58 where Id = 64;
Update Destino set CodigoSap = 'RU', nacionalIdad = 'rusa', Bandera_Id = 184 where Id = 66;
Update Destino set CodigoSap = 'MZ', nacionalIdad = 'mozambiqueña', Bandera_Id = 153 where Id = 67;
Update Destino set CodigoSap = 'BR', nacionalIdad = 'brasileña', Bandera_Id = 33 where Id = 68;
Update Destino set CodigoSap = 'YE', nacionalIdad = 'yemenita', Bandera_Id = 237 where Id = 69;
Update Destino set CodigoSap = 'GR', nacionalIdad = 'griega', Bandera_Id = 91 where Id = 70;
Update Destino set CodigoSap = 'MA', nacionalIdad = 'marroquí', Bandera_Id = 141 where Id = 71;
Update Destino set CodigoSap = 'OM', nacionalIdad = 'omaní', Bandera_Id = 166 where Id = 73;
Update Destino set CodigoSap = 'AE', nacionalIdad = 'árabe', Bandera_Id = 69 where Id = 75;
Update Destino set CodigoSap = 'SA', nacionalIdad = 'saudí', Bandera_Id = 11 where Id = 76;
Update Destino set CodigoSap = 'IT', nacionalIdad = 'italiana', Bandera_Id = 113 where Id = 77;
Update Destino set CodigoSap = 'TZ', nacionalIdad = 'tanzana', Bandera_Id = 213 where Id = 78;
Update Destino set CodigoSap = 'KE', nacionalIdad = 'keniana', Bandera_Id = 118 where Id = 79;
Update Destino set CodigoSap = 'US', nacionalIdad = 'estadounIdense', Bandera_Id = 75 where Id = 80;
Update Destino set CodigoSap = 'IT', nacionalIdad = 'italiana', Bandera_Id = 113 where Id = 81;
Update Destino set CodigoSap = 'SI', nacionalIdad = 'eslovenia', Bandera_Id = 72 where Id = 82;
Update Destino set CodigoSap = 'RO', nacionalIdad = 'rumana', Bandera_Id = 183 where Id = 83;
Update Destino set CodigoSap = 'CU', nacionalIdad = 'cubana', Bandera_Id = 62 where Id = 84;

Update Destino set Activo = 0 where Id = 86;

--Update Destino set CodigoSap = 'LD', nacionalIdad = 'Latviana', Bandera_Id = ALTA BANDERA where Id = 89;
Update Destino set CodigoSap = 'SY', nacionalIdad = 'siria', Bandera_Id = 201 where Id = 91;
Update Destino set CodigoSap = 'GB', nacionalIdad = 'británica', Bandera_Id = 241 where Id = 92;
Update Destino set CodigoSap = 'LT', nacionalIdad = 'lituana', Bandera_Id = 129 where Id = 94;
Update Destino set CodigoSap = 'CR', nacionalIdad = 'costarricense', Bandera_Id = 60 where Id = 95;
Update Destino set CodigoSap = 'VN', nacionalIdad = 'vietnamita', Bandera_Id = 233 where Id = 97;
Update Destino set CodigoSap = 'VE', nacionalIdad = 'venezolana', Bandera_Id = 232 where Id = 98;
Update Destino set CodigoSap = 'SA', nacionalIdad = 'saudí', Bandera_Id = 11 where Id = 99;
Update Destino set CodigoSap = 'AR', nacionalIdad = 'argentina', Bandera_Id = 13 where Id = 100;
Update Destino set CodigoSap = 'SN', nacionalIdad = 'senegalesa', Bandera_Id = 196 where Id = 102;
Update Destino set CodigoSap = 'AR', nacionalIdad = 'argentina', Bandera_Id = 13 where Id = 103;
Update Destino set CodigoSap = 'CI', nacionalIdad = 'Marfilense', Bandera_Id = 59 where Id = 104;
Update Destino set CodigoSap = 'BN', nacionalIdad = 'de Brunei', Bandera_Id = 34 where Id = 106;
Update Destino set CodigoSap = 'CG', nacionalIdad = 'Congoleña', Bandera_Id = 55 where Id = 109;
Update Destino set CodigoSap = 'NA', nacionalIdad = 'namibia', Bandera_Id = 155 where Id = 110;
Update Destino set CodigoSap = 'MU', nacionalIdad = 'mauriciense', Bandera_Id = 144 where Id = 113;
Update Destino set CodigoSap = 'MU', nacionalIdad = 'mauriciense', Bandera_Id = 144 where Id = 114;
Update Destino set CodigoSap = 'IL', nacionalIdad = 'israelí', Bandera_Id = 112 where Id = 116;
Update Destino set CodigoSap = 'HK', nacionalIdad = 'china', Bandera_Id = 104 where Id = 117;
Update Destino set CodigoSap = 'AE', nacionalIdad = 'árabe', Bandera_Id = 69 where Id = 119;
Update Destino set CodigoSap = 'BY', nacionalIdad = 'bielorrusa', Bandera_Id = 23 where Id = 121;
Update Destino set CodigoSap = 'MR', nacionalIdad = 'mauritana', Bandera_Id = 145 where Id = 122;
Update Destino set CodigoSap = 'GH', nacionalIdad = 'ghanesa', Bandera_Id = 88 where Id = 123;
Update Destino set CodigoSap = 'CV', nacionalIdad = 'caboverdiana', Bandera_Id = 38 where Id = 124;
Update Destino set CodigoSap = 'CM', nacionalIdad = 'camerunesa', Bandera_Id = 41 where Id = 126;

Update Destino set Activo = 0 where Id = 128;
Update Destino set Activo = 0 where Id = 129;
Update Destino set Activo = 0 where Id = 130;
Update Destino set Activo = 0 where Id = 131;
Update Destino set Activo = 0 where Id = 132;
Update Destino set Activo = 0 where Id = 133;
Update Destino set Activo = 0 where Id = 134;
Update Destino set Activo = 0 where Id = 136;

Update Destino set CodigoSap = 'LV', nacionalIdad = 'letona', Bandera_Id = 124 where Id = 139;

Update Destino set Activo = 0 where Id = 140;
Update Destino set Activo = 0 where Id = 141;

Update Destino set CodigoSap = 'TW', nacionalIdad = 'taiwanesa', Bandera_Id = 212 where Id = 142;
Update Destino set CodigoSap = 'JO', nacionalIdad = 'jordana', Bandera_Id = 116 where Id = 143;

Update Destino set Activo = 0 where Id = 144;
Update Destino set Activo = 0 where Id = 146;
Update Destino set Activo = 0 where Id = 147;
Update Destino set Activo = 0 where Id = 150;
Update Destino set Activo = 0 where Id = 151;
Update Destino set Activo = 0 where Id = 152;
Update Destino set Activo = 0 where Id = 153;
Update Destino set Activo = 0 where Id = 154;
Update Destino set Activo = 0 where Id = 155;
Update Destino set Activo = 0 where Id = 156;
Update Destino set Activo = 0 where Id = 157;

Update Destino set CodigoSap = 'NG', nacionalIdad = 'nigeriana', Bandera_Id = 160 where Id = 158;
Update Destino set CodigoSap = 'UG', nacionalIdad = 'ugandesa', Bandera_Id = 228 where Id = 159;

Update Destino set Activo = 0 where Id = 160;
Update Destino set Activo = 0 where Id = 163;

Update Destino set CodigoSap = 'GT', nacionalIdad = 'guatemalteca', Bandera_Id = 95 where Id = 164;

Update Destino set Activo = 0 where Id = 165;

Update Destino set CodigoSap = 'IN', nacionalIdad = 'hindú', Bandera_Id = 106 where Id = 166;
Update Destino set CodigoSap = 'IQ', nacionalIdad = 'iraquí', Bandera_Id = 109 where Id = 168;
Update Destino set CodigoSap = 'EG', nacionalIdad = 'egipcia', Bandera_Id = 67 where Id = 169;
Update Destino set CodigoSap = 'NL', nacionalIdad = 'holandesa', Bandera_Id = 167 where Id = 170;
Update Destino set CodigoSap = 'MU', nacionalIdad = 'mauriciense', Bandera_Id = 144 where Id = 171;
Update Destino set CodigoSap = 'GN', nacionalIdad = 'guineana', Bandera_Id = 97 where Id = 172;
Update Destino set CodigoSap = 'AO', nacionalIdad = 'angolana', Bandera_Id = 6 where Id = 173;
Update Destino set CodigoSap = 'IQ', nacionalIdad = 'iraquí', Bandera_Id = 109 where Id = 174;
Update Destino set CodigoSap = 'AE', nacionalIdad = 'árabe', Bandera_Id = 69 where Id = 175;
Update Destino set CodigoSap = 'DO', nacionalIdad = 'dominicana', Bandera_Id = 65 where Id = 176;
Update Destino set CodigoSap = 'KR', nacionalIdad = 'coreana', Bandera_Id = 58 where Id = 177;
Update Destino set CodigoSap = 'DZ', nacionalIdad = 'argelina', Bandera_Id = 12 where Id = 178;
Update Destino set CodigoSap = 'KE', nacionalIdad = 'keniana', Bandera_Id = 118 where Id = 179;
Update Destino set CodigoSap = 'MX', nacionalIdad = 'mexicana', Bandera_Id = 147 where Id = 180;
Update Destino set CodigoSap = 'KW', nacionalIdad = 'kuwaití', Bandera_Id = 121 where Id = 181;
Update Destino set CodigoSap = 'ZA', nacionalIdad = 'sudafricana', Bandera_Id = 205 where Id = 182;
Update Destino set CodigoSap = 'MM', nacionalIdad = 'Myanmar', Bandera_Id = 154 where Id = 183;

Update Destino set Activo = 0 where Id = 184;

Update Destino set CodigoSap = 'VN', nacionalIdad = 'vietnamita', Bandera_Id = 233 where Id = 185;
Update Destino set CodigoSap = 'GE', nacionalIdad = 'georgiana', Bandera_Id = 86 where Id = 186;
Update Destino set CodigoSap = 'LR', nacionalIdad = 'liberiana', Bandera_Id = 126 where Id = 187;
Update Destino set CodigoSap = 'CA', nacionalIdad = 'canadiense', Bandera_Id = 42 where Id = 188;

Update Destino set CodigoSap = 'ZPE', nacionalIdad = '', Bandera_Id = NULL where Id = 189;
Update Destino set CodigoSap = 'ZPE', nacionalIdad = '', Bandera_Id = NULL where Id = 190;
Update Destino set CodigoSap = 'ZPE', nacionalIdad = '', Bandera_Id = NULL where Id = 191;

Update Destino set CodigoSap = 'SV', nacionalIdad = 'salvadoreña', Bandera_Id = 68 where Id = 192;
Update Destino set CodigoSap = 'NI', nacionalIdad = 'nicaragüense', Bandera_Id = 158 where Id = 193;
Update Destino set CodigoSap = 'DZ', nacionalIdad = 'argelina', Bandera_Id = 12 where Id = 194;
Update Destino set CodigoSap = 'QA', nacionalIdad = 'qatarí', Bandera_Id = 180 where Id = 195;
Update Destino set CodigoSap = 'US', nacionalIdad = 'estadounIdense', Bandera_Id = 75 where Id = 196;
Update Destino set CodigoSap = 'ES', nacionalIdad = 'española', Bandera_Id = 73 where Id = 197;
Update Destino set CodigoSap = 'BB', nacionalIdad = 'de Barbados', Bandera_Id = 22 where Id = 198;

-- INSERTS

SET IDENTITY_INSERT Destino ON;

insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Afganistán',1,'AF','Afganistán',1);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Gland',1,'AX','Islas Gland',2);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Albania',1,'AL','Albania',3);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Andorra',1,'AD','Andorra',5);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Anguilla',1,'AI','Anguilla',7);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('AntártIda',1,'AQ','AntártIda',8);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Antigua y Barbuda',1,'AG','Antigua y Barbuda',9);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Antillas Holandesas',1,'AN','Antillas Holandesas',10);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Armenia',1,'AM','Armenia',14);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Aruba',1,'AW','Aruba',15);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Austria',1,'AT','Austria',17);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Azerbaiyán',1,'AZ','Azerbaiyán',18);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Bahamas',1,'BS','Bahamas',19);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Bahréin',1,'BH','Bahréin',20);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Belice',1,'BZ','Belice',25);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Benin',1,'BJ','Benin',26);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Bermudas',1,'BM','Bermudas',27);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Bhután',1,'BT','Bhután',28);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Bolivia',1,'BO','Bolivia',29);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Bosnia y Herzegovina',1,'BA','Bosnia y Herzegovina',30);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Botsuana',1,'BW','Botsuana',31);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Isla Bouvet',1,'BV','Isla Bouvet',32);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Bulgaria',1,'BG','Bulgaria',35);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Burkina Faso',1,'BF','Burkina Faso',36);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Burundi',1,'BI','Burundi',37);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Caimán',1,'KY','Islas Caimán',39);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Camboya',1,'KH','Camboya',40);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('República Centroafricana',1,'CF','República Centroafricana',43);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Chad',1,'TD','Chad',44);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('República Checa',1,'CZ','República Checa',45);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Isla de NavIdad',1,'CX','Isla de NavIdad',49);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Ciudad del Vaticano',1,'VA','Ciudad del Vaticano',50);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Cocos',1,'CC','Islas Cocos',51);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Comoras',1,'KM','Comoras',53);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('República Democrática del Congo',1,'CD','República Democrática del Congo',54);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Cook',1,'CK','Islas Cook',56);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Croacia',1,'HR','Croacia',61);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Dominica',1,'DM','Dominica',64);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Eritrea',1,'ER','Eritrea',70);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Eslovaquia',1,'SK','Eslovaquia',71);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas ultramarinas de Estados UnIdos',1,'UM','Islas ultramarinas de Estados UnIdos',74);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Estonia',1,'EE','Estonia',76);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Etiopía',1,'ET','Etiopía',77);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Inglaterra',1,'GB','Inglaterra',78);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Feroe',1,'FO','Islas Feroe',79);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Finlandia',1,'FI','Finlandia',81);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Fiyi',1,'FJ','Fiyi',82);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Gabón',1,'GA','Gabón',84);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Gambia',1,'GM','Gambia',85);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Georgias del Sur y Sandwich del Sur',1,'GS','Islas Georgias del Sur y Sandwich del Sur',87);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Gibraltar',1,'GI','Gibraltar',89);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Granada',1,'GD','Granada',90);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Groenlandia',1,'GL','Groenlandia',92);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Guadalupe',1,'GP','Guadalupe',93);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Guam',1,'GU','Guam',94);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Guayana Francesa',1,'GF','Guayana Francesa',96);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Guinea Ecuatorial',1,'GQ','Guinea Ecuatorial',98);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Guinea-Bissau',1,'GW','Guinea-Bissau',99);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Guyana',1,'GY','Guyana',100);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Haití',1,'HT','Haití',101);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Heard y McDonald',1,'HM','Islas Heard y McDonald',102);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Honduras',1,'HN','Honduras',103);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Hungría',1,'HU','Hungría',105);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islandia',1,'IS','Islandia',111);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Jamaica',1,'JM','Jamaica',114);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Kazajstán',1,'KZ','Kazajstán',117);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Kirguistán',1,'KG','Kirguistán',119);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Kiribati',1,'KI','Kiribati',120);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Laos',1,'LA','Laos',122);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Lesotho',1,'LS','Lesotho',123);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Liechtenstein',1,'LI','Liechtenstein',128);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Luxemburgo',1,'LU','Luxemburgo',130);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Macao',1,'MO','Macao',131);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('ARY Macedonia',1,'MK','ARY Macedonia',132);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Malawi',1,'MW','Malawi',135);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Maldivas',1,'MV','Maldivas',136);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Malí',1,'ML','Malí',137);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Malta',1,'MT','Malta',138);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Malvinas',1,'FK','Islas Malvinas',139);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Marianas del Norte',1,'MP','Islas Marianas del Norte',140);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Marshall',1,'MH','Islas Marshall',142);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Martinica',1,'MQ','Martinica',143);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Mayotte',1,'YT','Mayotte',146);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Micronesia',1,'FM','Micronesia',148);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Moldavia',1,'MD','Moldavia',149);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Mónaco',1,'MC','Mónaco',150);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Mongolia',1,'MN','Mongolia',151);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Montserrat',1,'MS','Montserrat',152);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Nauru',1,'NR','Nauru',156);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Nepal',1,'NP','Nepal',157);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Níger',1,'NE','Níger',159);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Niue',1,'NU','Niue',161);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Isla Norfolk',1,'NF','Isla Norfolk',162);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Noruega',1,'NO','Noruega',163);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Nueva Caledonia',1,'NC','Nueva Caledonia',164);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Palau',1,'PW','Palau',169);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Palestina',1,'PS','Palestina',170);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Papúa Nueva Guinea',1,'PG','Papúa Nueva Guinea',172);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Paraguay',1,'PY','Paraguay',173);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Pitcairn',1,'PN','Islas Pitcairn',175);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Polinesia Francesa',1,'PF','Polinesia Francesa',176);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Puerto Rico',1,'PR','Puerto Rico',179);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Reunión',1,'RE','Reunión',181);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Ruanda',1,'RW','Ruanda',182);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Sahara OccIdental',1,'EH','Sahara OccIdental',185);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Salomón',1,'SB','Islas Salomón',186);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Samoa',1,'WS','Samoa',187);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Samoa Americana',1,'AS','Samoa Americana',188);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('San Cristóbal y Nevis',1,'KN','San Cristóbal y Nevis',189);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('San Marino',1,'SM','San Marino',190);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('San Pedro y Miquelón',1,'PM','San Pedro y Miquelón',191);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('San Vicente y las Granadinas',1,'VC','San Vicente y las Granadinas',192);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Santa Helena',1,'SH','Santa Helena',193);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Santa Lucía',1,'LC','Santa Lucía',194);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Santo Tomé y Príncipe',1,'ST','Santo Tomé y Príncipe',195);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Serbia y Montenegro',1,'CS','Serbia y Montenegro',197);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Seychelles',1,'SC','Seychelles',198);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Sierra Leona',1,'SL','Sierra Leona',199);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Singapur',1,'SG','Singapur',200);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Somalia',1,'SO','Somalia',202);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Sri Lanka',1,'LK','Sri Lanka',203);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Suazilandia',1,'SZ','Suazilandia',204);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Sudán',1,'SD','Sudán',206);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Suecia',1,'SE','Suecia',207);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Suiza',1,'CH','Suiza',208);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Surinam',1,'SR','Surinam',209);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Svalbard y Jan Mayen',1,'SJ','Svalbard y Jan Mayen',210);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Tayikistán',1,'TJ','Tayikistán',214);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Territorio Británico del Océano Índico',1,'IO','Territorio Británico del Océano Índico',215);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Territorios Australes Franceses',1,'TF','Territorios Australes Franceses',216);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Timor Oriental',1,'TL','Timor Oriental',217);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Togo',1,'TG','Togo',218);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Tokelau',1,'TK','Tokelau',219);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Tonga',1,'TO','Tonga',220);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('TrinIdad y Tobago',1,'TT','TrinIdad y Tobago',221);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Turcas y Caicos',1,'TC','Islas Turcas y Caicos',223);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Turkmenistán',1,'TM','Turkmenistán',224);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Tuvalu',1,'TV','Tuvalu',226);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Ucrania',1,'UA','Ucrania',227);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Uruguay',1,'UY','Uruguay',229);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Uzbekistán',1,'UZ','Uzbekistán',230);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Vanuatu',1,'VU','Vanuatu',231);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Vírgenes Británicas',1,'VG','Islas Vírgenes Británicas',234);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Islas Vírgenes de los Estados UnIdos',1,'VI','Islas Vírgenes de los Estados UnIdos',235);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Wallis y Futuna',1,'WF','Wallis y Futuna',236);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Yibuti',1,'DJ','Yibuti',238);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Zambia',1,'ZM','Zambia',239);
insert into destino (nombre, activo, CodigoSap, nacionalIdad, Bandera_Id) values ('Zimbabue',1,'ZW','Zimbabue',240);

SET IDENTITY_INSERT Destino OFF

COMMIT;