-- Zonas --

IF NOT EXISTS (select 1 from Zona where Descripcion = '25 DE MAYO') BEGIN insert into Zona values ('25 DE MAYO') END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'ANGACO') BEGIN insert into Zona values ('ANGACO')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'CAUCETE') BEGIN insert into Zona values ('CAUCETE')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'EL MARCADO') BEGIN insert into Zona values ('EL MARCADO')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'GUAYMALLEN') BEGIN insert into Zona values ('GUAYMALLEN')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'JUNIN') BEGIN insert into Zona values ('JUNIN')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'LA PAZ') BEGIN insert into Zona values ('LA PAZ')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'LAVALLE') BEGIN insert into Zona values ('LAVALLE')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'LUJAN DE CUYO') BEGIN insert into Zona values ('LUJAN DE CUYO')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'MAIPU') BEGIN insert into Zona values ('MAIPU')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'RIVADAVIA') BEGIN insert into Zona values ('RIVADAVIA')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'SAN CARLOS') BEGIN insert into Zona values ('SAN CARLOS')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'SAN MARTIN') BEGIN insert into Zona values ('SAN MARTIN')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'SANTA ROSA') BEGIN insert into Zona values ('SANTA ROSA')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'SARMIENTO') BEGIN insert into Zona values ('SARMIENTO')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'TUNUYAN') BEGIN insert into Zona values ('TUNUYAN')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'TUPUNGATO') BEGIN insert into Zona values ('TUPUNGATO')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'ULLUM') BEGIN insert into Zona values ('ULLUM')END;
IF NOT EXISTS (select 1 from Zona where Descripcion = 'ZONDA') BEGIN insert into Zona values ('ZONDA')END;

-- SubZonas --

IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LA CHIMBERA') BEGIN insert into SubZona values ((select id from zona where Descripcion='25 DE MAYO'),'LA CHIMBERA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LAS CASUARINAS') BEGIN insert into SubZona values ((select id from zona where Descripcion='25 DE MAYO'),'LAS CASUARINAS')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'POZO SALADO') BEGIN insert into SubZona values ((select id from zona where Descripcion='25 DE MAYO'),'POZO SALADO')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'RINCON DE TUPELI') BEGIN insert into SubZona values ((select id from zona where Descripcion='25 DE MAYO'),'RINCON DE TUPELI')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'VILLA BORJAS-LA CHIMBERA') BEGIN insert into SubZona values ((select id from zona where Descripcion='25 DE MAYO'),'VILLA BORJAS-LA CHIMBERA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'PLUMERILLO') BEGIN insert into SubZona values ((select id from zona where Descripcion='ANGACO'),'PLUMERILLO')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'RINCON') BEGIN insert into SubZona values ((select id from zona where Descripcion='CAUCETE'),'RINCON')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = '12 DE OCTUBRE') BEGIN insert into SubZona values ((select id from zona where Descripcion='EL MARCADO'),'12 DE OCTUBRE')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'COLONIA SEGOVIA') BEGIN insert into SubZona values ((select id from zona where Descripcion='GUAYMALLEN'),'COLONIA SEGOVIA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'JUNIN') BEGIN insert into SubZona values ((select id from zona where Descripcion='JUNIN'),'JUNIN')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LA COLONIA') BEGIN insert into SubZona values ((select id from zona where Descripcion='JUNIN'),'LA COLONIA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'MEDRANO') BEGIN insert into SubZona values ((select id from zona where Descripcion='JUNIN'),'MEDRANO')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'PHILLIPS') BEGIN insert into SubZona values ((select id from zona where Descripcion='JUNIN'),'PHILLIPS')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'VILLA NUEVA') BEGIN insert into SubZona values ((select id from zona where Descripcion='LA PAZ'),'VILLA NUEVA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'COSTA DE ARAUJO') BEGIN insert into SubZona values ((select id from zona where Descripcion='LAVALLE'),'COSTA DE ARAUJO')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'EL VERGEL') BEGIN insert into SubZona values ((select id from zona where Descripcion='LAVALLE'),'EL VERGEL')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'JOCOLI') BEGIN insert into SubZona values ((select id from zona where Descripcion='LAVALLE'),'JOCOLI')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LA HOLANDA') BEGIN insert into SubZona values ((select id from zona where Descripcion='LAVALLE'),'LA HOLANDA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'AGRELO') BEGIN insert into SubZona values ((select id from zona where Descripcion='LUJAN DE CUYO'),'AGRELO')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'CARRODILLA') BEGIN insert into SubZona values ((select id from zona where Descripcion='LUJAN DE CUYO'),'CARRODILLA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'CHACRAS DE CORIA') BEGIN insert into SubZona values ((select id from zona where Descripcion='LUJAN DE CUYO'),'CHACRAS DE CORIA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'EL CARRIZAL') BEGIN insert into SubZona values ((select id from zona where Descripcion='LUJAN DE CUYO'),'EL CARRIZAL')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LUJAN DE CUYO') BEGIN insert into SubZona values ((select id from zona where Descripcion='LUJAN DE CUYO'),'LUJAN DE CUYO')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'PERDRIEL') BEGIN insert into SubZona values ((select id from zona where Descripcion='LUJAN DE CUYO'),'PERDRIEL')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'UGARTECHE') BEGIN insert into SubZona values ((select id from zona where Descripcion='LUJAN DE CUYO'),'UGARTECHE')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'VISTALBA') BEGIN insert into SubZona values ((select id from zona where Descripcion='LUJAN DE CUYO'),'VISTALBA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'BARRANCAS') BEGIN insert into SubZona values ((select id from zona where Descripcion='MAIPU'),'BARRANCAS')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'COQUIMBITO') BEGIN insert into SubZona values ((select id from zona where Descripcion='MAIPU'),'COQUIMBITO')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'FRAY LUIS BELTRAN') BEGIN insert into SubZona values ((select id from zona where Descripcion='MAIPU'),'FRAY LUIS BELTRAN')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LOS ALAMOS') BEGIN insert into SubZona values ((select id from zona where Descripcion='MAIPU'),'LOS ALAMOS')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'RUSSELL') BEGIN insert into SubZona values ((select id from zona where Descripcion='MAIPU'),'RUSSELL')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'ANDRADE') BEGIN insert into SubZona values ((select id from zona where Descripcion='RIVADAVIA'),'ANDRADE')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'CAMPAMENTOS') BEGIN insert into SubZona values ((select id from zona where Descripcion='RIVADAVIA'),'CAMPAMENTOS')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LOS ARBOLES') BEGIN insert into SubZona values ((select id from zona where Descripcion='RIVADAVIA'),'LOS ARBOLES')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'MEDRANO') BEGIN insert into SubZona values ((select id from zona where Descripcion='RIVADAVIA'),'MEDRANO')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'RIVADAVIA') BEGIN insert into SubZona values ((select id from zona where Descripcion='RIVADAVIA'),'RIVADAVIA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'EUGENIO BUSTOS') BEGIN insert into SubZona values ((select id from zona where Descripcion='SAN CARLOS'),'EUGENIO BUSTOS')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LA CONSULTA') BEGIN insert into SubZona values ((select id from zona where Descripcion='SAN CARLOS'),'LA CONSULTA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'CHIVILCOY') BEGIN insert into SubZona values ((select id from zona where Descripcion='SAN MARTIN'),'CHIVILCOY')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'DIVISADERO') BEGIN insert into SubZona values ((select id from zona where Descripcion='SAN MARTIN'),'DIVISADERO')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'DOS ACEQUIAS') BEGIN insert into SubZona values ((select id from zona where Descripcion='SAN MARTIN'),'DOS ACEQUIAS')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'MONTECASEROS') BEGIN insert into SubZona values ((select id from zona where Descripcion='SAN MARTIN'),'MONTECASEROS')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'TRES PORTEÑAS') BEGIN insert into SubZona values ((select id from zona where Descripcion='SAN MARTIN'),'TRES PORTEÑAS')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = '12 DE OCTUBRE') BEGIN insert into SubZona values ((select id from zona where Descripcion='SANTA ROSA'),'12 DE OCTUBRE')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'BARRIO DOCE DE OCTUBRE') BEGIN insert into SubZona values ((select id from zona where Descripcion='SANTA ROSA'),'BARRIO DOCE DE OCTUBRE')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'EL DIVISADERO') BEGIN insert into SubZona values ((select id from zona where Descripcion='SANTA ROSA'),'EL DIVISADERO')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'SANTA ROSA') BEGIN insert into SubZona values ((select id from zona where Descripcion='SANTA ROSA'),'SANTA ROSA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'COCHAGUAL') BEGIN insert into SubZona values ((select id from zona where Descripcion='SARMIENTO'),'COCHAGUAL')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'PEDERNAL') BEGIN insert into SubZona values ((select id from zona where Descripcion='SARMIENTO'),'PEDERNAL')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'VILLA MEDIA AGUA') BEGIN insert into SubZona values ((select id from zona where Descripcion='SARMIENTO'),'VILLA MEDIA AGUA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'EL TOPON') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUNUYAN'),'EL TOPON')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'EL TOTORAL') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUNUYAN'),'EL TOTORAL')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LOS ARBOLES') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUNUYAN'),'LOS ARBOLES')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LOS CHACAYES') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUNUYAN'),'LOS CHACAYES')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'LOS SAUCES') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUNUYAN'),'LOS SAUCES')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'TUNUYAN') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUNUYAN'),'TUNUYAN')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'VILLA SECA') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUNUYAN'),'VILLA SECA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'VISTA FLORES') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUNUYAN'),'VISTA FLORES')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'CAMPO VIDAL') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUPUNGATO'),'CAMPO VIDAL')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'CORDON DEL PLATA') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUPUNGATO'),'CORDON DEL PLATA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'EL PERAL') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUPUNGATO'),'EL PERAL')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'GUALTALLARY') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUPUNGATO'),'GUALTALLARY')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'SAN JOSE') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUPUNGATO'),'SAN JOSE')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'VILLA BASTIA') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUPUNGATO'),'VILLA BASTIA')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'ZAMPAL') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUPUNGATO'),'ZAMPAL')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'A DETERMINAR') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUPUNGATO'),'A DETERMINAR')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'SIN ASIGNAR') BEGIN insert into SubZona values ((select id from zona where Descripcion='TUPUNGATO'),'SIN ASIGNAR')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'ULLUM') BEGIN insert into SubZona values ((select id from zona where Descripcion='ULLUM'),'ULLUM')END;
IF NOT EXISTS (select 1 from SubZona where Descripcion = 'VILLA ZONDA') BEGIN insert into SubZona values ((select id from zona where Descripcion='ZONDA'),'VILLA ZONDA')END;
