CREATE TABLE [dbo].[ATAPuerto] (
    [Id]     INT           IDENTITY (1, 1) NOT NULL,
    [Nombre] NVARCHAR (60) NOT NULL,
    CONSTRAINT [PK_dbo.ATAPuerto] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UK_ATAPuerto_Nombre] UNIQUE NONCLUSTERED ([Nombre] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);


GO
