CREATE TABLE [dbo].[Calle] (
    [Id]                               INT             IDENTITY (1, 1) NOT NULL,
    [Nombre]                           NVARCHAR (35)   NOT NULL,
    [Codigo]                           NCHAR (5)       NOT NULL,
    [CentroId]                         INT             NOT NULL,
    [TipoCalle]                        INT             DEFAULT ((0)) NOT NULL,
    [CantidadDeCamiones]               INT             DEFAULT ((0)) NOT NULL,
    [Bloqueada]                        BIT             DEFAULT ((0)) NOT NULL,
    [Deshabilitada]                    BIT             DEFAULT ((0)) NOT NULL,
    [CalleCalado_Id]                   INT             NULL,
    [Automatica]                       BIT             DEFAULT ((0)) NOT NULL,
    [Material_Id]                      INT             NULL,
    [FechaLLamada]                     DATETIME2 (7)   NULL,
    [TipoCalidad]                      INT             DEFAULT ((0)) NOT NULL,
    [HidraulicaAsignada]               INT             DEFAULT ((1)) NULL,
    [CaracteristicaDeCalidad_Id]       INT             NULL,
    [RangoCaracteristicaCalidadMinimo] DECIMAL (18, 2) NULL,
    [RangoCaracteristicaCalidadMaximo] DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_dbo.Calle] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_dbo.Calle_dbo.Calle_CalleCalado_Id] FOREIGN KEY ([CalleCalado_Id]) REFERENCES [dbo].[Calle] ([Id]),
    CONSTRAINT [FK_dbo.Calle_dbo.Calle_CaracteristicaDeCalidad_Id] FOREIGN KEY ([CaracteristicaDeCalidad_Id]) REFERENCES [dbo].[CaracteristicaDeCalidad] ([Id]),
    CONSTRAINT [FK_dbo.Calle_dbo.Calle_Centro_Id] FOREIGN KEY ([CentroId]) REFERENCES [dbo].[Centro] ([Id]),
    CONSTRAINT [FK_dbo.Calle_dbo.Calle_Material_Id] FOREIGN KEY ([Material_Id]) REFERENCES [dbo].[Material] ([Id])
);

