CREATE TABLE [dbo].[CartaPorte]
(
	[Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY, 
    [NroCartaPorte] VARCHAR(12) NOT NULL, 
    [FechaCP] DATE NOT NULL, 
    [FechaVto] DATE NOT NULL, 
    [FechaEmision] DATETIME NOT NULL,
    [TipoVehiculo] INT NOT NULL, 
    [OrigenVehiculo] INT NOT NULL, 
    [CTG] VARCHAR(20) NULL, 
    [TipoComercial_Id] INT NOT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.TipoComercial_TipoComercial_Id] FOREIGN KEY ([TipoComercial_Id]) REFERENCES [dbo].[TipoComercial] ([Id]),
    [Material_Id] INT NOT NULL,
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Material_Material_Id] FOREIGN KEY ([Material_Id]) REFERENCES [dbo].[Material] ([Id]), 
    [Procedencia_Id] INT NOT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Localidad_Localidad_Id] FOREIGN KEY ([Procedencia_Id]) REFERENCES [dbo].[Localidad] ([Id]),
    [TitularCartaPorte_Id] INT NOT NULL, 
    [Intermediario_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Intermediario_Proveedor_Id] FOREIGN KEY ([Intermediario_Id]) REFERENCES [dbo].[Proveedor] ([Id]), 
    [RtteComercial_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.RtteComercial_Proveedor_Id] FOREIGN KEY ([RtteComercial_Id]) REFERENCES [dbo].[Proveedor] ([Id]), 
    [Corredor_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Corredor_Proveedor_Id] FOREIGN KEY ([Corredor_Id]) REFERENCES [dbo].[Proveedor] ([Id]), 
    [Entregador_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Entregador_Entregador_Id] FOREIGN KEY ([Entregador_Id]) REFERENCES [dbo].[Entregador] ([Id]), 
    [AgenteCompras_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.AgenteCompras_Proveedor_Id] FOREIGN KEY ([AgenteCompras_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    [Destinatario_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Destinatario_Proveedor_Id] FOREIGN KEY ([Destinatario_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    [DestinatarioCliente_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Destinatario_Cliente_Id] FOREIGN KEY ([DestinatarioCliente_Id]) REFERENCES [dbo].[Cliente] ([Id]),
    [CentroDestino_Id] INT NULL,
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Centro_Centro_Id] FOREIGN KEY ([CentroDestino_Id]) REFERENCES [dbo].[Centro] ([Id]),
    [ClienteDestino_Id] INT NULL,
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Cliente_Cliente_Id] FOREIGN KEY ([ClienteDestino_Id]) REFERENCES [dbo].[Cliente] ([Id]), 
    [Transportista_Id] INT NULL,
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Transportista_Transportista_Id] FOREIGN KEY ([Transportista_Id]) REFERENCES [dbo].[Transportista] ([Id]),   
    [KmRecorrer] INT NOT NULL, 
    [TarifaTonelada] DECIMAL(18, 2) NULL, 
    [Variedad] VARCHAR(15) NULL, 
    [CodEstab] VARCHAR(6) NULL, 
    [FletePagado] BIT NULL, 
    [FleteAPagar] BIT NULL, 
    [Aparceria] BIT NULL, 
    [Desvio] BIT NULL, 
    [AcuerdoMarco] VARCHAR(15) NULL, 
    [Cosecha] VARCHAR(5) NOT NULL, 
    [Caratula] INT NULL, 
    [CEE] VARCHAR(14) NOT NULL, 
	[CodigoAnexo] VARCHAR(10) NULL, 
    [Chofer_Id] INT NOT NULL,
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Chofer_Chofer_Id] FOREIGN KEY ([Chofer_Id]) REFERENCES [dbo].[Chofer] ([Id]),
    [TarifaReferencia] DECIMAL(18, 2) NULL, 
    [Prestador_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Prestador_Prestador_Id] FOREIGN KEY ([Prestador_Id]) REFERENCES [dbo].[Proveedor] ([Id]),   
    [BocaDestino_Id] INT NULL,
	CONSTRAINT [FK_dbo.CartaPorte_dbo.BocaDestino_BocaDestino_Id] FOREIGN KEY ([BocaDestino_Id]) REFERENCES [dbo].[BocaDestino] ([Id]), 
	[Tecnologia_Id] INT NULL,
	[Cupo] VARCHAR(30) NULL, 
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Tecnologia_Tecnologia_Id] FOREIGN KEY ([Tecnologia_Id]) REFERENCES [dbo].[Tecnologia] ([Id]),
	[CorredorVendedor_Id] INT NULL,
	CONSTRAINT [FK_CartaPorte_Proveedor_CorredorVendedor] FOREIGN KEY([CorredorVendedor_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
	[IntermediarioFlete_Id] INT NULL,
	CONSTRAINT [FK_CartaPorte_Proveedor_IntermediarioFlete] FOREIGN KEY([IntermediarioFlete_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
	[Categoria_Id] INT NULL,
	CONSTRAINT [FK_CartaPorte_Categoria] FOREIGN KEY([Categoria_Id]) REFERENCES [dbo].[Categoria] ([Id]),
	[TrigoEspecial] BIT NULL,
	[NumeroAduana] VARCHAR(20) NULL, 
	[EsExtranjero] BIT NULL, 
	[FotoRutaDestino] VARCHAR(200) NULL,
	[FotoRutaDestinoDetalle] VARCHAR(200) NULL,
	[Cpe] BIT NULL, 
    [RtteComercialVentaSecundaria_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.RtteComercialVentaSecundaria_Proveedor_Id] FOREIGN KEY ([RtteComercialVentaSecundaria_Id]) REFERENCES [dbo].[Proveedor] ([Id]), 
    [RtteComercialProductor_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.RtteComercialProductor_Proveedor_Id] FOREIGN KEY ([RtteComercialProductor_Id]) REFERENCES [dbo].[Proveedor] ([Id]), 
    [CorredorVendedorSecundario_Id] INT NULL, 
	CONSTRAINT [FK_dbo.CartaPorte_dbo.CorredorVendedorSecundario_Proveedor_Id] FOREIGN KEY ([CorredorVendedorSecundario_Id]) REFERENCES [dbo].[Proveedor] ([Id]), 
    [Sucursal] INT NULL,
    [RtteComercialVentaSecundaria2_Id] INT NULL, 
	[Observacion] NVARCHAR(200) NULL,    
    CONSTRAINT [FK_dbo.CartaPorte_dbo.RtteComercialVentaSecundaria2_Proveedor_Id] FOREIGN KEY ([RtteComercialVentaSecundaria2_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    [NumeroOperativo] BIGINT NULL,
    [RamalFerroviario_Id] INT NULL,
    [NumeroPrecinto] VARCHAR(20) NULL,
    CONSTRAINT [FK_dbo.CartaPorte_dbo.RamalFerroviario_Id] FOREIGN KEY ([RamalFerroviario_Id]) REFERENCES [dbo].[RamalFerroviario] ([Id]),
    [TransportistaTramo2_Id] INT NULL,
	CONSTRAINT [FK_dbo.CartaPorte_dbo.Transportista_TransportistaTramo2_Id] FOREIGN KEY ([TransportistaTramo2_Id]) REFERENCES [dbo].[Transportista] ([Id]),
    [PagadorFlete_Id] INT NULL,
    CONSTRAINT [FK_CartaPorte_Proveedor_PagadorFlete] FOREIGN KEY([PagadorFlete_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    [RepresentanteRecibidor_Id] INT NULL,
    CONSTRAINT [FK_CartaPorte_Entregador_RepresentanteRecibidor] FOREIGN KEY(RepresentanteRecibidor_Id) REFERENCES [dbo].[Entregador] ([Id])
)

GO
CREATE NONCLUSTERED INDEX [IX_CartaPorte_NroCartaPorte]
    ON [dbo].[CartaPorte]([NroCartaPorte] ASC);

