CREATE TABLE [dbo].[CartaPorte] (
    [Id]                               INT             IDENTITY (1, 1) NOT NULL,
    [NroCartaPorte]                    VARCHAR (12)    NOT NULL,
    [FechaCP]                          DATE            NOT NULL,
    [FechaVto]                         DATE            NOT NULL,
    [FechaEmision]                     DATETIME        NOT NULL,
    [TipoVehiculo]                     INT             NOT NULL,
    [OrigenVehiculo]                   INT             NOT NULL,
    [CTG]                              VARCHAR (20)    NULL,
    [TipoComercial_Id]                 INT             NOT NULL,
    [Material_Id]                      INT             NOT NULL,
    [Procedencia_Id]                   INT             NOT NULL,
    [TitularCartaPorte_Id]             INT             NOT NULL,
    [Intermediario_Id]                 INT             NULL,
    [RtteComercial_Id]                 INT             NULL,
    [Corredor_Id]                      INT             NULL,
    [Entregador_Id]                    INT             NULL,
    [AgenteCompras_Id]                 INT             NULL,
    [Destinatario_Id]                  INT             NULL,
    [DestinatarioCliente_Id]           INT             NULL,
    [CentroDestino_Id]                 INT             NULL,
    [ClienteDestino_Id]                INT             NULL,
    [Transportista_Id]                 INT             NULL,
    [KmRecorrer]                       INT             NOT NULL,
    [TarifaTonelada]                   DECIMAL (18, 2) NULL,
    [Variedad]                         VARCHAR (15)    NULL,
    [CodEstab]                         VARCHAR (6)     NULL,
    [FletePagado]                      BIT             NULL,
    [FleteAPagar]                      BIT             NULL,
    [Aparceria]                        BIT             NULL,
    [Desvio]                           BIT             NULL,
    [AcuerdoMarco]                     VARCHAR (15)    NULL,
    [Cosecha]                          VARCHAR (5)     NOT NULL,
    [Caratula]                         INT             NULL,
    [CEE]                              VARCHAR (14)    NOT NULL,
    [CodigoAnexo]                      VARCHAR (10)    NULL,
    [Chofer_Id]                        INT             NOT NULL,
    [TarifaReferencia]                 DECIMAL (18, 2) NULL,
    [Prestador_Id]                     INT             NULL,
    [BocaDestino_Id]                   INT             NULL,
    [Tecnologia_Id]                    INT             NULL,
    [Cupo]                             VARCHAR (30)    NULL,
    [CorredorVendedor_Id]              INT             NULL,
    [IntermediarioFlete_Id]            INT             NULL,
    [Categoria_Id]                     INT             NULL,
    [TrigoEspecial]                    BIT             NULL,
    [NumeroAduana]                     VARCHAR (20)    NULL,
    [EsExtranjero]                     BIT             NULL,
    [FotoRutaDestino]                  VARCHAR (200)   NULL,
    [FotoRutaDestinoDetalle]           VARCHAR (200)   NULL,
    [Cpe]                              BIT             NULL,
    [RtteComercialVentaSecundaria_Id]  INT             NULL,
    [RtteComercialProductor_Id]        INT             NULL,
    [CorredorVendedorSecundario_Id]    INT             NULL,
    [Sucursal]                         INT             NULL,
    [RtteComercialVentaSecundaria2_Id] INT             NULL,
    [Observacion]                      NVARCHAR (MAX)  NULL,
    [NumeroOperativo]                  BIGINT          NULL,
    [RamalFerroviario_Id]              INT             NULL,
    [NumeroPrecinto]                   VARCHAR (20)    NULL,
    [TransportistaTramo2_Id]           INT             NULL,
    [PagadorFlete_Id]                  INT             NULL,
    [RepresentanteRecibidor_Id]        INT             NULL,
    [FotoRutaSustentable]              NVARCHAR(255)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_CartaPorte_Categoria] FOREIGN KEY ([Categoria_Id]) REFERENCES [dbo].[Categoria] ([Id]),
    CONSTRAINT [FK_CartaPorte_Entregador_RepresentanteRecibidor] FOREIGN KEY ([RepresentanteRecibidor_Id]) REFERENCES [dbo].[Entregador] ([Id]),
    CONSTRAINT [FK_CartaPorte_Proveedor_CorredorVendedor] FOREIGN KEY ([CorredorVendedor_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_CartaPorte_Proveedor_IntermediarioFlete] FOREIGN KEY ([IntermediarioFlete_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_CartaPorte_Proveedor_PagadorFlete] FOREIGN KEY ([PagadorFlete_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.AgenteCompras_Proveedor_Id] FOREIGN KEY ([AgenteCompras_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.BocaDestino_BocaDestino_Id] FOREIGN KEY ([BocaDestino_Id]) REFERENCES [dbo].[BocaDestino] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Centro_Centro_Id] FOREIGN KEY ([CentroDestino_Id]) REFERENCES [dbo].[Centro] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Chofer_Chofer_Id] FOREIGN KEY ([Chofer_Id]) REFERENCES [dbo].[Chofer] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Cliente_Cliente_Id] FOREIGN KEY ([ClienteDestino_Id]) REFERENCES [dbo].[Cliente] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Corredor_Proveedor_Id] FOREIGN KEY ([Corredor_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.CorredorVendedorSecundario_Proveedor_Id] FOREIGN KEY ([CorredorVendedorSecundario_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Destinatario_Cliente_Id] FOREIGN KEY ([DestinatarioCliente_Id]) REFERENCES [dbo].[Cliente] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Destinatario_Proveedor_Id] FOREIGN KEY ([Destinatario_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Entregador_Entregador_Id] FOREIGN KEY ([Entregador_Id]) REFERENCES [dbo].[Entregador] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Intermediario_Proveedor_Id] FOREIGN KEY ([Intermediario_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Localidad_Localidad_Id] FOREIGN KEY ([Procedencia_Id]) REFERENCES [dbo].[Localidad] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Material_Material_Id] FOREIGN KEY ([Material_Id]) REFERENCES [dbo].[Material] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Prestador_Prestador_Id] FOREIGN KEY ([Prestador_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.RamalFerroviario_Id] FOREIGN KEY ([RamalFerroviario_Id]) REFERENCES [dbo].[RamalFerroviario] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.RtteComercial_Proveedor_Id] FOREIGN KEY ([RtteComercial_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.RtteComercialProductor_Proveedor_Id] FOREIGN KEY ([RtteComercialProductor_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.RtteComercialVentaSecundaria_Proveedor_Id] FOREIGN KEY ([RtteComercialVentaSecundaria_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.RtteComercialVentaSecundaria2_Proveedor_Id] FOREIGN KEY ([RtteComercialVentaSecundaria2_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Tecnologia_Tecnologia_Id] FOREIGN KEY ([Tecnologia_Id]) REFERENCES [dbo].[Tecnologia] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.TipoComercial_TipoComercial_Id] FOREIGN KEY ([TipoComercial_Id]) REFERENCES [dbo].[TipoComercial] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Transportista_Transportista_Id] FOREIGN KEY ([Transportista_Id]) REFERENCES [dbo].[Transportista] ([Id]),
    CONSTRAINT [FK_dbo.CartaPorte_dbo.Transportista_TransportistaTramo2_Id] FOREIGN KEY ([TransportistaTramo2_Id]) REFERENCES [dbo].[Transportista] ([Id])
);



GO
CREATE NONCLUSTERED INDEX [IX_CartaPorte_NroCartaPorte]
    ON [dbo].[CartaPorte]([NroCartaPorte] ASC) WITH (FILLFACTOR = 90, STATISTICS_NORECOMPUTE = ON);



