CREATE TABLE [dbo].[CartaPorteElectronica] (
    [Id]                                     INT             IDENTITY (1, 1) NOT NULL,
    [TipoCartaPorte]                         INT             NULL,
    [Sucursal]                               INT             NULL,
    [NroOrden]                               BIGINT          NULL,
    [Planta]                                 INT             NULL,
    [NroCTG]                                 BIGINT          NULL,
    [FechaEmision]                           DATETIME        NULL,
    [Estado]                                 NVARCHAR (20)   NULL,
    [FechaCP]                                DATETIME        NULL,
    [FechaVto]                               DATETIME        NULL,
    [Provincia]                              INT             NULL,
    [Localidad]                              INT             NULL,
    [Domicilio]                              NVARCHAR (100)  NULL,
    [PlantaOrigen]                           INT             NULL,
    [RetiroProductor]                        BIT             NULL,
    [CertificadoCOE]                         BIGINT          NULL,
    [CuitRemitenteComercialProductor]        BIGINT          NULL,
    [CuitIntermediario]                      BIGINT          NULL,
    [CuitRemitenteComercialVentaPrimaria]    BIGINT          NULL,
    [CuitRemitenteComercialVentaSecundaria]  BIGINT          NULL,
    [CuitMercadoATermino]                    BIGINT          NULL,
    [CuitCorredorVentaPrimaria]              BIGINT          NULL,
    [CuitCorredorVentaSecundaria]            BIGINT          NULL,
    [CuitRepresentanteEntregador]            BIGINT          NULL,
    [Material]                               INT             NULL,
    [Cosecha]                                INT             NULL,
    [PesoBruto]                              INT             NULL,
    [PesoTara]                               INT             NULL,
    [CuitDestino]                            BIGINT          NULL,
    [LocalidadDestino]                       BIGINT          NULL,
    [ProvinciaDestino]                       BIGINT          NULL,
    [PlantaDestino]                          INT             NULL,
    [CuitDestinatario]                       BIGINT          NULL,
    [CuitTransportista]                      BIGINT          NULL,
    [Dominio]                                NVARCHAR (100)  NULL,
    [FechaPartida]                           DATETIME        NULL,
    [KmRecorrer]                             INT             NULL,
    [CodigoTurno]                            NVARCHAR (100)  NULL,
    [Tarifa]                                 FLOAT (53)      NOT NULL,
    [CuitChofer]                             BIGINT          NULL,
    [CuitPagadorFlete]                       BIGINT          NULL,
    [CuitIntermediarioFlete]                 BIGINT          NULL,
    [MercaderiaFumigada]                     BIT             NULL,
    [CuitRepresentanteRecibidor]             BIGINT          NULL,
    [CuitOrigen]                             BIGINT          NULL,
    [Observacion]                            NVARCHAR (500)  NULL,
    [FechaUltimaActualizacion]               DATETIME        NULL,
    [NroOperativo]                           BIGINT          NULL,
    [CuitRemitenteComercialVentaSecundaria2] BIGINT          NULL,
    [RamalFerroviario]                       INT             NULL,
    [NumeroPrecinto]                         VARCHAR (20)    NULL,
    [Pdf]                                    VARBINARY (MAX) NULL,
    [CuitTransportistaTramo2]                BIGINT          NULL,
    [TarifaReferencia]                       FLOAT (53)      DEFAULT ((0)) NOT NULL,
    [FechaCacheado]                          DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

