CREATE TABLE [dbo].[DescargaUnidadItem] (
    [Id]				INT IDENTITY (1, 1) NOT NULL,
    [DescargaUnidad_Id]		INT NOT NULL,
    CONSTRAINT	[FK_dbo.DescargaUnidadItem_dbo.DescargaUnidad_DescargaUnidad_Id] FOREIGN KEY ([DescargaUnidad_Id]) REFERENCES [dbo].[DescargaUnidad] ([Id]) ON DELETE CASCADE,
    [Material_Id]		INT NOT NULL,
	CONSTRAINT	[FK_dbo.DescargaUnidadItem_dbo.Material_Material_Id] FOREIGN KEY ([Material_Id]) REFERENCES [dbo].[Material] ([Id]),
    [Almacen_Id]		INT NOT NULL,
	CONSTRAINT	[FK_dbo.DescargaUnidadItem_dbo.Almacen_Almacen_Id] FOREIGN KEY ([Almacen_Id]) REFERENCES [dbo].[Almacen] ([Id]),
    [LoteProveedor]		NVARCHAR (10) NULL,
    [PesoBruto]		DECIMAL(18, 2) NOT NULL,
    [PesoTara]		DECIMAL(18, 2) NOT NULL,
    [Fecha]		DATETIME NOT NULL DEFAULT GETDATE(),
	[FechaFabricacion]		DATETIME NULL,
	[ItemNro]	INT NOT NULL,
	CONSTRAINT [PK_dbo.DescargaUnidadItem] PRIMARY KEY CLUSTERED ([Id] ASC),
	[DocMaterial]		NVARCHAR (20) NOT NULL,
	[EjercicioDocMaterial]		NVARCHAR (20) NOT NULL,
	[EjercicioDocMaterialAnulacion]		NVARCHAR (20) NULL,
	[RemitoNro]		NVARCHAR (20) NOT NULL, 
    [Rechazado] BIT NOT NULL,
	[FechaRemito]		DATETIME NOT NULL,
	[Unidades]		DECIMAL NOT NULL,
	[TaraRomaneo_Id]		INT NOT NULL,
	CONSTRAINT	[FK_dbo.DescargaUnidadItem_dbo.TaraRomaneo_TaraRomaneo_Id] FOREIGN KEY ([TaraRomaneo_Id]) REFERENCES [dbo].[TaraRomaneo] ([Id]),
);