CREATE TABLE [dbo].[Embarque]
(
	[Id]  INT IDENTITY (1, 1) NOT NULL, 
    [Coordinadores_Id] INT NULL,
    [Agencias_Id] INT NULL,
    [Vapor_Id] INT NOT NULL, 
    [FechaRecalada] DATETIME NULL, 
    [HoraRecalada] NVARCHAR(8) NULL,
    [ObligacionCarga] DATETIME NULL, 
    [Senasa] BIT NOT NULL, 
    [Vicentin] BIT NOT NULL,
    [OtrosMuelles] BIT NOT NULL, 
    [Observaciones] NVARCHAR(500) NULL,
    [Recorrido_Id] INT NOT NULL, 
    [Centro_Id] INT NOT NULL, 
    [Patente] NVARCHAR(60) NOT NULL, 
    [TipoBuque] NVARCHAR(50) NULL, 
    [Freeboard] DECIMAL(18,2) NOT NULL default 0,
    [Noryon] BIT NOT NULL default 0,
    [SanBenito] BIT NOT NULL default 1,
    [Ubicacion]					INT NOT NULL default 0,
    [ATA_Id] INT NULL,
    [EsLiquido] BIT NOT NULL DEFAULT 0,
    [FechaDesdeLimpieza] DATETIME NULL, 
    [HoraDesdeLimpieza] NVARCHAR(8) NULL,
    [FechaHastaLimpieza] DATETIME NULL,
    [HoraHastaLimpieza] NVARCHAR(8) NULL,
    [MotivosLimpieza_Id] INT NULL, 
    [ObservacionesLimpieza] NVARCHAR(500) NULL,
    [Destino_Id] INT NULL,
    [PorteNeto] DECIMAL(18,2) not NULL default 0,
    [PorteBruto] DECIMAL(18,2) not NULL default 0,
    [Eslora] DECIMAL(18,2) not NULL default 0,  
    [Manga] DECIMAL(18,2) not NULL default 0,
    [Puntal] DECIMAL(18,2) not NULL default 0,
    [FechaLibrePlatica] DATETIME NULL, 
    [HoraLibrePlatica] NVARCHAR(8) NULL,
    [EstadoBuque_Id] INT NULL, 
    CONSTRAINT [PK_Embarque] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_dbo.Embarque_dbo.Vapor_Vapor_Id] FOREIGN KEY ([Vapor_Id]) REFERENCES [dbo].[Vapor] ([Id]),
    CONSTRAINT [FK_dbo.Embarque_dbo.Recorrido_Recorrido_Id] FOREIGN KEY ([Recorrido_Id]) REFERENCES [dbo].[Recorrido] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_dbo.Embarque_dbo.Centro_Centro_Id] FOREIGN KEY ([Centro_Id]) REFERENCES [dbo].[Centro] ([Id]),
    CONSTRAINT [FK_dbo.Embarque_dbo.CoordinadorPuerto_Coordinador_Id] FOREIGN KEY ([Coordinadores_Id]) REFERENCES [dbo].[CoordinadorPuerto] ([Id]),
    CONSTRAINT [FK_dbo.Embarque_dbo.AgenciaMaritimaPuerto_Agencia_Id] FOREIGN KEY ([Agencias_Id]) REFERENCES [dbo].[AgenciaMaritimaPuerto] ([Id]),
    CONSTRAINT [FK_dbo.Embarque_dbo.ATAPuerto_ATA_Id] FOREIGN KEY ([ATA_Id]) REFERENCES [dbo].[ATAPuerto] ([Id]),
    CONSTRAINT [FK_dbo.Embarque_dbo.MotivosLimpieza_MotivosLimpieza_Id] FOREIGN KEY ([MotivosLimpieza_Id]) REFERENCES [dbo].[MotivosLimpieza] ([Id]),
    CONSTRAINT [FK_dbo.Embarque_dbo.Destino_Destino_Id] FOREIGN KEY ([Destino_Id]) REFERENCES [dbo].[Destino] ([Id]),
    CONSTRAINT [FK_dbo.Embarque_dbo.EstadoBuque_EstadoBuque_Id] FOREIGN KEY ([EstadoBuque_Id]) REFERENCES [dbo].[EstadoBuque] ([Id])
)