CREATE TABLE [dbo].[HistoricoEmbarqueLineUp](
	[Id]					[BIGINT] IDENTITY(1,1) NOT NULL, 
	[VaporNombre]			NVARCHAR(50) NOT NULL, 
	[Actualizado]			NVARCHAR(20), 
	[Ubicacion]				NVARCHAR(50),
	[CartaSubidaEnviada]	BIT NOT NULL DEFAULT 0,
	[CartaSubidaAprobada]	NVARCHAR(50),
	[CargaEnSap]			BIT NOT NULL DEFAULT 0,
	[NominacionDePractico]	BIT NOT NULL DEFAULT 0,
	[SeguridadPortuaria]	BIT NOT NULL DEFAULT 0,
	[InspeccionSenasa]		BIT NOT NULL DEFAULT 0,
	[ControlSenasa]			BIT NOT NULL DEFAULT 0,
	[ControlPrivado]		BIT NOT NULL DEFAULT 0,
	[Amarrador]				BIT NOT NULL DEFAULT 0,
	[AgenciaContactada]		BIT NOT NULL DEFAULT 0,
	[FechaRecalada]			NVARCHAR(20),
	[PuertoActual]			NVARCHAR(50),
	[Observaciones]			NVARCHAR(200),
	[Materiales]			NVARCHAR(200),
	[PlanoDeCargaEnviado]	BIT NOT NULL DEFAULT 0,
	[ObligacionCarga]		NVARCHAR(50),
	[AgenteNombre]			NVARCHAR(50),
	[AtaNombre]				NVARCHAR(50), 
	[LineUpId]				INT NOT NULL,
	[EmbarqueId]			INT NOT NULL,
	[OtroMuelleNombre]		NVARCHAR(120) NULL, 
	[TransaccionesSAP_Id]	BIGINT NULL,
    
	CONSTRAINT [PK_dbo.HistoricoEmbarqueLineUp] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_dbo.HistoricoEmbarqueLineUp_LineUpId] FOREIGN KEY ([LineUpId]) REFERENCES [dbo].[LineUp] ([Id]),
	CONSTRAINT [FK_dbo.HistoricoEmbarqueLineUp_EmbarqueId] FOREIGN KEY ([EmbarqueId]) REFERENCES [dbo].[Embarque] ([Id]),
	CONSTRAINT [FK_dbo.HistoricoEmbarqueLineUp_TransaccionesSAPId] FOREIGN KEY ([TransaccionesSAP_Id]) REFERENCES [dbo].[TransaccionesSAP] ([Id])
);