CREATE TABLE [dbo].[ImpCertificadoDeAnalisis] (
    [Id]                                INT            NOT NULL,
    [Centro]                            NVARCHAR (50)  NULL,
    [NumeroDocumento]                   NVARCHAR (50)  NULL,
    [NumeroIngreso]                     NVARCHAR (50)  NULL,
    [PatenteAcoplado]                   NVARCHAR (50)  NULL,
    [Entregador]                        NVARCHAR (50)  NULL,
    [Corredor]                          NVARCHAR (50)  NULL,
    [Vendedor]                          NVARCHAR (50)  NULL,
    [Observaciones]                     NVARCHAR (100) NULL,
    [HumedadDescripcion]                NVARCHAR (50)  NULL,
    [NumeroDeTarjetaAsignada]           NVARCHAR (50)  NULL,
    [FechaYhoraDeIngreso]               NVARCHAR (50)  NULL,
    [MaterialDesc]                      NVARCHAR (50)  NULL,
    [EsSustentable]                     BIT            NULL,
    [CTG]                               NVARCHAR (50)  NULL,
    [TitularDeCartaDePorteCuit]         NVARCHAR (50)  NULL,
    [TitularDeCartaDePorteRazon]        NVARCHAR (50)  NULL,
    [IntermediarioCuit]                 NVARCHAR (50)  NULL,
    [IntermediarioRazon]                NVARCHAR (50)  NULL,
    [RemitenteComercialCuit]            NVARCHAR (50)  NULL,
    [RemitenteComercialRazon]           NVARCHAR (50)  NULL,
    [CorredorCuit]                      NVARCHAR (50)  NULL,
    [VendedorCuit]                      NVARCHAR (50)  NULL,
    [EntregadorCuit]                    NVARCHAR (50)  NULL,
    [AgenteDeComprasCuit]               NVARCHAR (50)  NULL,
    [AgenteDeComprasRazon]              NVARCHAR (50)  NULL,
    [DestinatarioCuit]                  NVARCHAR (50)  NULL,
    [DestinatarioRazon]                 NVARCHAR (50)  NULL,
    [DestinoCuit]                       NVARCHAR (50)  NULL,
    [DestinoRazon]                      NVARCHAR (50)  NULL,
    [TransportistaCuit]                 NVARCHAR (50)  NULL,
    [TransportistaRazon]                NVARCHAR (50)  NULL,
    [ChoferCuit]                        NVARCHAR (50)  NULL,
    [ChoferNombre]                      NVARCHAR (50)  NULL,
    [ProcedenciaDeLaMercanderiaCodAFIP] NVARCHAR (50)  NULL,
    [ProcedenciaDeLaMercanderiaDesc]    NVARCHAR (50)  NULL,
    [Cupo]                              NVARCHAR (50)  NULL,
    CONSTRAINT [PK_dbo.ImpCertificadoDeAnalisis] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_dbo.ImpCertificadoDeAnalisis_dbo.ImpId] FOREIGN KEY ([Id]) REFERENCES [dbo].[Impresion] ([Id]) ON DELETE CASCADE
);

