CREATE TABLE [dbo].[ImpConstanciaDeEntregaLaser] (
    [Id]                   INT            NOT NULL,
    [Centro]               NVARCHAR (50)  NULL,
    [CentroDireccion]      NVARCHAR (50)  NULL,
    [CentroLocalidad]      NVARCHAR (50)  NULL,
    [CentroProvincia]      NVARCHAR (50)  NULL,
    [Fecha]                DATETIME       NOT NULL,
    [NumeroDeOrden]        NVARCHAR (50)  NULL,
    [NumeroCertificacion]  NVARCHAR (50)  NULL,
    [Material]             NVARCHAR (50)  NULL,
    [Corredor]             NVARCHAR (50)  NULL,
    [Vendedor]             NVARCHAR (50)  NULL,
    [Procedencia]          NVARCHAR (50)  NULL,
    [NumeroCartaPorte]     NVARCHAR (50)  NULL,
    [PesoBruto]            NVARCHAR (50)  NULL,
    [PesoTara]             NVARCHAR (50)  NULL,
    [PesoNeto]             NVARCHAR (50)  NULL,
    [FechaCartaPorte]      DATETIME       NOT NULL,
    [PatenteAcoplado]      NVARCHAR (50)  NULL,
    [Observaciones]        NVARCHAR (100) NULL,
    [ObservacionesCalado]  NVARCHAR (100) NULL,
    [BalanzaTara]          NVARCHAR (30)  NULL,
    [BalanzaBruto]         NVARCHAR (30)  NULL,
    [ModeloBalanzaTara]    NVARCHAR (30)  NULL,
    [ModeloBalanzaBruto]   NVARCHAR (30)  NULL,
    [NroSerieBalanzaTara]  NVARCHAR (30)  NULL,
    [NroSerieBalanzaBruto] NVARCHAR (30)  NULL,
    [Entregador]           NVARCHAR (100) NULL,
    CONSTRAINT [PK_dbo.ImpConstanciaDeEntregaLaser] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_dbo.ImpConstanciaDeEntregaLaser_dbo.ImpId] FOREIGN KEY ([Id]) REFERENCES [dbo].[Impresion] ([Id]) ON DELETE CASCADE
);

