CREATE TABLE [dbo].[ImpEtiquetaAuditoria] (
    [Id]                     INT             NOT NULL,
	[Centro]				NVARCHAR (50)    NULL,
	[CentroDomicilio]				NVARCHAR (150)    NULL,
	[NumeroCartaPorte]			NVARCHAR (13)    NULL,
	[FechaDescarga]			DATETIME    NULL,
	[PesoBruto]				NVARCHAR (10)    NULL,
	[BalanzaBruto]				NVARCHAR (50)    NULL,
	[UsuarioBruto]				NVARCHAR (50)    NULL,
	[PesoTara]				NVARCHAR (10)    NULL,
	[BalanzaTara]				NVARCHAR (50)    NULL,
	[UsuarioTara]				NVARCHAR (50)    NULL,
	[PesoNeto]				NVARCHAR(10)    NULL,
	[PatenteAcoplado]				NVARCHAR (10)    NULL,
	[EntregadorRazonSocial]				NVARCHAR (100)    NULL,
	[EntregadorCuit]				NVARCHAR (13)    NULL,
    [PesoNetoConDescuento] NVARCHAR(10) NULL,	
	[RecibidorNombre] NVARCHAR(100) NULL,
	[RecibidorApellido] NVARCHAR(100) NULL,
	[RecibidorMatricula] NVARCHAR(100) NULL,
	[RecibidorFirma] VARCHAR(8000) NULL,
    CONSTRAINT [PK_dbo.ImpEtiquetaAuditoria] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_dbo.ImpEtiquetaAuditoria_dbo.ImpId] FOREIGN KEY ([Id]) REFERENCES [dbo].[Impresion] ([Id]) ON DELETE CASCADE
);