CREATE TABLE [dbo].[ImpFormulario239] (
    [Id]						INT              NOT NULL,
	[Centro]					NVARCHAR (50)    NULL,
	[CentroDireccion]			NVARCHAR (50)    NULL,
	[CentroLocalidad]			NVARCHAR (50)    NULL,
	[CentroProvincia]			NVARCHAR (50)    NULL,
	[Fecha]						DATETIME NOT NULL, 
	[NumeroDocumentoEntrada]	NVARCHAR (50)    NULL,
	[TipoDocumentoEntrada]		int    NOT NULL,
	[EmpresaCuit]				NVARCHAR (50)    NULL,
	[Empresa]					NVARCHAR (50)    NULL,
	[Representante]				NVARCHAR (50)    NULL,
	[PatenteAcoplado]			NVARCHAR (50)    NULL,
	[NumeroDeOrden]				NVARCHAR (50)    NULL,
	[NumeroDeFormulario]		NVARCHAR (50)    NULL,
	[Material]					NVARCHAR (50)    NULL,
	[MaterialCodigoSap]			NVARCHAR (50)    NULL,
	[Observaciones]				NVARCHAR (255)    NULL,
	[CTG]						NVARCHAR (50)    NULL,
    CONSTRAINT [PK_dbo.ImpFormulario239] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_dbo.ImpFormulario239_dbo.ImpId] FOREIGN KEY ([Id]) REFERENCES [dbo].[Impresion] ([Id]) ON DELETE CASCADE
);