CREATE TABLE [dbo].[ImpIdentificacionMuestraAuditoria] (
    [Id]                     INT             NOT NULL,
	[Centro]				NVARCHAR (50)    NULL,
	[NroMuestra]			NVARCHAR (50)    NULL,
	[NumeroDeOrden]			NVARCHAR (50)    NULL,
	[PatenteAcoplado]		NVARCHAR (50)    NULL,
	[Material]				NVARCHAR (100)    NULL,
	[MaterialId]           INT             NOT NULL,
	[Proveedor]				NVARCHAR (50)    NULL,
	[ProveedorCuit]			NVARCHAR (50)    NULL,
	[Entregador]			NVARCHAR (50)    NULL,
	[EntregadorCuit]		NVARCHAR (50)    NULL,
	[Corredor]				NVARCHAR (50)    NULL,
	[CorredorCuit]			NVARCHAR (50)    NULL,
	[Procedencia]			NVARCHAR (50)    NULL,
	[FechaHoraCalado]		NVARCHAR (50)    NULL,
	[UsuarioCalado]			NVARCHAR (50)    NULL,
    CONSTRAINT [PK_dbo.ImpIdentificacionMuestraAuditoria] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_dbo.ImpIdentificacionMuestraAuditoria_dbo.ImpId] FOREIGN KEY ([Id]) REFERENCES [dbo].[Impresion] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_dbo.ImpIdentificacionMuestraAuditoria_dbo.Material_Material_Id] FOREIGN KEY ([MaterialId]) REFERENCES [dbo].[Material] ([Id]),
);