CREATE TABLE [dbo].[ImpTicketPesadaAduana] (
    [Id]                         INT            NOT NULL,
    [NumeroDocumento]            NVARCHAR (50)  NULL,
    [Material]                   NVARCHAR (50)  NULL,
    [PesoBruto]                  NVARCHAR (50)  NULL,
    [PesoTara]                   NVARCHAR (50)  NULL,
    [PesoNeto]                   NVARCHAR (100) NULL,
    [Transportista]              NVARCHAR (50)  NULL,
    [CuitTransportista]          NVARCHAR (50)  NULL,
    [PatenteAcoplado]            NVARCHAR (50)  NULL,
    [Observaciones]              NVARCHAR (100) NULL,
    [Identidad]                  INT            NOT NULL,
    [CodigoAduana]               NVARCHAR (50)  NULL,
    [CertificadoDeHabilitacion]  NVARCHAR (50)  NULL,
    [CuitExportador]             NVARCHAR (50)  NULL,
    [RazonSocialExportador]      NVARCHAR (50)  NULL,
    [PermisoDeEmbarque]          NVARCHAR (50)  NULL,
    [FechaInicio]                DATETIME       NULL,
    [FechaEgreso]                DATETIME       NULL,
    [IdentificadorDeContenedor]  NVARCHAR (50)  NULL,
    [ChoferTipoDoc]              NVARCHAR (50)  NULL,
    [ChoferNumero]               NVARCHAR (50)  NULL,
    [ChoferApellido]             NVARCHAR (50)  NULL,
    [ChoferNombre]               NVARCHAR (50)  NULL,
    [VencimientoDeCertificacion] DATETIME       NULL,
    [NumeroInternoSap]           NVARCHAR (50)  NULL,
    [Nacionalidad]               NVARCHAR (50)  NULL,
    [NumeroIngreso]              NVARCHAR (50)  NULL,
    [BalanzaNombre]              NVARCHAR (50)  NULL,
    [Longitud]                   NVARCHAR (50)  NULL,
    [Latitud]                    NVARCHAR (50)  NULL,
    [Lot]                        NVARCHAR (50)  NULL,
    [FechaHoraPesoTara]          DATETIME       NULL,
    [FechaHoraPesoBruto]         DATETIME       NULL,
    CONSTRAINT [PK_dbo.ImpTicketPesadaAduana] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_dbo.ImpTicketPesadaAduana_dbo.ImpId] FOREIGN KEY ([Id]) REFERENCES [dbo].[Impresion] ([Id]) ON DELETE CASCADE
);

