CREATE TABLE [dbo].[ImpTicketPesadaBodega] (
    [Id]                     INT             NOT NULL,
	[FechaUltimaPesada]			DATETIME    NULL,
	[ComprobanteInterno]				NVARCHAR (50)    NULL,
	[Material]		NVARCHAR (50)    NULL,
	[Proveedor]			NVARCHAR (50)    NULL,
	[Remito]		NVARCHAR (50)    NULL,
	[PesoBrutoBodega]				NVARCHAR (50)    NULL,
	[PesoTaraBodega]				NVARCHAR (50)    NULL,
	[BalanzaBruto]				NVARCHAR (50)    NULL,
	[BalanzaTara]				NVARCHAR (100)    NULL,
	[Transportista]				NVARCHAR (50)    NULL,
	[Chofer]			NVARCHAR (50)    NULL,
	[PatenteAcoplado]		NVARCHAR (50)    NULL,
	[Observaciones]			NVARCHAR (100)    NULL,
    [FechaIngreso] DATETIME NULL, 
    [FechaEgreso] DATETIME NULL, 
    [CIU] NVARCHAR(50) NULL, 
    [Pedido] NVARCHAR(50) NULL, 
    [Identidad] INT NOT NULL, 
    [CentroDescripcion] NVARCHAR(50) NULL, 
    [CentroLocalidad] NVARCHAR(50) NULL, 
    [CentroDireccion] NVARCHAR(50) NULL, 
    CONSTRAINT [PK_dbo.ImpTicketPesadaBodega] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_dbo.ImpTicketPesadaBodega_dbo.ImpId] FOREIGN KEY ([Id]) REFERENCES [dbo].[Impresion] ([Id]) ON DELETE CASCADE
);