CREATE TABLE [dbo].[IngresosPorCompraDeGranosTransmisionASap] (
    [Id]               INT NOT NULL,
	[AlmacenCodigoSap] NVARCHAR (100) NULL,
	[PatenteAcoplado] NVARCHAR (100) NULL,
	[AgenteCompra] NVARCHAR (100) NULL,
	[Secuencia] NVARCHAR (100) NULL,
	[Almacen] NVARCHAR (100) NULL,
	[Apariencia] NVARCHAR (100) NULL,
	[Balanza] NVARCHAR (100) NULL,
	[Bruto] NVARCHAR (100) NULL,
	[BrutoOrigen] NVARCHAR (100) NULL,
	[Camara] NVARCHAR (100) NULL,
	[Caratula] NVARCHAR (100) NULL,
	[Cargador] NVARCHAR (100) NULL,
	[CCPP] NVARCHAR (100) NULL,
	[Analisis] NVARCHAR (100) NULL,
	[Centro] NVARCHAR (100) NULL,
	[Chofer] NVARCHAR (100) NULL,
	[Contrato] NVARCHAR (100) NULL,
	[Destino] NVARCHAR (100) NULL,
	[EntradaSalida] NVARCHAR (100) NULL,
	[EstadoSAP] NVARCHAR (100) NULL,
	[FechaAlta] NVARCHAR (100) NULL,
	[FechaBruto] NVARCHAR (100) NULL,
	[FechaCalado] NVARCHAR (100) NULL,
	[FechaEgreso] NVARCHAR (100) NULL,
	[FechaIngreso] NVARCHAR (100) NULL,
	[FechaNeto] NVARCHAR (100) NULL,
	[FechaTara] NVARCHAR (100) NULL,
	[Km] NVARCHAR (100) NULL,
	[Material] NVARCHAR (100) NULL,
	[FirmaPaga] NVARCHAR (100) NULL,
	[MuestraConjunto] NVARCHAR (100) NULL,
	[Neto] NVARCHAR (100) NULL,
	[NetoOrigen] NVARCHAR (100) NULL,
	[NroDocChofer] NVARCHAR (100) NULL,
	[NumCarPor] NVARCHAR (100) NULL,
	[Patente] NVARCHAR (100) NULL,
	[Pesada] NVARCHAR (100) NULL,
	[Prestador] NVARCHAR (100) NULL,
	[Proveedor] NVARCHAR (100) NULL,
	[Procedencia] NVARCHAR (100) NULL,
	[ProvProc] NVARCHAR (100) NULL,
	[Remitente] NVARCHAR (100) NULL,
	[Tara] NVARCHAR (100) NULL,
	[TaraOrigen] NVARCHAR (100) NULL,
	[TipoDocChofer] NVARCHAR (100) NULL,
	[TipoComercial] NVARCHAR (100) NULL,
	[TipVehiculo] NVARCHAR (100) NULL,
	[Transportista] NVARCHAR (100) NULL,
	[Variedad] NVARCHAR (100) NULL,
	[Corredor] NVARCHAR (100) NULL,
	[NetoDescontado] NVARCHAR (100) NULL,
	[CuentaOrden] NVARCHAR (100) NULL,
	[HoraBruto] NVARCHAR (100) NULL,
	[HoraCalado] NVARCHAR (100) NULL,
	[HoraEgreso] NVARCHAR (100) NULL,
	[HoraIngreso] NVARCHAR (100) NULL,
	[HoraNeto] NVARCHAR (100) NULL,
	[HoraTara] NVARCHAR (100) NULL, 
	[Cuenta_Orden] NVARCHAR (100) NULL,
    [CTG] NVARCHAR(100) NULL, 
    [FECHA_CTG] NVARCHAR(100) NULL, 
    [CanjeRemito] NVARCHAR(100) NULL, 
    [NumeroCCPP] NVARCHAR(100) NULL, 
    [Cosecha] NVARCHAR(100) NULL, 
    [CTG_Destinatario] NVARCHAR(100) NULL, 
    [CuitCanjeador] NVARCHAR(100) NULL, 
    [CuitDestinatario] NVARCHAR(100) NULL, 
    [CuitDestino] NVARCHAR(100) NULL, 
    [Especie] NVARCHAR(100) NULL, 
    [Establecimiento] NVARCHAR(100) NULL, 
    [Estado_Destinatario] NVARCHAR(100) NULL, 
    [FechaConf] NVARCHAR(100) NULL, 
    [PesoNetoCarga] NVARCHAR(100) NULL, 
    [Solicitante] NVARCHAR(100) NULL, 
	[CuitDestinatarioCartaPorte] NVARCHAR(100) NULL, 
    [CosechaCartaPorte] NVARCHAR(100) NULL, 
    [EstablecimientoCartaPorte] NVARCHAR(100) NULL, 
    [NoValidaCG] NVARCHAR(100) NULL, 
	[Cupo] NVARCHAR(100) NULL,
	[TrigoEspecial] NVARCHAR(100) NULL,
	[InterFlete] NVARCHAR(150) NULL,
	[Clasificacion] NVARCHAR(150) NULL,
    [CuitSolicitante] NVARCHAR(100) NULL, 
    CONSTRAINT [PK_dbo.IngresosPorCompraDeGranosTransmisionASap] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_dbo.IngresosPorCompraDeGranosTransmisionASap_dbo.TransmisionASapId] FOREIGN KEY ([Id]) REFERENCES [dbo].[TransmisionASap] ([Id]) ON DELETE CASCADE
);
GO
