CREATE TABLE [dbo].[LogAjusteDeStock] (
    [Id]                     INT              IDENTITY (1, 1) NOT NULL,
    [TipoComprobanteOncca_Id]   INT              NOT NULL default 1,
    [NumeroDocumentoIngreso] NVARCHAR (40)   NOT NULL,
	[Fecha]	         DATETIME NOT NULL,
	[FechaAjuste]	         DATETIME NULL,
	[Material_Id] INT NOT NULL,
	[PesoBrutoIngreso] DECIMAL (18, 2) NOT NULL, 
    [PesoNetoIngreso] DECIMAL (18, 2) NOT NULL, 
    [PesoNetoEgreso] DECIMAL (18, 2) NOT NULL,
	[Centro_Id]                  INT             NOT NULL,
	[Observaciones] NVARCHAR (30),
	[NombreUsuario] NVARCHAR (30),
	[Tipo] NVARCHAR (30),
    CONSTRAINT [PK_dbo.LogAjusteDeStock] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_dbo.LogAjusteDeStock_dbo.Material_Material_Id] FOREIGN KEY ([Material_Id]) REFERENCES [dbo].[Material] ([Id]),
	CONSTRAINT [FK_dbo.LogAjusteDeStock_dbo.Centro_Centro_Id] FOREIGN KEY ([Centro_Id]) REFERENCES [dbo].[Centro] ([Id]),
	CONSTRAINT [FK_dbo.LogAjusteDeStock_dbo.TipoComprobanteOncca_TipoComprobanteOncca_Id] FOREIGN KEY ([TipoComprobanteOncca_Id]) REFERENCES [dbo].[TipoComprobanteOncca] ([Id]),
);