CREATE TABLE [dbo].[ModuloDeCargaPlanillaDeTurnosDetallesLiquido]
(
	[Id]                                        INT IDENTITY (1, 1) NOT NULL,
    [ModuloDeCargaPlanillaDeTurnos_Id]    INT NOT NULL,
    [Exportador_Id]                             INT NOT NULL,
    [Linea_Id]                                     INT NOT NULL,
    [BodegaParcel]                              INT,
    [MaterialPuerto_Id]                         INT NOT NULL,
    [Tk]                                        NVARCHAR (10),
    [Temperatura]                               FLOAT,
    [MedidaInicialCM]                           FLOAT,
    [MedidaInicialMM]                           FLOAT,
    [MedidaFinalCM]                             FLOAT,
    [MedidaFinalMM]                             FLOAT,
    [Destino_Id]                                INT NULL,
    [Cantidad]                                  DECIMAL(18, 8),
    [HoraInicio]                                NVARCHAR (8),
    [HoraFin]                                   NVARCHAR (8),
    [CambioMaterial] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_dbo.ModuloDeCargaPlanillaDeTurnosDetallesLiquido] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_dbo.ModuloDeCargaPlanillaDeTurnosDetallesLiquido_dbo.ModuloDeCargaPlanillaDeTurnos_MDCPlanillaDeTurnos_Id] FOREIGN KEY ([ModuloDeCargaPlanillaDeTurnos_Id]) REFERENCES [dbo].[ModuloDeCargaPlanillaDeTurnos] ([Id]) on delete cascade,
    CONSTRAINT [FK_dbo.ModuloDeCargaPlanillaDeTurnosDetallesLiquido_dbo.Exportador_Exportador_Id] FOREIGN KEY ([Exportador_Id]) REFERENCES [dbo].[Exportador] ([Id]),
    CONSTRAINT [FK_dbo.ModuloDeCargaPlanillaDeTurnosDetallesLiquido_dbo.MaterialPuerto_MaterialPuerto_Id] FOREIGN KEY ([MaterialPuerto_Id]) REFERENCES [dbo].[MaterialPuerto] ([Id]),
    CONSTRAINT [FK_dbo.ModuloDeCargaPlanillaDeTurnosDetallesLiquido_dbo.Destino_Destino_Id] FOREIGN KEY ([Destino_Id]) REFERENCES [dbo].[Destino] ([Id])
);