CREATE TABLE [dbo].[MovimientoDeBines] (
    [Id]                     INT              IDENTITY (1, 1) NOT NULL,
    [Fecha]	         DATETIME NOT NULL,
	[Movimiento]   INT			 NOT NULL,
	[Material_Id] INT NOT NULL,
	[Centro_Id]                  INT             NULL,
	[Observaciones] NVARCHAR (100) NULL,
	[Proveedor_Id] INT NULL,
	[Cantidad] INT NOT NULL,
	[TipoAjuste] INT NOT NULL,
	[NombreUsuario] NVARCHAR (40) NOT NULL,
	[Numero] NVARCHAR (40) NOT NULL,
	[CentroOrigen_Id]                  INT             NULL,
    [VinedoPropio_Id] INT NULL, 
    CONSTRAINT [PK_dbo.MovimientoDeBines] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_dbo.MovimientoDeBines_dbo.Material_Material_Id] FOREIGN KEY ([Material_Id]) REFERENCES [dbo].[Material] ([Id]),
	CONSTRAINT [FK_dbo.MovimientoDeBines_dbo.Centro_Centro_Id] FOREIGN KEY ([Centro_Id]) REFERENCES [dbo].[Centro] ([Id]),
    CONSTRAINT [FK_dbo.MovimientoDeBines_dbo.Centro_CentroOrigen_Id] FOREIGN KEY ([CentroOrigen_Id]) REFERENCES [dbo].[Centro] ([Id]),
	CONSTRAINT [FK_dbo.MovimientoDeBines_dbo.Proveedor_Proveedor_Id] FOREIGN KEY ([Proveedor_Id]) REFERENCES [dbo].[Proveedor] ([Id]),
	CONSTRAINT [FK_dbo.MovimientoDeBines_dbo.Vinedo_VinedoPropio_Id] FOREIGN KEY ([VinedoPropio_Id]) REFERENCES [dbo].[Vinedo] ([Id]),
);