create table NominacionDatoTecnico(
Id int IDENTITY (1, 1) NOT NULL,
MaterialPuerto_Id  int NOT NULL ,
CantidadTotal int NULL ,
Tolerancia int NULL ,
Observaciones varchar(500) null,
Vapor_Id int NOT null,
ETARecalada datetime ,
ObligacionDeCarga datetime, 
MuelleDeCarga_Id int NOT NULL, 
TasaDeCarga_Id int NOT NULL,
TasaDeCargaValor varchar(250),
DEM decimal(8,2),
DES decimal(8,2),
TipoContrato_Id int NOT NULL,
ATAPuerto_Id int NOT NULL,
AgenciaMaritimaPuerto_Id int NOT NULL,
Surveyor_Id int NOT NULL,
ObservacionesSurveyor varchar(500),
CONSTRAINT [PK_dbo.NominacionDatoTecnico] PRIMARY KEY CLUSTERED ([Id] ASC),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.MaterialPuerto_MaterialPuerto_Id] FOREIGN KEY ([MaterialPuerto_Id]) REFERENCES [dbo].[MaterialPuerto] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.Vapor_Vapor_Id] FOREIGN KEY ([Vapor_Id]) REFERENCES [dbo].[Vapor] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.MuelleDeCarga_MuelleDeCarga_Id] FOREIGN KEY ([MuelleDeCarga_Id]) REFERENCES [dbo].[MuelleDeCarga] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.TasaDeCarga_TasaDeCarga_Id] FOREIGN KEY ([TasaDeCarga_Id]) REFERENCES [dbo].[TasaDeCarga] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.ATAPuerto_ATAPuerto_Id] FOREIGN KEY ([ATAPuerto_Id]) REFERENCES [dbo].[ATAPuerto] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.AgenciaMaritimaPuerto_AgenciaMaritimaPuerto_Id] FOREIGN KEY ([AgenciaMaritimaPuerto_Id]) REFERENCES [dbo].[AgenciaMaritimaPuerto] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.Surveyor_Surveyor_Id] FOREIGN KEY ([Surveyor_Id]) REFERENCES [dbo].[Surveyor] ([Id]),

)