create table NominacionDatoTecnico(
Id int,
Nominacion_Id int,
MaterialPuerto_Id  int ,
CantidadTotal int ,
Tolterancia int ,
Observaciones varchar(500) null,
Vapor_Id int null,
ETARecalada datetime ,
ObligacionDeCarga datetime, 
MuelleDeCarga_Id int, 
TasaDeCarga_Id int,
TasaDeCarga_Valor varchar(250),
DEM decimal(8,2),
DES decimal(8,2),
TipoContrato_Id int,
ATAPuerto_Id int,
AgenciaMaritima_Id int,
Surveyor_Id int,
ObservacionesSurveyor varchar(500),
CONSTRAINT [PK_dbo.NominacionDatoTecnico] PRIMARY KEY CLUSTERED ([Id] ASC),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.Nominacion_Nominacion_Id] FOREIGN KEY ([Nominacion_Id]) REFERENCES [dbo].[Nominacion] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.MaterialPuerto_MaterialPuerto_Id] FOREIGN KEY ([MaterialPuerto_Id]) REFERENCES [dbo].[MaterialPuerto] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.Vapor_Vapor_Id] FOREIGN KEY ([Vapor_Id]) REFERENCES [dbo].[Vapor] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.MuelleDeCarga_MuelleDeCarga_Id] FOREIGN KEY ([MuelleDeCarga_Id]) REFERENCES [dbo].[MuelleDeCarga] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.TasaDeCarga_TasaDeCarga_Id] FOREIGN KEY ([TasaDeCarga_Id]) REFERENCES [dbo].[TasaDeCarga] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.ATAPuerto_ATAPuerto_Id] FOREIGN KEY ([ATAPuerto_Id]) REFERENCES [dbo].[ATAPuerto] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.AgenciaMaritimaPuerto_AgenciaMaritima_Id] FOREIGN KEY ([AgenciaMaritima_Id]) REFERENCES [dbo].[AgenciaMaritimaPuerto] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.Surveyor_Surveyor_Id] FOREIGN KEY ([Surveyor_Id]) REFERENCES [dbo].[Surveyor] ([Id]),

)