create table NominacionDatoTecnico(
Id int IDENTITY (1, 1) NOT NULL,
MaterialPuerto_Id  int NOT NULL ,
CantidadTotal int NOT NULL ,
Tolerancia int NULL ,
Observaciones varchar(500) null,
[VaporInformacion_Id] int NOT null,
ETARecalada datetime ,
ObligacionDeCarga datetime, 
MuelleDeCarga_Id int NOT NULL, 
TasaDeCarga_Id int  NULL,
TasaDeCargaValor INT  NULL,
DEM decimal(8,2),
DES decimal(8,2),
TipoDeContrato_Id int  NULL,
ATAPuerto_Id int NULL,
AgenciaMaritimaPuerto_Id int NULL,
Surveyor_Id int NULL,
ObservacionesSurveyor varchar(500),
CONSTRAINT [PK_dbo.NominacionDatoTecnico] PRIMARY KEY CLUSTERED ([Id] ASC),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.MaterialPuerto_MaterialPuerto_Id] FOREIGN KEY ([MaterialPuerto_Id]) REFERENCES [dbo].[MaterialPuerto] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.VaporInformacion_VaporInformacion_Id] FOREIGN KEY ([VaporInformacion_Id]) REFERENCES [dbo].[VaporInformacion] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.MuelleDeCarga_MuelleDeCarga_Id] FOREIGN KEY ([MuelleDeCarga_Id]) REFERENCES [dbo].[MuelleDeCarga] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.TasaDeCarga_TasaDeCarga_Id] FOREIGN KEY ([TasaDeCarga_Id]) REFERENCES [dbo].[TasaDeCarga] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.TipoDeContrato_TipoDeContrato_Id] FOREIGN KEY ([TipoDeContrato_Id]) REFERENCES [dbo].[TipoDeContrato] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.ATAPuerto_ATAPuerto_Id] FOREIGN KEY ([ATAPuerto_Id]) REFERENCES [dbo].[ATAPuerto] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.AgenciaMaritimaPuerto_AgenciaMaritimaPuerto_Id] FOREIGN KEY ([AgenciaMaritimaPuerto_Id]) REFERENCES [dbo].[AgenciaMaritimaPuerto] ([Id]),
CONSTRAINT [FK_dbo.NominacionDatoTecnico_dbo.Surveyor_Surveyor_Id] FOREIGN KEY ([Surveyor_Id]) REFERENCES [dbo].[Surveyor] ([Id]),

)