CREATE TABLE [dbo].[PuntosInteresGeolocalizacion] (
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](200) NOT NULL,
	[TipoUbicacion] [nvarchar](50) NULL,
	[Imagen] [nvarchar](100) NULL,
	[Puerto] [nvarchar](100) NULL,
	[Pais] [nvarchar](100) NULL,
	[HorasSanBenito] [decimal](18, 8) NULL,
	[Latitud] [nvarchar](80) NULL,
	[Longitud] [nvarchar](80) NULL,
	[DistanciaKm] [decimal](18,8) NULL,
	[RadioPunto] [decimal](18,8) NULL,
	[TipoZona] [nvarchar](80) NULL,
	[AgrupadorZona] [nvarchar](80) NULL,
	[PosicionZona] smallint NULL,
	[Estado] [smallint] NULL,
	[FechaRegistro] [datetime] NULL,
    CONSTRAINT [PK_dbo.PuntoInteresGeolocalizacion] PRIMARY KEY CLUSTERED ([Id] ASC),
);
