CREATE TABLE [dbo].[RomaneoItem] (
    [Id]				INT IDENTITY (1, 1) NOT NULL,
    [Romaneo_Id]		INT NOT NULL,
    CONSTRAINT	[FK_dbo.RomaneoItem_dbo.Romaneo_Romaneo_Id] FOREIGN KEY ([Romaneo_Id]) REFERENCES [dbo].[Romaneo] ([Id]) ON DELETE CASCADE,
    [Material_Id]		INT NOT NULL,
	CONSTRAINT	[FK_dbo.RomaneoItem_dbo.Material_Material_Id] FOREIGN KEY ([Material_Id]) REFERENCES [dbo].[Material] ([Id]),
    [Almacen_Id]		INT NOT NULL,
	CONSTRAINT	[FK_dbo.RomaneoItem_dbo.Almacen_Almacen_Id] FOREIGN KEY ([Almacen_Id]) REFERENCES [dbo].[Almacen] ([Id]),
    [LoteProveedor]		NVARCHAR (10) NULL,
    [PesoBruto]		DECIMAL(18, 2) NOT NULL,
    [PesoTara]		DECIMAL(18, 2) NOT NULL,
    [Fecha]		DATETIME NOT NULL DEFAULT GETDATE(),
	[FechaFabricacion]		DATETIME NULL,
	[ItemNro]	INT NOT NULL,
	CONSTRAINT [PK_dbo.RomaneoItem] PRIMARY KEY CLUSTERED ([Id] ASC),
	[DocMaterial]		NVARCHAR (20) NOT NULL,
	[EjercicioDocMaterial]		NVARCHAR (20) NOT NULL,
	[EjercicioDocMaterialAnulacion]		NVARCHAR (20) NULL,
	[RemitoNro]		NVARCHAR (20) NOT NULL, 
    [Rechazado] BIT NOT NULL,
	[FechaRemito]		DATETIME NOT NULL,
	[Balanza_Id]		INT NOT NULL,
	CONSTRAINT	[FK_dbo.RomaneoItem_dbo.Balanza_Balanza_Id] FOREIGN KEY ([Balanza_Id]) REFERENCES [dbo].[Balanza] ([Id]),
	[TaraRomaneo_Id]		INT NOT NULL,
	CONSTRAINT	[FK_dbo.RomaneoItem_dbo.TaraRomaneo_TaraRomaneo_Id] FOREIGN KEY ([TaraRomaneo_Id]) REFERENCES [dbo].[TaraRomaneo] ([Id]),
);