CREATE TABLE [dbo].[ZE7550TransmisionASap] (
	[Id]               INT NOT NULL,
	[NumCarPor] NVARCHAR (100) NULL,
	[PatenteAcoplado] NVARCHAR (100) NULL,
	[AgenteCompra] NVARCHAR (100) NULL,
	[Almacen] NVARCHAR (100) NULL,
	[Analisis] NVARCHAR (100) NULL,
	[Apariencia] NVARCHAR (100) NULL,
	[Balanza] NVARCHAR (100) NULL,
	[Bruto] int NULL,
	[BrutoOrigen] int NULL,
	[TrigoEspecial] NVARCHAR(100) NULL,
	[Camara] NVARCHAR (100) NULL,
	[Caratula] NVARCHAR (100) NULL,
	[Cargador] NVARCHAR (100) NULL,
	[CCPP] NVARCHAR (100) NULL,
	[Centro] NVARCHAR (100) NULL,
	[Chofer] NVARCHAR (100) NULL,
	[Clasificacion] NVARCHAR(150) NULL,
	[Contrato] NVARCHAR (100) NULL,
	[Corredor] NVARCHAR (100) NULL,
	[CosechaCartaPorte] NVARCHAR(100) NULL, 
	[CTG] NVARCHAR(100) NULL, 
	[CuentaOrden] NVARCHAR (100) NULL,
	[CuitDestinatarioCartaPorte] NVARCHAR(100) NULL, 
	[Destino] NVARCHAR (100) NULL,
	[EntradaSalida] NVARCHAR (100) NULL,
	[EstablecimientoCartaPorte] NVARCHAR(100) NULL,
	[EstadoSAP] NVARCHAR (100) NULL,
	[FechaAlta] NVARCHAR (100) NULL,
	[FechaBruto] NVARCHAR (100) NULL,
	[FechaCalado] NVARCHAR (100) NULL,
	[FechaEgreso] NVARCHAR (100) NULL,
	[FechaIngreso] NVARCHAR (100) NULL,
	[FechaNeto] NVARCHAR (100) NULL,
	[FechaTara] NVARCHAR (100) NULL,
	[FechaCtg] NVARCHAR(100) NULL, 
	[HoraBruto] NVARCHAR (100) NULL,
	[HoraCalado] NVARCHAR (100) NULL,
	[HoraEgreso] NVARCHAR (100) NULL,
	[HoraIngreso] NVARCHAR (100) NULL,
	[HoraNeto] NVARCHAR (100) NULL,
	[HoraTara] NVARCHAR (100) NULL, 
	[InterFlete] NVARCHAR(150) NULL,
	[Km] int NULL,
	[Material] NVARCHAR (100) NULL,
	[MuestraConjunto] NVARCHAR (100) NULL,
	[Neto] int NULL,
	[NetoOrigen] int NULL,
	[NroDocChofer] NVARCHAR (100) NULL,
	[Patente] NVARCHAR (100) NULL,
	[Pesada] NVARCHAR (100) NULL,
	[Prestador] NVARCHAR (100) NULL,
	[Proveedor] NVARCHAR (100) NULL,
	[Procedencia] NVARCHAR (100) NULL,
	[ProvProc] NVARCHAR (100) NULL,
	[Remitente] NVARCHAR (100) NULL,
	[Secuencia] NVARCHAR (100) NULL,
	[Tara] int NULL,
	[TaraOrigen] int NULL,
	[TipoDocChofer] NVARCHAR (100) NULL,
	[TipoComercial] NVARCHAR (100) NULL,
	[TipVehiculo] NVARCHAR (100) NULL,
	[Transportista] NVARCHAR (100) NULL,
	[Variedad] NVARCHAR (100) NULL,
	[NetoDescontado] int NULL,
	[FirmaPaga] NVARCHAR (100) NULL,
	[CuitSolicitante] NVARCHAR(100) NULL,
    CONSTRAINT [PK_dbo.ZMPES5170TransmisionASap] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_dbo.ZMPES5170TransmisionASap_dbo.TransmisionASapId] FOREIGN KEY ([Id]) REFERENCES [dbo].[TransmisionASap] ([Id]) ON DELETE CASCADE
);
GO
